# -*- coding: utf-8 -*-
"""SOTA_Object_Detection_Models_Compared.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S6WoKt-rXvMXDDqRiJ1ZT_memLIfz4qm

# State-of-the-Art Object Detectors, Compared End-to-End
### Train · Evaluate · Visualize · Analyze · Benchmark — Four Real Architectures Head-to-Head

---

This is a **practical, results-driven** companion to the concepts course. Instead of building detectors from scratch, here we take **four real, production-grade detector architectures** from `torchvision`, **fine-tune each end-to-end** on a realistic synthetic dataset, and then put them through a thorough, professional **evaluation and comparison** — the kind of analysis you'd run when choosing a detector for a real project.

**The four contenders** (deliberately spanning the major design families):

| Model | Family | Backbone | Why it's here |
|---|---|---|---|
| **SSDLite320** | single-stage, anchor-based | MobileNetV3 | the *fast & light* edge-deployment option |
| **Faster R-CNN** | **two-stage**, anchor-based | MobileNetV3-FPN | the classic *propose-then-classify* design |
| **RetinaNet** | single-stage, anchor-based | ResNet50-FPN | single-stage + **Focal Loss** |
| **FCOS** | single-stage, **anchor-free** | ResNet50-FPN | the modern *per-point* paradigm |

**What you'll produce and learn to read:**

- **Training curves** for every model on shared data.
- A full **COCO-style evaluation**: mAP@.5, mAP@[.5:.95], **per-class AP**, and **AP broken down by object size** (small/medium/large) — the breakdown that reveals each model's real weaknesses.
- **Precision–Recall curves**, **confidence-threshold sweeps** (precision/recall/F1), and a **confidence-calibration (reliability) diagram**.
- A **speed/efficiency benchmark** (latency, FPS, parameters, model size) and the canonical **speed-vs-accuracy trade-off plot**.
- **Qualitative side-by-side** detections on the same scenes, including hard small-object cases.
- A **TIDE-style error analysis** decomposing each model's mistakes (localization vs. classification vs. duplicates vs. background vs. missed) and a **confusion matrix**.
- A **master comparison table** and an evidence-based **"which model when"** discussion.

---

### How to run

1. **Runtime → Change runtime type → GPU.** Training four detectors is much faster on a GPU (a few minutes each on a T4; far slower on CPU).
2. **Runtime → Run all**, or step through to learn. A `CONFIG` block at the top controls dataset size, epochs, which models to train, and a **`QUICK_MODE`** for a fast end-to-end pass.
3. Everything is **self-contained**: the dataset is generated in-notebook. By default we download small **ImageNet-pretrained backbones** (standard transfer-learning practice — it makes fine-tuning fast and the results meaningful). Set `USE_PRETRAINED_BACKBONE = False` for a fully-offline run (expect to need more epochs).

> **A note on the data.** We use a controlled synthetic dataset so the notebook is fast, reproducible, and free of licensing/download friction — and so we can *know the exact ground truth* for clean analysis. The **code, pipeline, metrics, and analyses are exactly what you'd use on COCO or your own data**; you'd only swap the `Dataset`. Absolute mAP numbers here are not comparable to COCO leaderboards — the *relative* behavior and the *analysis techniques* are the lesson.

## 1. Setup & configuration

We import the stack and define a single `CONFIG` object that governs the whole run. Tweak it in one place. `QUICK_MODE` shrinks everything for a ~5-minute smoke test; the full defaults give more meaningful curves.
"""

import os, math, time, random, warnings, gc
from dataclasses import dataclass, field
from collections import defaultdict
from typing import List, Dict, Tuple, Callable

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
import matplotlib.cm as cm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

warnings.filterwarnings("ignore")          # torchvision emits benign warnings

SEED = 0
random.seed(SEED); np.random.seed(SEED)
torch.manual_seed(SEED); torch.cuda.manual_seed_all(SEED)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

@dataclass
class Config:
    img_size: int = 256
    # Which models to train. Comment out any to skip (saves time).
    models: tuple = ("ssdlite", "frcnn_mnv3", "retinanet", "fcos")
    n_train: int = 1200
    n_val: int = 280
    epochs: int = 8
    batch_size: int = 8
    lr: float = 5e-4
    use_pretrained_backbone: bool = True   # transfer learning (downloads ~small backbones)
    # internal detector input resize (keeps compute modest for our small images)
    min_size: int = 192
    max_size: int = 256
    eval_score_thresh: float = 0.05        # low: keep many dets for PR curves
    quick_mode: bool = False

CONFIG = Config()

# QUICK_MODE: fast end-to-end pass to verify everything before a full run.
if CONFIG.quick_mode:
    CONFIG.models = ("ssdlite", "frcnn_mnv3")
    CONFIG.n_train, CONFIG.n_val = 300, 80
    CONFIG.epochs, CONFIG.batch_size = 3, 8

print("PyTorch :", torch.__version__)
print("Device  :", DEVICE, "" if DEVICE.type == "cuda" else "(GPU strongly recommended for training)")
if DEVICE.type == "cuda":
    print("GPU     :", torch.cuda.get_device_name(0))
print("Config  :", CONFIG)

plt.rcParams.update({"figure.dpi": 110, "axes.grid": False, "font.size": 10})
# A consistent color per model across every plot in the notebook.
MODEL_COLORS = {"ssdlite": "#1f77b4", "frcnn_mnv3": "#ff7f0e",
                "retinanet": "#2ca02c", "fcos": "#d62728"}
MODEL_PRETTY = {"ssdlite": "SSDLite320-MNv3", "frcnn_mnv3": "FasterRCNN-MNv3",
                "retinanet": "RetinaNet-R50", "fcos": "FCOS-R50"}

"""## 2. A realistic synthetic detection dataset

To exercise the detectors properly we generate scenes that contain the difficulties of real detection:

- **4 object classes** — `circle`, `rectangle`, `triangle`, `ellipse` — for genuine multi-class confusion analysis.
- **A wide range of object sizes**, deliberately including **small objects** (the hardest case) so we can measure AP by size.
- **Textured, non-uniform backgrounds** and sensor-like noise, so objects aren't trivially separable.
- **Occlusion / clutter** — objects overlap, and labels remain the full analytic extent (as in real annotation).
- **Variable object counts** per image (1–8).

Ground-truth boxes are computed analytically as we render, so labels are exact. We also record each object's **size category** (small / medium / large) for the size-stratified evaluation later.
"""

CLASS_NAMES = ["background", "circle", "rectangle", "triangle", "ellipse"]
NUM_CLASSES = len(CLASS_NAMES)          # 5 (incl. background at 0)
CIRCLE, RECT, TRI, ELL = 1, 2, 3, 4

# Size bands (by box area, in pixels) for AP_small / AP_medium / AP_large.
SIZE_SMALL_MAX  = 26 ** 2
SIZE_MEDIUM_MAX = 56 ** 2

def _bg(img_size, rng):
    """Low-frequency textured background + slight vignette — not flat."""
    small = rng.uniform(0.55, 0.95, size=(8, 8, 3)).astype(np.float32)
    bg = np.array(_resize_np(small, img_size), dtype=np.float32)
    yy, xx = np.mgrid[0:img_size, 0:img_size]
    vign = 1.0 - 0.25 * (((xx - img_size/2)**2 + (yy - img_size/2)**2) /
                         (img_size/2)**2)
    return np.clip(bg * vign[..., None], 0, 1).astype(np.float32)

def _resize_np(a, size):
    """Bilinear upsample a small HxWxC array to size x size (no extra deps)."""
    t = torch.from_numpy(a).permute(2, 0, 1)[None]
    t = F.interpolate(t, size=(size, size), mode="bilinear", align_corners=False)
    return t[0].permute(1, 2, 0).numpy()

def _circle(img, cx, cy, r, color):
    H, W = img.shape[:2]; ys, xs = np.ogrid[:H, :W]
    img[(xs-cx)**2 + (ys-cy)**2 <= r*r] = color
    return [cx-r, cy-r, cx+r, cy+r]

def _ellipse(img, cx, cy, rx, ry, color):
    H, W = img.shape[:2]; ys, xs = np.ogrid[:H, :W]
    img[((xs-cx)/rx)**2 + ((ys-cy)/ry)**2 <= 1.0] = color
    return [cx-rx, cy-ry, cx+rx, cy+ry]

def _rect(img, cx, cy, w, h, color):
    H, W = img.shape[:2]
    x1, y1 = int(cx-w/2), int(cy-h/2); x2, y2 = int(cx+w/2), int(cy+h/2)
    img[max(0,y1):min(H,y2), max(0,x1):min(W,x2)] = color
    return [x1, y1, x2, y2]

def _triangle(img, cx, cy, s, color):
    H, W = img.shape[:2]
    apex, left, right = (cx, cy-s), (cx-s, cy+s), (cx+s, cy+s)
    ys, xs = np.mgrid[:H, :W]
    def side(p, q): return (q[0]-p[0])*(ys-p[1]) - (q[1]-p[1])*(xs-p[0])
    d1, d2, d3 = side(apex,left), side(left,right), side(right,apex)
    neg = (d1<0)|(d2<0)|(d3<0); pos = (d1>0)|(d2>0)|(d3>0)
    img[~(neg & pos)] = color
    return [cx-s, cy-s, cx+s, cy+s]

def size_category(box):
    area = max(0, (box[2]-box[0])) * max(0, (box[3]-box[1]))
    if area <= SIZE_SMALL_MAX:  return "small"
    if area <= SIZE_MEDIUM_MAX: return "medium"
    return "large"

def generate_scene(img_size=256, max_objects=8, rng=None):
    rng = rng or np.random
    img = _bg(img_size, rng)
    boxes, labels = [], []
    n = rng.randint(1, max_objects + 1)
    for _ in range(n):
        cls = rng.choice([CIRCLE, RECT, TRI, ELL])
        color = rng.uniform(0.0, 0.6, size=3).astype(np.float32)
        # Bias toward more small/medium objects (realistic + stresses detectors).
        scale_band = rng.choice(["small", "medium", "large"], p=[0.4, 0.4, 0.2])
        if scale_band == "small":   s = rng.randint(6, 13)
        elif scale_band == "medium": s = rng.randint(14, 28)
        else:                        s = rng.randint(30, 48)
        m = s + 2
        cx, cy = rng.randint(m, img_size-m), rng.randint(m, img_size-m)
        if cls == CIRCLE:   box = _circle(img, cx, cy, s, color)
        elif cls == RECT:   box = _rect(img, cx, cy, int(s*rng.uniform(1.0,2.0)),
                                        int(s*rng.uniform(1.0,2.0)), color)
        elif cls == TRI:    box = _triangle(img, cx, cy, s, color)
        else:               box = _ellipse(img, cx, cy, int(s*rng.uniform(1.0,1.8)),
                                           s, color)
        x1 = max(0, min(box[0], img_size-1)); y1 = max(0, min(box[1], img_size-1))
        x2 = max(0, min(box[2], img_size));   y2 = max(0, min(box[3], img_size))
        if x2-x1 >= 4 and y2-y1 >= 4:
            boxes.append([x1, y1, x2, y2]); labels.append(cls)
    img = np.clip(img + rng.normal(0, 0.025, img.shape).astype(np.float32), 0, 1)
    img = img.astype(np.float32)
    if not boxes:
        return generate_scene(img_size, max_objects, rng)
    return img, np.array(boxes, np.float32), np.array(labels, np.int64)

class DetectionDataset(Dataset):
    """Self-contained synthetic detection dataset (torchvision-compatible)."""
    def __init__(self, length, img_size=256, seed=0):
        self.length, self.img_size, self.seed = length, img_size, seed
    def __len__(self): return self.length
    def __getitem__(self, idx):
        rng = np.random.RandomState(self.seed * 1_000_003 + idx)
        img, boxes, labels = generate_scene(self.img_size, rng=rng)
        img = torch.from_numpy(img).permute(2, 0, 1).contiguous()
        target = {"boxes": torch.from_numpy(boxes),
                  "labels": torch.from_numpy(labels)}
        return img, target

def collate(batch):
    return [b[0] for b in batch], [b[1] for b in batch]

train_set = DetectionDataset(CONFIG.n_train, CONFIG.img_size, seed=1)
val_set   = DetectionDataset(CONFIG.n_val,   CONFIG.img_size, seed=777)
print(f"Train: {len(train_set)} images | Val: {len(val_set)} images "
      f"(disjoint seeds => no leakage)")

# Preview
def draw(ax, img, boxes, labels=None, scores=None, color="red", title=None, lw=2):
    im = img.permute(1,2,0).cpu().numpy() if torch.is_tensor(img) else img
    ax.imshow(np.clip(im,0,1)); ax.axis("off")
    if title: ax.set_title(title, fontsize=10)
    if boxes is None: return
    b = boxes.cpu().numpy() if torch.is_tensor(boxes) else np.asarray(boxes)
    for i,(x1,y1,x2,y2) in enumerate(b):
        ax.add_patch(Rectangle((x1,y1),x2-x1,y2-y1,fill=False,edgecolor=color,lw=lw))
        t = ""
        if labels is not None: t = CLASS_NAMES[int(labels[i])]
        if scores is not None: t += f" {float(scores[i]):.2f}"
        if t: ax.text(x1, max(y1-2,8), t, fontsize=7, color="white",
                      bbox=dict(facecolor=color, edgecolor="none", pad=0.5, alpha=0.85))

fig, axes = plt.subplots(2, 4, figsize=(16, 8))
for ax in axes.ravel():
    img, bx, lb = generate_scene(CONFIG.img_size, rng=np.random.RandomState(random.randint(0,9999)))
    draw(ax, img, bx, lb, color="red")
plt.suptitle("Synthetic detection scenes (4 classes · multi-scale · occlusion · texture)", y=0.98)
plt.tight_layout(); plt.show()

"""## 3. Dataset analysis

Before modeling, *understand your data* — a habit that prevents many downstream surprises. We profile the class balance, the object-size distribution (which sets expectations for AP-by-size), and how many objects appear per image (crowding). These statistics also help interpret the results: e.g., if "small" objects dominate, expect overall mAP to be dragged down by the universally-hard small-object case.
"""

# Collect statistics over a sample of the training set.
N_PROFILE = min(600, CONFIG.n_train)
cls_counts = defaultdict(int)
size_counts = defaultdict(int)
per_image = []
areas = []
for i in range(N_PROFILE):
    _, boxes, labels = generate_scene(CONFIG.img_size,
                                      rng=np.random.RandomState(1_000_003 + i))
    per_image.append(len(labels))
    for b, l in zip(boxes, labels):
        cls_counts[CLASS_NAMES[int(l)]] += 1
        size_counts[size_category(b)] += 1
        areas.append((b[2]-b[0])*(b[3]-b[1]))

fig, axes = plt.subplots(1, 4, figsize=(18, 4))
# class balance
cn = [c for c in CLASS_NAMES[1:]]
axes[0].bar(cn, [cls_counts[c] for c in cn], color="#4c72b0")
axes[0].set_title("Class distribution"); axes[0].set_ylabel("# instances")
axes[0].tick_params(axis='x', rotation=20)
# size category
order = ["small", "medium", "large"]
axes[1].bar(order, [size_counts[s] for s in order],
            color=["#dd8452", "#55a868", "#c44e52"])
axes[1].set_title("Object size categories"); axes[1].set_ylabel("# instances")
# objects per image
axes[2].hist(per_image, bins=range(1, max(per_image)+2), align="left",
             color="#8172b3", rwidth=0.85)
axes[2].set_title("Objects per image"); axes[2].set_xlabel("# objects")
# area distribution
axes[3].hist(np.sqrt(areas), bins=30, color="#937860")
axes[3].axvline(np.sqrt(SIZE_SMALL_MAX), color="k", ls="--", lw=1)
axes[3].axvline(np.sqrt(SIZE_MEDIUM_MAX), color="k", ls="--", lw=1)
axes[3].set_title("Object size (sqrt area, px)\ndashed = small/med/large bounds")
axes[3].set_xlabel("sqrt(area) px")
plt.suptitle(f"Dataset profile (n={N_PROFILE} images)", y=1.03)
plt.tight_layout(); plt.show()

total = sum(cls_counts.values())
print(f"Total instances profiled : {total}")
print(f"Mean objects / image     : {np.mean(per_image):.2f}")
print("Size mix                 : " +
      ", ".join(f"{s} {100*size_counts[s]/total:.0f}%" for s in order))
print("=> Many small objects: expect AP_small << AP_large for every model.")

"""## 4. The model zoo

We define a builder for each architecture behind a uniform interface. Every torchvision detector shares the same calling convention — `model(images, targets)` returns a **loss dict** in `train()` mode, and `model(images)` returns a list of **detection dicts** (`boxes`, `scores`, `labels`) in `eval()` mode — which is what lets us treat all four identically in one training/eval loop.

Two practical knobs we set on every model:

- **`min_size`/`max_size`** — torchvision detectors internally resize inputs (default up to 800–1333 px). Our scenes are 256 px; resizing them up to 800 would waste compute, so we cap the internal resize to keep training fast. *(This is a real, commonly-overlooked performance lever.)*
- **A low score threshold + generous `detections_per_img`** at eval time, so we retain enough low-confidence detections to draw full precision–recall curves.

`USE_PRETRAINED_BACKBONE` loads ImageNet-pretrained backbone weights (standard transfer learning) for fast, meaningful convergence.
"""

from torchvision.models.detection import (
    ssdlite320_mobilenet_v3_large, fasterrcnn_mobilenet_v3_large_fpn,
    retinanet_resnet50_fpn, fcos_resnet50_fpn)

def _bw(): return "DEFAULT" if CONFIG.use_pretrained_backbone else None

def build_ssdlite():
    # SSDLite fixes its own 320x320 input; score/detection knobs still apply.
    return ssdlite320_mobilenet_v3_large(
        weights=None, weights_backbone=_bw(), num_classes=NUM_CLASSES,
        score_thresh=0.01, detections_per_img=300)

def build_frcnn_mnv3():
    return fasterrcnn_mobilenet_v3_large_fpn(
        weights=None, weights_backbone=_bw(), num_classes=NUM_CLASSES,
        min_size=CONFIG.min_size, max_size=CONFIG.max_size,
        box_score_thresh=0.01, box_detections_per_img=300)

def build_retinanet():
    return retinanet_resnet50_fpn(
        weights=None, weights_backbone=_bw(), num_classes=NUM_CLASSES,
        min_size=CONFIG.min_size, max_size=CONFIG.max_size,
        score_thresh=0.01, detections_per_img=300)

def build_fcos():
    return fcos_resnet50_fpn(
        weights=None, weights_backbone=_bw(), num_classes=NUM_CLASSES,
        min_size=CONFIG.min_size, max_size=CONFIG.max_size,
        score_thresh=0.01, detections_per_img=300)

MODEL_BUILDERS = {"ssdlite": build_ssdlite, "frcnn_mnv3": build_frcnn_mnv3,
                  "retinanet": build_retinanet, "fcos": build_fcos}

MODEL_META = {  # for the comparison table / discussion
    "ssdlite":   dict(family="single-stage", anchors="anchor-based",
                      backbone="MobileNetV3", neck="lite-FPN"),
    "frcnn_mnv3":dict(family="two-stage",    anchors="anchor-based",
                      backbone="MobileNetV3", neck="FPN"),
    "retinanet": dict(family="single-stage", anchors="anchor-based (focal loss)",
                      backbone="ResNet50",    neck="FPN"),
    "fcos":      dict(family="single-stage", anchors="anchor-FREE",
                      backbone="ResNet50",    neck="FPN"),
}

def count_params(m): return sum(p.numel() for p in m.parameters())
def model_size_mb(m):
    return sum(p.numel()*p.element_size() for p in m.parameters()) / 1024**2

# Build each selected model once to report its profile (then free memory).
rows = []
for name in CONFIG.models:
    m = MODEL_BUILDERS[name]()
    rows.append({"model": MODEL_PRETTY[name], **MODEL_META[name],
                 "params (M)": round(count_params(m)/1e6, 2),
                 "size (MB)": round(model_size_mb(m), 1)})
    del m; gc.collect()
zoo_df = pd.DataFrame(rows).set_index("model")
print("Model zoo:")
zoo_df

"""## 5. The evaluation toolkit

A detector is only as trustworthy as its evaluation. We build a reusable toolkit — the same machinery (in spirit) as the official COCO evaluator — so every model is judged identically and fairly.

Core pieces:

- **`box_iou`** — vectorized pairwise IoU.
- **`average_precision`** — AP from a ranked list of detections via all-points interpolation, with optional **size filtering** and **ignore** logic (so we can compute AP_small / AP_medium / AP_large the COCO way: objects of other sizes are *ignored*, not counted as errors).
- **`evaluate_model`** — runs a model over the validation set **once**, caching all raw predictions (at a low score threshold). Every subsequent metric and plot reads from this cache, so the expensive forward passes happen only once per model.
- **`compute_all_metrics`** — turns cached predictions into mAP@.5, mAP@[.5:.95], per-class AP, and per-size AP.

We reuse `torchvision.ops.nms`/`box_iou` where the model already applied NMS internally; our job downstream is purely measurement.
"""

def box_iou(a, b):
    """Pairwise IoU. a:(N,4) b:(M,4) xyxy -> (N,M)."""
    if len(a) == 0 or len(b) == 0:
        return torch.zeros((len(a), len(b)))
    area_a = (a[:,2]-a[:,0]).clamp(min=0)*(a[:,3]-a[:,1]).clamp(min=0)
    area_b = (b[:,2]-b[:,0]).clamp(min=0)*(b[:,3]-b[:,1]).clamp(min=0)
    lt = torch.max(a[:,None,:2], b[None,:,:2])
    rb = torch.min(a[:,None,2:], b[None,:,2:])
    wh = (rb-lt).clamp(min=0); inter = wh[...,0]*wh[...,1]
    return inter / (area_a[:,None]+area_b[None,:]-inter).clamp(min=1e-9)

def _ap_from_pr(rec, prec):
    """All-points (COCO/VOC-2010) interpolation: area under PR envelope."""
    mrec = np.concatenate(([0.0], rec, [1.0]))
    mpre = np.concatenate(([0.0], prec, [0.0]))
    for i in range(len(mpre)-2, -1, -1):
        mpre[i] = max(mpre[i], mpre[i+1])
    idx = np.where(mrec[1:] != mrec[:-1])[0]
    return float(np.sum((mrec[idx+1]-mrec[idx])*mpre[idx+1]))

def average_precision(preds, gts, cls, iou_thr=0.5, area_range=None,
                      return_curve=False):
    """AP for one class at one IoU threshold, COCO-style size handling.

    preds/gts : per-image lists. pred dict has boxes,scores,labels (np);
                gt dict has boxes,labels (np).
    area_range: optional (min_area, max_area); GTs outside it are *ignored*
                (matched detections become neither TP nor FP) -> AP_S/M/L.
    """
    def in_range(box):
        if area_range is None: return True
        a = (box[2]-box[0])*(box[3]-box[1])
        return area_range[0] <= a < area_range[1]

    scored = []   # (score, img_idx, box)
    n_gt = 0
    gt_boxes, gt_keep, gt_used = [], [], []
    for i,(p,g) in enumerate(zip(preds, gts)):
        gm = g["labels"] == cls
        gb = g["boxes"][gm]
        keep = np.array([in_range(b) for b in gb], dtype=bool) if len(gb) \
               else np.zeros(0, bool)
        gt_boxes.append(gb); gt_keep.append(keep)
        gt_used.append(np.zeros(len(gb), bool))
        n_gt += int(keep.sum())
        pm = p["labels"] == cls
        for box, sc in zip(p["boxes"][pm], p["scores"][pm]):
            scored.append((float(sc), i, box))
    if n_gt == 0:
        return (0.0, np.array([0.]), np.array([0.])) if return_curve else 0.0
    scored.sort(key=lambda x: -x[0])
    tp = np.zeros(len(scored)); fp = np.zeros(len(scored))
    for k,(sc,i,box) in enumerate(scored):
        gb = gt_boxes[i]
        if len(gb) == 0: fp[k] = 1; continue
        ious = box_iou(torch.tensor(box[None]), torch.tensor(gb))[0].numpy()
        j = int(ious.argmax())
        if ious[j] >= iou_thr:
            if not gt_keep[i][j]:
                # matched an out-of-size-range GT -> ignore (neither TP nor FP)
                if not gt_used[i][j]: gt_used[i][j] = True
                continue
            if not gt_used[i][j]:
                tp[k] = 1; gt_used[i][j] = True
            else:
                fp[k] = 1                      # duplicate
        else:
            fp[k] = 1                          # poor localization / background
    tpc, fpc = np.cumsum(tp), np.cumsum(fp)
    rec = tpc / (n_gt + 1e-9)
    prec = tpc / (tpc + fpc + 1e-9)
    ap = _ap_from_pr(rec, prec)
    return (ap, rec, prec) if return_curve else ap

print("Metric primitives ready: box_iou, average_precision (+size/curve support).")

@torch.no_grad()
def collect_predictions(model, dataset, batch_size=8, score_thresh=0.05):
    """Run the model over a dataset ONCE; cache predictions + ground truth.
    Returns (preds, gts) as per-image lists of numpy dicts."""
    model.eval()
    loader = DataLoader(dataset, batch_size=batch_size, collate_fn=collate,
                        num_workers=2)
    preds, gts = [], []
    for images, targets in loader:
        images = [im.to(DEVICE) for im in images]
        outputs = model(images)
        for out, tgt in zip(outputs, targets):
            keep = out["scores"] >= score_thresh
            preds.append({"boxes": out["boxes"][keep].cpu().numpy(),
                          "scores": out["scores"][keep].cpu().numpy(),
                          "labels": out["labels"][keep].cpu().numpy()})
            gts.append({"boxes": tgt["boxes"].numpy(),
                        "labels": tgt["labels"].numpy()})
    return preds, gts

def compute_all_metrics(preds, gts):
    """COCO-style summary from cached predictions."""
    classes = list(range(1, NUM_CLASSES))
    iou_thrs = np.arange(0.5, 1.0, 0.05)
    # per-class AP@.5 and AP@[.5:.95]
    ap50 = {c: average_precision(preds, gts, c, 0.5) for c in classes}
    ap_coco = {c: float(np.mean([average_precision(preds, gts, c, t)
                                 for t in iou_thrs])) for c in classes}
    # per-size AP@.5 (averaged over classes)
    ranges = {"small": (0, SIZE_SMALL_MAX),
              "medium": (SIZE_SMALL_MAX, SIZE_MEDIUM_MAX),
              "large": (SIZE_MEDIUM_MAX, 1e9)}
    ap_size = {}
    for sname, rng in ranges.items():
        vals = [average_precision(preds, gts, c, 0.5, area_range=rng)
                for c in classes]
        ap_size[sname] = float(np.mean(vals))
    return {
        "mAP@.5": float(np.mean(list(ap50.values()))),
        "mAP@[.5:.95]": float(np.mean(list(ap_coco.values()))),
        "AP50_per_class": {CLASS_NAMES[c]: ap50[c] for c in classes},
        "AP_small": ap_size["small"], "AP_medium": ap_size["medium"],
        "AP_large": ap_size["large"],
    }

print("collect_predictions() and compute_all_metrics() ready.")

"""### Speed benchmark & error-analysis tools

Two more tools complete the kit:

- **`benchmark_latency`** — measures single-image inference time (with warmup, and CUDA synchronization when on GPU) → milliseconds/image and FPS. Speed is half of the real-world decision.
- **`categorize_errors`** — a **TIDE-style** decomposition of *what kind* of mistakes a model makes, at a fixed operating threshold. Every prediction is sorted into one of: **correct**, **duplicate**, **localization error** (right class, loose box), **classification error** (right place, wrong class), or **background error** (hallucination). Separately we count **missed** ground-truth objects (false negatives). This tells you *how to fix* a model, not just *that* it's imperfect — far more actionable than a single mAP number.
"""

@torch.no_grad()
def benchmark_latency(model, n_warmup=5, n_runs=40, img_size=None):
    """Return (ms_per_image, fps) for batch-1 inference."""
    model.eval()
    img_size = img_size or CONFIG.img_size
    x = [torch.rand(3, img_size, img_size, device=DEVICE)]
    for _ in range(n_warmup):
        model(x)
    if DEVICE.type == "cuda": torch.cuda.synchronize()
    t0 = time.time()
    for _ in range(n_runs):
        model(x)
    if DEVICE.type == "cuda": torch.cuda.synchronize()
    ms = (time.time() - t0) / n_runs * 1000
    return ms, 1000.0 / ms

def categorize_errors(preds, gts, score_thresh=0.3, iou_correct=0.5, iou_loc=0.1):
    """TIDE-lite error decomposition over the dataset at a fixed threshold.
    Returns dict of counts: correct, duplicate, localization, classification,
    background, missed."""
    cats = defaultdict(int)
    for p, g in zip(preds, gts):
        order = np.argsort(-p["scores"])
        pb, pl, ps = p["boxes"][order], p["labels"][order], p["scores"][order]
        sel = ps >= score_thresh
        pb, pl = pb[sel], pl[sel]
        gb, gl = g["boxes"], g["labels"]
        used = np.zeros(len(gb), bool)
        if len(gb):
            ious_all = box_iou(torch.tensor(pb), torch.tensor(gb)).numpy() \
                       if len(pb) else np.zeros((0, len(gb)))
        for k in range(len(pb)):
            if len(gb) == 0:
                cats["background"] += 1; continue
            ious = ious_all[k]
            j = int(ious.argmax()); best = ious[j]
            if best >= iou_correct:
                if gl[j] == pl[k]:
                    if not used[j]: cats["correct"] += 1; used[j] = True
                    else:           cats["duplicate"] += 1
                else:
                    cats["classification"] += 1     # right box, wrong class
            elif best >= iou_loc:
                # same class but loose box -> localization; else still background-ish
                cats["localization"] += 1 if gl[j] == pl[k] else 1
            else:
                cats["background"] += 1
        cats["missed"] += int((~used).sum())
    return dict(cats)

def confusion_matrix(preds, gts, score_thresh=0.3, iou_thr=0.5):
    """(NUM_CLASSES) x (NUM_CLASSES) matrix incl. background row/col.
    Row = true class (0=missed/background), Col = predicted (0=none)."""
    M = np.zeros((NUM_CLASSES, NUM_CLASSES), dtype=int)
    for p, g in zip(preds, gts):
        order = np.argsort(-p["scores"])
        pb, pl, ps = p["boxes"][order], p["labels"][order], p["scores"][order]
        sel = ps >= score_thresh; pb, pl = pb[sel], pl[sel]
        gb, gl = g["boxes"], g["labels"]
        used = np.zeros(len(gb), bool)
        ious_all = box_iou(torch.tensor(pb), torch.tensor(gb)).numpy() \
                   if (len(pb) and len(gb)) else np.zeros((len(pb), len(gb)))
        for k in range(len(pb)):
            if len(gb) == 0: M[0, pl[k]] += 1; continue
            j = int(ious_all[k].argmax())
            if ious_all[k][j] >= iou_thr and not used[j]:
                M[gl[j], pl[k]] += 1; used[j] = True
            else:
                M[0, pl[k]] += 1                 # predicted but no true match
        for j in range(len(gb)):
            if not used[j]: M[gl[j], 0] += 1     # true object missed
    return M

print("benchmark_latency, categorize_errors, confusion_matrix ready.")

"""## 6. Train every model end-to-end

One unified loop fine-tunes each architecture on the **same** training data with the **same** budget — the only fair way to compare. We use Adam with a cosine schedule and gradient clipping (detection losses can spike early). For each model we record the per-epoch loss and wall-clock time, then cache its validation predictions once for all downstream analysis.

> **Time:** on a Colab **T4 GPU**, the MobileNet models train in well under a minute per epoch; the ResNet50 models a bit more. The full default run is a few minutes per model. Use `QUICK_MODE` (top of notebook) for a fast smoke test. Results are stored in `RESULTS`, so you can re-run any analysis cell without retraining.
"""

def train_model(name, epochs=None, lr=None):
    """Fine-tune one model; return (model, history) with per-epoch loss/time."""
    epochs = epochs or CONFIG.epochs
    lr = lr or CONFIG.lr
    model = MODEL_BUILDERS[name]().to(DEVICE)
    loader = DataLoader(train_set, batch_size=CONFIG.batch_size, shuffle=True,
                        collate_fn=collate, num_workers=2, drop_last=True)
    opt = torch.optim.Adam([p for p in model.parameters() if p.requires_grad],
                           lr=lr, weight_decay=1e-4)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=epochs)
    hist = {"loss": [], "time": []}
    for ep in range(epochs):
        model.train(); t0 = time.time(); tot = 0.0; nb = 0
        for images, targets in loader:
            images = [im.to(DEVICE) for im in images]
            targets = [{k: v.to(DEVICE) for k, v in t.items()} for t in targets]
            loss_dict = model(images, targets)
            loss = sum(loss_dict.values())
            opt.zero_grad(); loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            opt.step(); tot += float(loss); nb += 1
        sched.step()
        hist["loss"].append(tot / nb); hist["time"].append(time.time() - t0)
        print(f"  [{MODEL_PRETTY[name]:18s}] epoch {ep+1:2d}/{epochs} "
              f"loss {hist['loss'][-1]:6.3f} ({hist['time'][-1]:4.1f}s)")
    return model, hist

# Train all selected models, caching predictions + metrics + speed in RESULTS.
RESULTS = {}
TRAINED = {}
for name in CONFIG.models:
    print(f"\n=== Training {MODEL_PRETTY[name]} ===")
    model, hist = train_model(name)
    print("  evaluating ...")
    preds, gts = collect_predictions(model, val_set,
                                     score_thresh=CONFIG.eval_score_thresh)
    metrics = compute_all_metrics(preds, gts)
    ms, fps = benchmark_latency(model)
    RESULTS[name] = {"history": hist, "preds": preds, "gts": gts,
                     "metrics": metrics, "ms": ms, "fps": fps,
                     "params": count_params(model), "size_mb": model_size_mb(model)}
    TRAINED[name] = model
    print(f"  mAP@.5={metrics['mAP@.5']:.3f}  "
          f"mAP@[.5:.95]={metrics['mAP@[.5:.95]']:.3f}  "
          f"{ms:.1f} ms/img ({fps:.0f} FPS)")
    gc.collect(); torch.cuda.empty_cache() if DEVICE.type=="cuda" else None
GTS = RESULTS[CONFIG.models[0]]["gts"]    # shared ground truth (same val set)
print("\nAll models trained & evaluated. RESULTS keys:", list(RESULTS.keys()))

"""## 7. Results & comparison

With every model trained and its predictions cached, we now turn numbers into insight. Each subsection below isolates one axis of comparison.

### 7.1 Training loss curves

The first sanity check: did training converge? Overlaid loss curves reveal convergence speed and stability. Different architectures have different loss *scales* (SSD's multi-box loss, R-CNN's four-term loss, focal loss) so don't compare absolute heights across models — compare each curve's *shape* (is it still descending? plateaued? noisy?).
"""

fig, ax = plt.subplots(figsize=(9, 5))
for name in CONFIG.models:
    h = RESULTS[name]["history"]["loss"]
    ax.plot(range(1, len(h)+1), h, "-o", color=MODEL_COLORS[name],
            label=MODEL_PRETTY[name], lw=2, ms=4)
ax.set_xlabel("epoch"); ax.set_ylabel("training loss")
ax.set_title("Training loss per model (compare shape, not absolute scale)")
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout(); plt.show()

# Average epoch time (a practical training-cost signal).
print("Mean training time per epoch:")
for name in CONFIG.models:
    t = np.mean(RESULTS[name]["history"]["time"])
    print(f"  {MODEL_PRETTY[name]:18s}: {t:5.1f} s/epoch")

"""### 7.2 Headline accuracy: mAP@.5 and mAP@[.5:.95]

The two standard summary numbers. **mAP@.5** is lenient (a box just needs 50% overlap). **mAP@[.5:.95]** (the primary COCO metric) averages over ten stricter thresholds and rewards *tight* localization — it's almost always much lower and is the more honest headline. The gap between the two tells you how precise each model's boxes are.
"""

labels = [MODEL_PRETTY[n] for n in CONFIG.models]
map50 = [RESULTS[n]["metrics"]["mAP@.5"] for n in CONFIG.models]
mapco = [RESULTS[n]["metrics"]["mAP@[.5:.95]"] for n in CONFIG.models]
colors = [MODEL_COLORS[n] for n in CONFIG.models]

x = np.arange(len(labels)); w = 0.38
fig, ax = plt.subplots(figsize=(10, 5))
b1 = ax.bar(x-w/2, map50, w, label="mAP@.5", color=colors, alpha=0.95)
b2 = ax.bar(x+w/2, mapco, w, label="mAP@[.5:.95]", color=colors, alpha=0.5,
            hatch="//")
ax.set_xticks(x); ax.set_xticklabels(labels, rotation=15)
ax.set_ylabel("mAP"); ax.set_title("Detection accuracy (higher is better)")
ax.legend()
for bars in (b1, b2):
    for b in bars:
        ax.text(b.get_x()+b.get_width()/2, b.get_height()+0.005,
                f"{b.get_height():.3f}", ha="center", fontsize=8)
ax.grid(alpha=0.3, axis="y")
plt.tight_layout(); plt.show()

best = labels[int(np.argmax(mapco))]
print(f"Best COCO mAP: {best}. The mAP@.5 - mAP@[.5:.95] gap reflects "
      "localization tightness (smaller gap = tighter boxes).")

"""### 7.3 Per-class AP — where does each model struggle?

Aggregate mAP hides per-class behavior. Some shapes are intrinsically harder (e.g., thin triangles have lots of background inside their box; ellipses resemble circles). A grouped bar chart exposes which classes drag a model down — directly informing where you'd add data or augmentation.
"""

classes = CLASS_NAMES[1:]
x = np.arange(len(classes)); w = 0.8/len(CONFIG.models)
fig, ax = plt.subplots(figsize=(11, 5))
for i, name in enumerate(CONFIG.models):
    perc = RESULTS[name]["metrics"]["AP50_per_class"]
    vals = [perc[c] for c in classes]
    ax.bar(x + i*w - 0.4 + w/2, vals, w, label=MODEL_PRETTY[name],
           color=MODEL_COLORS[name])
ax.set_xticks(x); ax.set_xticklabels(classes)
ax.set_ylabel("AP@.5"); ax.set_title("Per-class AP@.5 by model")
ax.legend(ncol=2); ax.grid(alpha=0.3, axis="y")
plt.tight_layout(); plt.show()

"""### 7.4 AP by object size — the small-object reality check

This is one of the most revealing plots in detection. **Small objects are universally the hardest** (few pixels, weak features, easily lost in downsampling). Models with high-resolution feature maps / FPN tend to do better on small objects. Expect every model's `AP_small` to be far below `AP_large` — and the *size of that gap* differentiates the architectures.
"""

sizes = ["AP_small", "AP_medium", "AP_large"]
x = np.arange(len(sizes)); w = 0.8/len(CONFIG.models)
fig, ax = plt.subplots(figsize=(10, 5))
for i, name in enumerate(CONFIG.models):
    vals = [RESULTS[name]["metrics"][s] for s in sizes]
    ax.bar(x + i*w - 0.4 + w/2, vals, w, label=MODEL_PRETTY[name],
           color=MODEL_COLORS[name])
ax.set_xticks(x); ax.set_xticklabels(["small", "medium", "large"])
ax.set_ylabel("AP@.5"); ax.set_title("AP by object size — small objects are hardest")
ax.legend(ncol=2); ax.grid(alpha=0.3, axis="y")
plt.tight_layout(); plt.show()
print("Takeaway: the small->large climb is steep for all models; the model with")
print("the highest AP_small is your pick for small-object-heavy applications.")

"""### 7.5 Precision–Recall curves

The PR curve shows the full precision/recall trade-off as the confidence threshold varies (AP is the area under it). A curve that stays high and to the right is better. We plot the curve for one representative class (averaged behavior is similar) for each model on shared axes.
"""

PR_CLASS = CIRCLE     # representative class for the PR-curve plot
fig, ax = plt.subplots(figsize=(8, 6))
for name in CONFIG.models:
    ap, rec, prec = average_precision(RESULTS[name]["preds"], GTS, PR_CLASS,
                                      0.5, return_curve=True)
    # sort by recall for a clean monotone-x plot
    order = np.argsort(rec)
    ax.plot(rec[order], prec[order], color=MODEL_COLORS[name], lw=2,
            label=f"{MODEL_PRETTY[name]} (AP={ap:.3f})")
ax.set_xlabel("Recall"); ax.set_ylabel("Precision")
ax.set_xlim(0, 1); ax.set_ylim(0, 1.02)
ax.set_title(f"Precision–Recall @IoU 0.5  (class: {CLASS_NAMES[PR_CLASS]})")
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout(); plt.show()

"""### 7.6 Speed & efficiency

Accuracy is only half the story; deployment cares about **latency, throughput (FPS), parameter count, and model size**. We measured per-image latency during evaluation. Note that the lightweight MobileNet models trade some accuracy for large speed/size advantages — exactly the design intent.
"""

names = list(CONFIG.models)
ms   = [RESULTS[n]["ms"] for n in names]
fps  = [RESULTS[n]["fps"] for n in names]
prm  = [RESULTS[n]["params"]/1e6 for n in names]
size = [RESULTS[n]["size_mb"] for n in names]
colors = [MODEL_COLORS[n] for n in names]
pretty = [MODEL_PRETTY[n] for n in names]

fig, axes = plt.subplots(1, 3, figsize=(16, 4.5))
axes[0].barh(pretty, fps, color=colors); axes[0].set_xlabel("FPS (higher=faster)")
axes[0].set_title(f"Throughput  ({DEVICE.type.upper()})")
for i,v in enumerate(fps): axes[0].text(v, i, f" {v:.0f}", va="center", fontsize=8)
axes[1].barh(pretty, prm, color=colors); axes[1].set_xlabel("parameters (M)")
axes[1].set_title("Model capacity")
for i,v in enumerate(prm): axes[1].text(v, i, f" {v:.1f}M", va="center", fontsize=8)
axes[2].barh(pretty, size, color=colors); axes[2].set_xlabel("size on disk (MB)")
axes[2].set_title("Storage footprint")
for i,v in enumerate(size): axes[2].text(v, i, f" {v:.0f}", va="center", fontsize=8)
for a in axes: a.grid(alpha=0.3, axis="x")
plt.tight_layout(); plt.show()

"""### 7.7 The speed–accuracy trade-off (the plot that decides deployments)

This single scatter — **accuracy (y) vs. speed (x)**, with bubble size encoding parameter count — is how the field communicates detector choices. The **upper-right** is the dream (fast *and* accurate). Real models lie on a trade-off frontier: you pick the point that fits your latency budget. There is rarely one "best" model — only the best *for a given constraint*.
"""

fig, ax = plt.subplots(figsize=(9, 6.5))
for n in CONFIG.models:
    r = RESULTS[n]
    ax.scatter(r["fps"], r["metrics"]["mAP@[.5:.95]"],
               s=80 + r["params"]/1e6*25, color=MODEL_COLORS[n],
               alpha=0.75, edgecolor="k", zorder=3)
    ax.annotate(f"{MODEL_PRETTY[n]}\n{r['params']/1e6:.1f}M params",
                (r["fps"], r["metrics"]["mAP@[.5:.95]"]),
                textcoords="offset points", xytext=(8, 6), fontsize=8)
ax.set_xlabel("Speed — FPS (higher = faster) →")
ax.set_ylabel("Accuracy — mAP@[.5:.95] (higher = better) ↑")
ax.set_title("Speed vs. Accuracy trade-off\n(bubble size ∝ parameters; upper-right is best)")
ax.grid(alpha=0.3)
ax.annotate("ideal", xy=(0.97, 0.97), xycoords="axes fraction", ha="right",
            fontsize=11, color="green", weight="bold")
plt.tight_layout(); plt.show()

"""### 7.8 Master comparison table

Everything in one place. This is the artifact you'd put in a report or README to justify a model choice.
"""

table = []
for n in CONFIG.models:
    r = RESULTS[n]; m = r["metrics"]
    table.append({
        "Model": MODEL_PRETTY[n],
        "Family": MODEL_META[n]["family"],
        "Anchors": MODEL_META[n]["anchors"],
        "Backbone": MODEL_META[n]["backbone"],
        "mAP@.5": round(m["mAP@.5"], 3),
        "mAP@[.5:.95]": round(m["mAP@[.5:.95]"], 3),
        "AP_S": round(m["AP_small"], 3),
        "AP_M": round(m["AP_medium"], 3),
        "AP_L": round(m["AP_large"], 3),
        "FPS": round(r["fps"], 1),
        "ms/img": round(r["ms"], 1),
        "Params(M)": round(r["params"]/1e6, 1),
        "Size(MB)": round(r["size_mb"], 0),
    })
comparison_df = pd.DataFrame(table).set_index("Model")
# Highlight the best in each "higher is better" accuracy/speed column.
def _hl(s):
    is_max = s == s.max()
    return ["background-color: #c8e6c9" if v else "" for v in is_max]
acc_cols = ["mAP@.5","mAP@[.5:.95]","AP_S","AP_M","AP_L","FPS"]
try:
    display(comparison_df.style.apply(_hl, subset=acc_cols, axis=0)
            .set_caption("Green = best in column (accuracy/speed)"))
except NameError:
    print(comparison_df.to_string())
comparison_df

"""## 8. Qualitative comparison — same scenes, every model

Numbers summarize; pictures explain. We run all models on identical validation scenes (including a deliberately hard, small-object-heavy one) and lay the detections side by side against ground truth. Watch for the characteristic failure modes: missed small objects, duplicate boxes, class confusions, and loose localization.
"""

@torch.no_grad()
def detect_one(model, img_tensor, score_thresh=0.4):
    model.eval()
    out = model([img_tensor.to(DEVICE)])[0]
    keep = out["scores"] >= score_thresh
    return (out["boxes"][keep].cpu(), out["labels"][keep].cpu(),
            out["scores"][keep].cpu())

# Pick a few varied validation images (one with many small objects).
def n_objects(i): return len(val_set[i][1]["labels"])
candidate = sorted(range(len(val_set)), key=lambda i: -n_objects(i))
show_idx = [candidate[0], candidate[len(candidate)//3], candidate[-1]]

ncol = 1 + len(CONFIG.models)
fig, axes = plt.subplots(len(show_idx), ncol, figsize=(4*ncol, 4*len(show_idx)))
if len(show_idx) == 1: axes = axes[None, :]
for r, idx in enumerate(show_idx):
    img, tgt = val_set[idx]
    draw(axes[r, 0], img, tgt["boxes"], tgt["labels"], color="lime",
         title="Ground truth" if r == 0 else None)
    if r != 0: axes[r,0].set_title("")
    axes[r,0].set_ylabel(f"scene {idx}\n({len(tgt['labels'])} objects)", fontsize=9)
    for c, name in enumerate(CONFIG.models, start=1):
        b, l, s = detect_one(TRAINED[name], img, score_thresh=0.4)
        draw(axes[r, c], img, b, l, s, color=MODEL_COLORS[name],
             title=MODEL_PRETTY[name] if r == 0 else None)
plt.suptitle("Green = ground truth · colored = each model's detections (score ≥ 0.4)",
             y=1.0, fontsize=12)
plt.tight_layout(); plt.show()

"""## 9. Error analysis — *why* each model is wrong

mAP tells you a model is imperfect; **error decomposition tells you how to fix it.** Using the TIDE-style categories, we classify every confident prediction and count missed objects. The stacked bars below show each model's *error fingerprint*:

- **Background** errors dominate → the model hallucinates; raise the score threshold or add hard negatives.
- **Localization** errors dominate → boxes are loose; improve regression / use a tighter-IoU loss.
- **Classification** errors → confusable classes; add data or features.
- **Duplicate** errors → NMS too lenient.
- **Missed** (false negatives) → recall problem; lower threshold, better small-object handling, or more anchors/queries.
"""

ERR_ORDER = ["correct", "localization", "classification", "duplicate",
             "background", "missed"]
ERR_COLORS = {"correct": "#2ca02c", "localization": "#ff7f0e",
              "classification": "#9467bd", "duplicate": "#17becf",
              "background": "#d62728", "missed": "#7f7f7f"}

err_by_model = {}
for name in CONFIG.models:
    err_by_model[name] = categorize_errors(RESULTS[name]["preds"], GTS,
                                           score_thresh=0.3)

fig, ax = plt.subplots(figsize=(11, 5))
x = np.arange(len(CONFIG.models)); bottom = np.zeros(len(CONFIG.models))
for cat in ERR_ORDER:
    vals = np.array([err_by_model[n].get(cat, 0) for n in CONFIG.models], float)
    ax.bar(x, vals, bottom=bottom, label=cat, color=ERR_COLORS[cat])
    bottom += vals
ax.set_xticks(x); ax.set_xticklabels([MODEL_PRETTY[n] for n in CONFIG.models],
                                     rotation=15)
ax.set_ylabel("count (predictions @ score≥0.3, plus missed GTs)")
ax.set_title("Error decomposition per model (TIDE-style)")
ax.legend(ncol=3, fontsize=8)
plt.tight_layout(); plt.show()

# Print the normalized error profile (excluding 'correct') for quick reading.
print("Error mix (share of mistakes, excluding correct detections):")
for name in CONFIG.models:
    d = err_by_model[name]
    mistakes = {k: d.get(k,0) for k in ERR_ORDER if k != "correct"}
    tot = sum(mistakes.values()) or 1
    s = ", ".join(f"{k} {100*v/tot:.0f}%" for k,v in mistakes.items())
    print(f"  {MODEL_PRETTY[name]:18s}: {s}")

"""### 9.1 Confusion matrix

Which classes get mistaken for which? Rows are the true class (plus a *missed* row, index 0); columns are the predicted class (plus a *no-detection* column). A clean detector has mass on the diagonal; off-diagonal mass reveals systematic class confusions, and the first row/column quantify misses and hallucinations. We show it for the most accurate model.
"""

best_name = max(CONFIG.models, key=lambda n: RESULTS[n]["metrics"]["mAP@[.5:.95]"])
M = confusion_matrix(RESULTS[best_name]["preds"], GTS, score_thresh=0.3)
ticks = ["(none)"] + CLASS_NAMES[1:]

fig, ax = plt.subplots(figsize=(7, 6))
im = ax.imshow(M, cmap="Blues")
ax.set_xticks(range(NUM_CLASSES)); ax.set_xticklabels(ticks, rotation=30, ha="right")
ax.set_yticks(range(NUM_CLASSES)); ax.set_yticklabels(ticks)
ax.set_xlabel("Predicted"); ax.set_ylabel("True")
ax.set_title(f"Confusion matrix — {MODEL_PRETTY[best_name]}\n"
             "(row 0 = false positives, col 0 = missed objects)")
for i in range(NUM_CLASSES):
    for j in range(NUM_CLASSES):
        ax.text(j, i, M[i,j], ha="center", va="center",
                color="white" if M[i,j] > M.max()*0.5 else "black", fontsize=9)
plt.colorbar(im, fraction=0.046); plt.tight_layout(); plt.show()

"""## 10. Operating-point & robustness analyses

A trained detector isn't deployed as-is — you choose its **operating point**: the confidence threshold (how sure before reporting) and the NMS IoU threshold (how aggressively to merge). These choices trade precision against recall and aren't captured by mAP (which integrates over all thresholds). Here we make the trade-offs explicit.

### 10.1 Confidence-threshold sweep → precision / recall / F1

As you raise the score threshold, precision rises (fewer false alarms) but recall falls (more misses). The **F1-optimal threshold** is a common deployment choice. We sweep it for each model on one class.
"""

def pr_at_threshold(preds, gts, cls, score_thr, iou_thr=0.5):
    tp = fp = 0; n_gt = 0
    for p, g in zip(preds, gts):
        gm = g["labels"] == cls; gb = g["boxes"][gm]; n_gt += len(gb)
        used = np.zeros(len(gb), bool)
        pm = (p["labels"] == cls) & (p["scores"] >= score_thr)
        pb = p["boxes"][pm]; psc = p["scores"][pm]
        for box in pb[np.argsort(-psc)]:
            if len(gb) == 0: fp += 1; continue
            ious = box_iou(torch.tensor(box[None]), torch.tensor(gb))[0].numpy()
            j = int(ious.argmax())
            if ious[j] >= iou_thr and not used[j]: tp += 1; used[j] = True
            else: fp += 1
    prec = tp/(tp+fp+1e-9); rec = tp/(n_gt+1e-9)
    f1 = 2*prec*rec/(prec+rec+1e-9)
    return prec, rec, f1

thrs = np.linspace(0.05, 0.95, 19)
fig, axes = plt.subplots(1, len(CONFIG.models), figsize=(4.2*len(CONFIG.models), 4),
                         sharey=True)
if len(CONFIG.models) == 1: axes = [axes]
for ax, name in zip(axes, CONFIG.models):
    P, R, Fs = [], [], []
    for t in thrs:
        p, r, f = pr_at_threshold(RESULTS[name]["preds"], GTS, CIRCLE, t)
        P.append(p); R.append(r); Fs.append(f)
    ax.plot(thrs, P, label="precision", color="#1f77b4")
    ax.plot(thrs, R, label="recall", color="#ff7f0e")
    ax.plot(thrs, Fs, label="F1", color="#2ca02c", lw=2.5)
    bt = thrs[int(np.argmax(Fs))]
    ax.axvline(bt, ls="--", color="gray")
    ax.set_title(f"{MODEL_PRETTY[name]}\nF1-best thr ≈ {bt:.2f}", fontsize=10)
    ax.set_xlabel("score threshold"); ax.grid(alpha=0.3)
axes[0].set_ylabel(f"metric (class: {CLASS_NAMES[CIRCLE]})"); axes[0].legend(fontsize=8)
plt.suptitle("Confidence threshold sweep — precision/recall/F1 trade-off", y=1.04)
plt.tight_layout(); plt.show()

"""### 10.2 NMS IoU-threshold sweep

NMS removes duplicate boxes; its IoU threshold controls aggressiveness. Too low → it deletes legitimately-close neighbors (recall drops in crowded scenes); too high → duplicates survive (precision drops). We re-apply NMS to the cached detections at several thresholds and measure mAP@.5, isolating this one knob.
"""

from torchvision.ops import nms as tv_nms

def renms_predictions(preds, iou_thr):
    """Re-run class-aware NMS on cached detections at a given IoU threshold."""
    out = []
    for p in preds:
        boxes = torch.tensor(p["boxes"]); scores = torch.tensor(p["scores"])
        labels = torch.tensor(p["labels"])
        keep_all = []
        for c in labels.unique():
            idx = torch.where(labels == c)[0]
            if len(idx) == 0: continue
            k = tv_nms(boxes[idx], scores[idx], iou_thr)
            keep_all.append(idx[k])
        keep = torch.cat(keep_all) if keep_all else torch.empty(0, dtype=torch.long)
        out.append({"boxes": boxes[keep].numpy(), "scores": scores[keep].numpy(),
                    "labels": labels[keep].numpy()})
    return out

nms_thrs = [0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
fig, ax = plt.subplots(figsize=(9, 5))
for name in CONFIG.models:
    ys = []
    for it in nms_thrs:
        rp = renms_predictions(RESULTS[name]["preds"], it)
        ap = np.mean([average_precision(rp, GTS, c, 0.5)
                      for c in range(1, NUM_CLASSES)])
        ys.append(ap)
    ax.plot(nms_thrs, ys, "-o", color=MODEL_COLORS[name], label=MODEL_PRETTY[name])
ax.set_xlabel("NMS IoU threshold"); ax.set_ylabel("mAP@.5")
ax.set_title("Effect of NMS IoU threshold on accuracy")
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout(); plt.show()
print("Note: the models already applied internal NMS; this re-NMS on retained")
print("boxes illustrates sensitivity. Tune this per dataset (crowded => higher).")

"""### 10.3 Confidence calibration (reliability diagram)

When a model says *"0.9 confident,"* is it right 90% of the time? A **well-calibrated** detector's confidence matches its actual precision. We bin detections by confidence and plot mean confidence vs. empirical precision; the diagonal is perfect calibration. Detectors are often *over*-confident — important to know if you set thresholds or fuse scores downstream.
"""

def calibration(preds, gts, iou_thr=0.5, n_bins=10):
    """Return (bin_centers, empirical_precision, mean_conf, counts)."""
    confs, correct = [], []
    for p, g in zip(preds, gts):
        order = np.argsort(-p["scores"])
        pb, pl, ps = p["boxes"][order], p["labels"][order], p["scores"][order]
        used = defaultdict(lambda: np.zeros(len(g["boxes"]), bool))
        for box, lab, sc in zip(pb, pl, ps):
            gm = np.where(g["labels"] == lab)[0]
            ok = 0
            if len(gm):
                ious = box_iou(torch.tensor(box[None]),
                               torch.tensor(g["boxes"][gm]))[0].numpy()
                j = int(ious.argmax())
                if ious[j] >= iou_thr and not used[lab][gm[j]]:
                    ok = 1; used[lab][gm[j]] = True
            confs.append(sc); correct.append(ok)
    confs = np.array(confs); correct = np.array(correct)
    edges = np.linspace(0, 1, n_bins+1)
    centers, emp, mc, cnt = [], [], [], []
    for i in range(n_bins):
        m = (confs >= edges[i]) & (confs < edges[i+1])
        if m.sum() == 0: continue
        centers.append((edges[i]+edges[i+1])/2)
        emp.append(correct[m].mean()); mc.append(confs[m].mean()); cnt.append(int(m.sum()))
    return np.array(centers), np.array(emp), np.array(mc), np.array(cnt)

fig, ax = plt.subplots(figsize=(7, 6.5))
ax.plot([0,1],[0,1],"k--",label="perfect calibration")
for name in CONFIG.models:
    c, emp, mc, cnt = calibration(RESULTS[name]["preds"], GTS)
    ax.plot(mc, emp, "-o", color=MODEL_COLORS[name], label=MODEL_PRETTY[name], ms=4)
ax.set_xlabel("mean predicted confidence"); ax.set_ylabel("empirical precision")
ax.set_title("Reliability diagram\n(below diagonal = over-confident)")
ax.set_xlim(0,1); ax.set_ylim(0,1); ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout(); plt.show()

"""## 11. Discussion — which model, when?

Pulling the threads together. The exact numbers depend on your run (data, epochs, hardware), but the **architectural tendencies** below are robust and match the broader literature:

**SSDLite (MobileNetV3) — the edge/real-time choice.**
Smallest and fastest by a wide margin. Gives up some accuracy, especially on small objects (its lite feature pyramid is coarse). Pick it for phones, embedded devices, or high-FPS video where latency and size dominate.

**Faster R-CNN (MobileNetV3-FPN) — the balanced two-stage baseline.**
The region-proposal stage filters candidates before classification, which historically helps precision and small-object recall. Heavier than SSDLite but still modest with a MobileNet backbone. A dependable default when accuracy matters more than raw speed.

**RetinaNet (ResNet50-FPN) — single-stage accuracy via Focal Loss.**
Dense single-stage prediction with Focal Loss tackling the foreground/background imbalance. Strong accuracy with a heavier backbone; a good pick when you want single-stage simplicity without the accuracy penalty SSD pays.

**FCOS (ResNet50-FPN) — anchor-free and clean.**
No anchor hyperparameters to tune (scales/ratios), per-point prediction with center-ness. Comparable accuracy to RetinaNet with a conceptually simpler head; representative of where modern detection design has moved.

**A decision checklist:**

1. **Latency/size budget?** Tight → SSDLite or a MobileNet two-stage. Generous → ResNet50 models or larger.
2. **Small objects critical?** Favor FPN-based models; check the **AP_small** column, not just mAP.
3. **Precision vs. recall priority?** Use the **threshold-sweep** plot to set your operating point, not the default.
4. **Crowded scenes?** Mind the **NMS** sensitivity; consider Soft-NMS.
5. **Trust the scores downstream?** Check the **reliability diagram** — recalibrate if over-confident.
6. **Diagnosing a weak model?** Read its **error fingerprint** before changing the architecture — the fix (more data vs. better boxes vs. NMS tuning) depends on which error dominates.

**Honest caveats about this study (good experimental hygiene):**

- The data is **synthetic and relatively easy**; absolute mAP won't transfer to COCO, and the *ordering* of models could differ on real data. Treat this as a **methodology** template.
- Training budgets are **small** for a notebook; with more epochs/data the gaps would shift. A fair comparison fixes the budget (we did) but a *sufficient* budget matters for conclusions.
- We used **pretrained backbones**; from-scratch results would differ and need far more training.
- Single-run numbers carry **variance** — for publishable claims you'd average several seeds and report error bars.

> **Staying current.** This lineup reflects well-established, widely-available architectures. The frontier (DETR-family models like DINO, and recent YOLO/RT-DETR releases) moves quickly; specific "best" claims are time-sensitive and worth verifying against current benchmarks. The *evaluation and analysis techniques* in this notebook, however, apply to any detector — including whatever is state-of-the-art when you read this.

## 12. Summary

You took four real, architecturally-distinct detectors and ran a **complete, professional comparison pipeline**:

- Generated and **profiled** a realistic multi-class, multi-scale dataset.
- **Fine-tuned** every model under an identical budget with one unified loop.
- Built a **COCO-style evaluation toolkit** (AP, per-class AP, AP-by-size, PR curves) and a **speed benchmark**.
- Produced the full comparison suite: **training curves, accuracy bars, per-class & per-size AP, PR curves, efficiency bars, the speed–accuracy trade-off, and a master table**.
- Compared models **qualitatively** on shared scenes.
- Diagnosed *why* models fail with **TIDE-style error decomposition** and a **confusion matrix**.
- Made operating-point trade-offs explicit via **threshold sweeps, NMS sensitivity, and a calibration diagram**.
- Distilled it into an evidence-based **"which model when"** guide.

**The transferable skill** is not the specific result — it's the *workflow*: train fairly, evaluate rigorously across multiple axes (accuracy, size, speed, calibration), diagnose errors by category, and choose a model against explicit constraints. Swap `DetectionDataset` for your own data and this entire notebook becomes your model-selection harness.
"""

print("="*66)
print("  SOTA DETECTOR COMPARISON — COMPLETE")
print("="*66)
try:
    print("\nFinal leaderboard (by COCO mAP):\n")
    lb = comparison_df.sort_values("mAP@[.5:.95]", ascending=False)
    print(lb[["Family","mAP@.5","mAP@[.5:.95]","AP_S","FPS","Params(M)"]].to_string())
except Exception:
    pass
print("""
Pipeline you can reuse on real data:
  profile data -> train (fair budget) -> cache predictions
  -> evaluate (mAP, per-class, per-size, PR) -> benchmark speed
  -> trade-off plot -> qualitative review -> error decomposition
  -> threshold/NMS/calibration tuning -> pick model for YOUR constraints

Swap DetectionDataset for COCO/VOC/your data; everything else carries over.
""")