# -*- coding: utf-8 -*-
"""OpenCV_Comprehensive_Tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15K9V2MeE2TyBVqrQP6BJbBAeqVEdoLgO

# 👨‍💻 About the Author

Welcome to this comprehensive tutorial! This notebook is curated and maintained by **Mohammad Javad Ahmadi**, a specialist in bridging the gap between cutting-edge AI research and production-grade software.

### **Mohammad Javad Ahmadi**
*CTO at MediversAI | Head of ARAS AI Group | Ph.D. Candidate in Electrical & Control Engineering*

With over 8 years of experience in architecting complex AI pipelines, Mohammad Javad leads technical teams in developing scalable SaaS solutions for **MedTech** and **FinTech**. His expertise includes:

*   **Advanced Computer Vision:** Real-time surgical video understanding, 3D-CNNs, and medical imaging analysis.
*   **Generative AI:** Multi-modal GenAI (LLMs/VLMs) and Autonomous Agentic Systems.
*   **Technical Leadership:** Directing R&D strategies and mentoring 60+ developers and researchers.

He has been recognized as an innovation leader by **Alberta Machine Intelligence Institute (Amii)** and has received prestigious grants for his work on AI-powered surgical assessment systems.

---
*Connect or explore more:*
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Profile-blue?style=flat&logo=linkedin)](https://www.linkedin.com/in/mjahmadi/)
[![GitHub](https://img.shields.io/badge/GitHub-Profile-black?style=flat&logo=github)](https://github.com/MJAHMADEE)
[![Google Scholar](https://img.shields.io/badge/Google%20Scholar-Publications-red?style=flat&logo=google-scholar)](https://scholar.google.com/citations?user=wTnN9IEAAAAJ&hl=en)

# 🖼️ Comprehensive OpenCV Tutorial for Google Colab

Welcome! This notebook is a hands-on, end-to-end introduction to **OpenCV** (Open Source Computer Vision Library) using Python. It is designed to run on **Google Colab** with no local setup required.

## 📚 What you'll learn

1. **Setup** — Installing OpenCV, verifying versions, importing libraries
2. **Image basics** — Loading, displaying, saving, understanding pixels
3. **Color spaces** — BGR, RGB, Grayscale, HSV
4. **Drawing** — Lines, rectangles, circles, polygons, text
5. **Image transformations** — Resize, crop, rotate, flip, translate, affine, perspective
6. **Arithmetic & bitwise operations** — Blending, masking
7. **Thresholding** — Binary, adaptive, Otsu
8. **Smoothing & filtering** — Blur, Gaussian, median, bilateral
9. **Morphological operations** — Erosion, dilation, opening, closing
10. **Edge detection** — Sobel, Laplacian, Canny
11. **Contours** — Finding, drawing, and analyzing shapes
12. **Histograms** — Computing and equalizing
13. **Feature detection** — Corners (Harris, Shi-Tomasi) and keypoints (ORB)
14. **Face detection** — Using Haar cascades
15. **Video basics** — Reading video files (Colab-friendly)

Every cell prints **detailed metadata** (shapes, dtypes, min/max values, library versions, etc.) so you can verify what is happening at each step.

> 💡 **Tip:** OpenCV uses **BGR** color order by default (not RGB). Matplotlib uses **RGB**. We'll convert between them whenever we display images.

---
# 1. 🛠️ Setup and Installation

Google Colab comes with OpenCV pre-installed, but we'll verify the installation, upgrade if needed, and import all the supporting libraries we'll use throughout the tutorial.

## 1.1 Install / Upgrade OpenCV

We use `opencv-contrib-python` because it includes the **main modules** plus **extra contributed modules** (like SIFT, extended feature detectors, etc.). On Colab, OpenCV is usually already available — running `pip install` confirms the version.

The `-q` flag keeps the output quiet, but pip will still report the final installed version.
"""

# Install OpenCV (contrib version includes extra algorithms)
# On Colab this is usually already installed; this cell verifies/updates it.
!pip install -q opencv-contrib-python
!pip show opencv-contrib-python

"""## 1.2 Import libraries and print versions

We import:
- **`cv2`** — The OpenCV Python bindings
- **`numpy`** — OpenCV images are NumPy arrays under the hood
- **`matplotlib.pyplot`** — For displaying images inline in the notebook
- **`os`, `urllib.request`** — For downloading sample images

Printing each library's version helps with reproducibility — if something behaves differently for you, the version is the first thing to check.

"""

# Commented out IPython magic to ensure Python compatibility.
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import os
import sys
import urllib.request
import skimage
from skimage import data as skdata

# Configure matplotlib for inline display in the notebook
# %matplotlib inline

# Make plots a bit larger by default so images are easier to read
plt.rcParams['figure.figsize'] = (8, 6)
plt.rcParams['figure.dpi'] = 90

# Print versions so we can verify the environment
print("=" * 60)
print("ENVIRONMENT INFORMATION")
print("=" * 60)
print(f"Python version    : {sys.version.split()[0]}")
print(f"OpenCV version    : {cv2.__version__}")
print(f"NumPy version     : {np.__version__}")
print(f"Matplotlib version: {matplotlib.__version__}")
print("=" * 60)

# OpenCV build information (a brief slice — full info is very long)
build_info = cv2.getBuildInformation()
# Show just the first ~15 lines so we know which modules/CUDA/etc are available
print("\nOpenCV Build Information (first 15 lines):")
print("-" * 60)
for line in build_info.splitlines()[:15]:
    print(line)

"""## 1.3 Helper function to display images

Because OpenCV stores color images in **BGR** order, but matplotlib expects **RGB**, we'll write a small helper that handles both color and grayscale images correctly. We'll use this helper throughout the notebook so every visualization is consistent.

"""

def show(image, title="Image", cmap=None, figsize=(8, 6)):
    """
    Display an OpenCV image inline using matplotlib.

    Parameters
    ----------
    image  : np.ndarray  -- the image (grayscale 2D, or BGR 3D)
    title  : str         -- plot title
    cmap   : str or None -- matplotlib colormap (auto-picks 'gray' for 2D)
    figsize: tuple       -- figure size in inches
    """
    plt.figure(figsize=figsize)

    if len(image.shape) == 2:
        # Grayscale image: use a gray colormap
        plt.imshow(image, cmap=cmap or 'gray', vmin=0, vmax=255)
    else:
        # Color image: convert BGR (OpenCV default) -> RGB (matplotlib default)
        plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

    plt.title(title)
    plt.axis('off')
    plt.show()


def show_grid(images, titles, cols=2, figsize=(12, 8)):
    """
    Display multiple images side by side in a grid.
    Useful for before/after comparisons.
    """
    n = len(images)
    rows = (n + cols - 1) // cols
    plt.figure(figsize=figsize)
    for i, (img, t) in enumerate(zip(images, titles)):
        plt.subplot(rows, cols, i + 1)
        if len(img.shape) == 2:
            plt.imshow(img, cmap='gray', vmin=0, vmax=255)
        else:
            plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        plt.title(t)
        plt.axis('off')
    plt.tight_layout()
    plt.show()


print("Helper functions `show()` and `show_grid()` are ready to use.")

"""---
# 2. 🌄 Loading Sample Images

We need some images to work with. Instead of downloading from the internet (which can fail behind firewalls or due to 403 errors), we'll use **scikit-image's bundled sample images** — they are pre-installed on Colab and ship with the library, so no network is required.

The images we'll use are all classics from the computer-vision and robotics literature:

| File we save | Source (skimage.data) | Why it matters in CV / robotics |
|--------------|-----------------------|---------------------------------|
| `astronaut.jpg` | `data.astronaut()` | A standard color test image — replaces "Astronaut". Rich in skin tones, hair, and fine detail. |
| `coffee.jpg`    | `data.coffee()`    | Color photo with strong texture and circular objects (cup rim) — great for contours and circles. |
| `coins.jpg`     | `data.coins()`     | Grayscale coins on a background — the textbook example for **thresholding, morphology, contours, and object counting**. |
| `chelsea.jpg`   | `data.chelsea()`   | Photo of a cat — a face/eye structure for cascade and feature detection. |
| `checkerboard.png` | `data.checkerboard()` | Synthetic checkerboard — used for **camera calibration** in real robotics pipelines. |
| `brick.jpg`     | `data.brick()`     | Repetitive texture — perfect for edge/feature detection and Fourier analysis. |

All of these are public-domain or BSD-licensed test images that ship with `scikit-image`.
"""

# scikit-image is pre-installed on Colab and ships with sample images on disk —
# no network calls needed. We convert each one to BGR uint8 (OpenCV's format)
# and write to a local 'images/' folder so the rest of the notebook can use cv2.imread.
# import skimage
# from skimage import data as skdata

os.makedirs('images', exist_ok=True)
print(f"scikit-image version: {skimage.__version__}\n")

# Each entry: (output filename, skimage loader function, short description)
samples = [
    ("astronaut.jpg",    skdata.astronaut,    "Color portrait (standard CV test image)"),
    ("coffee.jpg",       skdata.coffee,       "Color photo with circular objects"),
    ("coins.jpg",        skdata.coins,        "Grayscale coins (segmentation classic)"),
    ("chelsea.jpg",      skdata.chelsea,      "Cat photo (face/feature detection)"),
    ("checkerboard.png", skdata.checkerboard, "Synthetic calibration target"),
    ("brick.jpg",        skdata.brick,        "Repetitive brick texture"),
]

for filename, loader, description in samples:
    path = os.path.join('images', filename)
    arr = loader()  # numpy array, RGB if color, grayscale otherwise

    # skimage returns RGB uint8 for color images. Some (like coins/checkerboard/brick)
    # are 2D grayscale. cv2.imwrite expects BGR for color, and grayscale 2D arrays
    # are written as 1-channel automatically.
    if arr.ndim == 3:
        # Convert RGB -> BGR for OpenCV-on-disk compatibility
        arr_bgr = cv2.cvtColor(arr, cv2.COLOR_RGB2BGR)
        cv2.imwrite(path, arr_bgr)
    else:
        cv2.imwrite(path, arr)

    print(f"✓ Saved {filename:18s} shape={str(arr.shape):16s} dtype={arr.dtype}  ({description})")

print("\nFiles in 'images/' folder:")
for f in sorted(os.listdir('images')):
    full = os.path.join('images', f)
    print(f"  {f:20s} {os.path.getsize(full):>8,} bytes")

"""---
# 3. 📷 Image Basics: Load, Inspect, Display, Save

In OpenCV, an image is just a **NumPy array**:
- **Grayscale** images are 2D arrays with shape `(height, width)`
- **Color** images are 3D arrays with shape `(height, width, 3)` — the 3 channels are stored in **BGR** order
- The `dtype` is usually `uint8` (values from 0 to 255)

## 3.1 Loading an image with `cv2.imread`

`cv2.imread(path, flag)` reads an image from disk. The `flag` controls how it is loaded:

| Flag | Value | Meaning |
|------|-------|---------|
| `cv2.IMREAD_COLOR`     |  1 | Load as BGR color (default), drops alpha channel |
| `cv2.IMREAD_GRAYSCALE` |  0 | Load as single-channel grayscale |
| `cv2.IMREAD_UNCHANGED` | -1 | Load as-is, including alpha channel if present |

> ⚠️ If the path is wrong, `imread` does **not raise an error** — it returns `None`. Always check!
"""

img_path = 'images/astronaut.jpg'

# Load the image in color (default behavior)
img = cv2.imread(img_path, cv2.IMREAD_COLOR)

# Always validate the load — imread silently returns None on failure
if img is None:
    raise FileNotFoundError(
        f"Could not read {img_path}. "
        f"Check the path or upload the image manually."
    )

# Inspect the array's metadata
print(f"File path        : {img_path}")
print(f"Type             : {type(img).__name__}")
print(f"Shape            : {img.shape}    (height, width, channels)")
print(f"Data type (dtype): {img.dtype}")
print(f"Total pixels     : {img.size:,} (= H * W * C)")
print(f"Min pixel value  : {img.min()}")
print(f"Max pixel value  : {img.max()}")
print(f"Mean pixel value : {img.mean():.2f}")

# Pull out width / height / channels explicitly for clarity
height, width, channels = img.shape
print(f"\nWidth  = {width} px")
print(f"Height = {height} px")
print(f"Channels = {channels} (B, G, R)")

"""## 3.2 Displaying the image

In a regular Python script you'd use `cv2.imshow()` — but **that doesn't work in Colab** because Colab runs on a remote server with no GUI. Instead we display images inline using matplotlib (via our `show()` helper, which converts BGR → RGB automatically).

"""

# Display the color image (helper handles BGR -> RGB conversion)
show(img, title=f"Astronaut - {img.shape[1]}x{img.shape[0]} BGR")

"""### Why do colors look weird without conversion?

Let's prove that OpenCV is BGR by displaying the raw array with matplotlib **without** converting. Matplotlib will assume RGB, swap the red and blue channels, and the image will look strange — Astronaut's skin will appear blue.

"""

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Wrong: feeding BGR straight to matplotlib (which expects RGB)
axes[0].imshow(img)
axes[0].set_title("BGR shown as RGB (WRONG colors)")
axes[0].axis('off')

# Right: convert BGR -> RGB first
axes[1].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
axes[1].set_title("After cv2.COLOR_BGR2RGB (correct)")
axes[1].axis('off')

plt.tight_layout()
plt.show()

print("Conclusion: cv2.imread returns BGR. Always convert before showing with matplotlib.")

"""## 3.3 Loading as grayscale

Loading directly as grayscale is more efficient than loading in color and converting — OpenCV reads only one channel.

"""

gray = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

print(f"Grayscale shape  : {gray.shape}    (height, width) — only 2 dimensions!")
print(f"Grayscale dtype  : {gray.dtype}")
print(f"Min / Max / Mean : {gray.min()} / {gray.max()} / {gray.mean():.2f}")
print(f"Memory size      : {gray.nbytes:,} bytes "
      f"(vs {img.nbytes:,} bytes for color — {img.nbytes / gray.nbytes:.1f}x smaller)")

show(gray, title="Astronaut (Grayscale)")

"""## 3.4 Accessing and modifying pixels

Since the image is a NumPy array, you can index into it with `[y, x]` (row, column).

> ⚠️ Note the order: **`[y, x]` = `[row, column]`**, NOT `[x, y]`. This trips up many people.

"""

# Read the pixel at (y=100, x=100)
b, g, r = img[100, 100]
print(f"Pixel at (y=100, x=100) -> B={b}, G={g}, R={r}")

# You can also read just one channel
blue_value = img[100, 100, 0]   # 0=B, 1=G, 2=R
print(f"Blue channel only       : {blue_value}")

# Modify a pixel (note: this is in-place, so we work on a copy)
img_copy = img.copy()
img_copy[100, 100] = [255, 255, 255]  # white pixel
print(f"After modification      : {img_copy[100, 100]}")

# Bulk modify a region using slicing — paint a 50x50 white square at the top left
img_copy[0:50, 0:50] = [255, 255, 255]
show(img_copy, title="With a 50x50 white square in the top-left")

"""## 3.5 Saving an image with `cv2.imwrite`

`cv2.imwrite(path, image)` writes an image to disk. The format is inferred from the file extension (.jpg, .png, .bmp, .tiff, etc.). It returns `True` on success and `False` on failure.

"""

output_path = 'images/astronaut_gray.png'
success = cv2.imwrite(output_path, gray)

print(f"imwrite returned: {success}")
print(f"File exists     : {os.path.exists(output_path)}")
print(f"File size       : {os.path.getsize(output_path):,} bytes")

# Saving with quality control (JPEG)
jpg_path = 'images/astronaut_gray_q50.jpg'
cv2.imwrite(jpg_path, gray, [cv2.IMWRITE_JPEG_QUALITY, 50])  # 50% quality
print(f"\nLow-quality JPEG saved at {jpg_path}: "
      f"{os.path.getsize(jpg_path):,} bytes "
      f"(compare to PNG: {os.path.getsize(output_path):,} bytes)")

"""---
# 4. 🎨 Color Spaces

A **color space** is a way of representing colors numerically. The most common ones are:

| Space | Channels | Notes |
|-------|----------|-------|
| **BGR** | Blue, Green, Red | OpenCV's default |
| **RGB** | Red, Green, Blue | Standard for display, matplotlib, web |
| **Gray** | Single intensity channel | Used for many algorithms (faster, simpler) |
| **HSV** | Hue, Saturation, Value | Great for **color-based filtering** because hue is decoupled from brightness |
| **Lab** | Lightness, a*, b* | Perceptually uniform — small numeric distance ≈ small visual difference |

Convert between them with `cv2.cvtColor(img, code)`.

"""

# Convert the original BGR image to several color spaces
img_rgb  = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_hsv  = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
img_lab  = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)

print(f"Original BGR : shape={img.shape},     dtype={img.dtype}")
print(f"RGB          : shape={img_rgb.shape},  dtype={img_rgb.dtype}")
print(f"Grayscale    : shape={img_gray.shape},          dtype={img_gray.dtype}")
print(f"HSV          : shape={img_hsv.shape},  dtype={img_hsv.dtype}")
print(f"Lab          : shape={img_lab.shape},  dtype={img_lab.dtype}")

# A single pixel across the color spaces
print("\nPixel (200, 200) values across color spaces:")
print(f"  BGR  -> {img[200, 200]}")
print(f"  RGB  -> {img_rgb[200, 200]}")
print(f"  HSV  -> {img_hsv[200, 200]}  (H: 0-179, S: 0-255, V: 0-255 in OpenCV)")
print(f"  Lab  -> {img_lab[200, 200]}")

# Visualize the same image in different color spaces
# Note: HSV and Lab look weird when shown directly as RGB — that's expected,
# we just want to see what the channel data looks like.
show_grid(
    [img, img_gray, img_hsv, img_lab],
    ["BGR (original)", "Grayscale", "HSV (raw channels as RGB)", "Lab (raw channels as RGB)"],
    cols=2, figsize=(11, 9)
)

"""## 4.1 Splitting and merging channels

You can split a multi-channel image into its individual channels with `cv2.split()` and recombine them with `cv2.merge()`. This is also doable (and faster) with NumPy slicing: `img[:, :, 0]`.

"""

import numpy as np
import cv2

# Split the original 3-channel image into its individual Blue, Green, and Red single channels
b, g, r = cv2.split(img)

# Print out the shape, data type, and mean pixel intensity for each isolated channel
print(f"B channel: shape={b.shape}, dtype={b.dtype}, mean={b.mean():.1f}")
print(f"G channel: shape={g.shape}, dtype={g.dtype}, mean={g.mean():.1f}")
print(f"R channel: shape={r.shape}, dtype={r.dtype}, mean={r.mean():.1f}")

# Create a 2D array of zeros with the exact same dimensions and data type as the individual channels.
# This will be used as a "blank" or "empty" channel to mask out unwanted colors.
zeros = np.zeros_like(b)

# Reconstruct 3-channel images to visualize each channel in its true color rather than grayscale.
# Note: OpenCV strictly uses the BGR (Blue, Green, Red) channel order.
# To isolate a color, we place the original channel data in its respective position
# and fill the other two color positions with the 'zeros' array.
b_color = cv2.merge([b, zeros, zeros])  # Format: [Blue data, No Green, No Red]
g_color = cv2.merge([zeros, g, zeros])  # Format: [No Blue, Green data, No Red]
r_color = cv2.merge([zeros, zeros, r])  # Format: [No Blue, No Green, Red data]

# Visualize the color-isolated images side-by-side using the custom plotting function
show_grid([b_color, g_color, r_color], ["Blue channel", "Green channel", "Red channel"], cols=3, figsize=(13, 4))

# Merge the original isolated channels back together into a standard 3-channel image
# This is to verify that the split and merge operations perfectly preserve the original image data (round-trip test)
merged = cv2.merge([b, g, r])
print(f"\nMerged back: shape={merged.shape}, identical to original? {np.array_equal(img, merged)}")

"""## 4.2 Color filtering with HSV — isolating a color

HSV is excellent for picking out a specific color, because the **Hue** channel encodes "what color it is" independent of brightness or saturation. This is much more robust than thresholding in BGR — a key technique in robotics for tasks like **detecting colored markers, traffic cones, or fiducials** under variable lighting.

We'll demonstrate by isolating the **brown/red coffee** in the `coffee.jpg` image.
"""

coffee = cv2.imread('images/coffee.jpg', cv2.IMREAD_COLOR)
if coffee is None:
    print("⚠ OpenCV coffee not available — skipping this cell.")
else:
    print(f"coffee shape: {coffee.shape}, dtype: {coffee.dtype}")

    # Convert to HSV
    coffee_hsv = cv2.cvtColor(coffee, cv2.COLOR_BGR2HSV)

    # In OpenCV's HSV: H in [0, 179], S/V in [0, 255]
    # Red wraps around the hue circle, so we need TWO ranges:
    #   ~0-10 (low end)  and  ~170-179 (high end)
    lower_red1 = np.array([  0, 100, 100])
    upper_red1 = np.array([ 10, 255, 255])
    lower_red2 = np.array([170, 100, 100])
    upper_red2 = np.array([179, 255, 255])

    mask1 = cv2.inRange(coffee_hsv, lower_red1, upper_red1)
    mask2 = cv2.inRange(coffee_hsv, lower_red2, upper_red2)
    red_mask = mask1 | mask2  # combine both ranges

    # Apply the mask to the original
    red_only = cv2.bitwise_and(coffee, coffee, mask=red_mask)

    print(f"Mask shape : {red_mask.shape}, dtype: {red_mask.dtype}")
    print(f"Mask values: unique = {np.unique(red_mask)} (255 = keep, 0 = discard)")
    print(f"Red pixels found: {(red_mask > 0).sum():,} of {red_mask.size:,} "
          f"({(red_mask > 0).mean() * 100:.1f}%)")

    show_grid(
        [coffee, red_mask, red_only],
        ["Original coffee", "Red mask", "Red pixels only"],
        cols=3, figsize=(13, 4)
    )

"""---
# 5. ✏️ Drawing on Images

OpenCV provides functions to draw shapes and text. They modify the image **in place** and return the modified image.

| Function | Draws |
|----------|-------|
| `cv2.line(img, pt1, pt2, color, thickness)` | Line |
| `cv2.rectangle(img, pt1, pt2, color, thickness)` | Rectangle |
| `cv2.circle(img, center, radius, color, thickness)` | Circle |
| `cv2.ellipse(img, center, axes, angle, start, end, color, thickness)` | Ellipse |
| `cv2.polylines(img, [pts], isClosed, color, thickness)` | Polygon outline |
| `cv2.fillPoly(img, [pts], color)` | Filled polygon |
| `cv2.putText(img, text, org, font, scale, color, thickness)` | Text |

> Use `thickness=-1` (or `cv2.FILLED`) to fill a shape instead of just outlining it. Colors are `(B, G, R)` tuples.

"""

# Start with a black canvas
canvas = np.zeros((400, 600, 3), dtype=np.uint8)
print(f"Canvas shape: {canvas.shape}, dtype: {canvas.dtype}")
print(f"Initial pixel sum: {canvas.sum()} (all zeros = pure black)")

# Line: from (50, 50) to (550, 50), green, thickness 3
cv2.line(canvas, (50, 50), (550, 50), color=(0, 255, 0), thickness=3)

# Rectangle outline
cv2.rectangle(canvas, (50, 80), (250, 200), color=(255, 0, 0), thickness=2)

# Filled rectangle
cv2.rectangle(canvas, (300, 80), (500, 200), color=(0, 0, 255), thickness=-1)

# Circle outline
cv2.circle(canvas, (150, 290), 50, color=(0, 255, 255), thickness=3)

# Filled circle
cv2.circle(canvas, (300, 290), 50, color=(255, 255, 0), thickness=-1)

# Ellipse: center=(450,290), axes=(80,40), angle=0, full sweep 0->360
cv2.ellipse(canvas, (450, 290), (80, 40), 0, 0, 360, (255, 0, 255), 2)

# Polygon: needs an int32 array of shape (N, 1, 2)
pts = np.array([[50, 380], [120, 340], [180, 380], [120, 360]], np.int32).reshape(-1, 1, 2)
cv2.polylines(canvas, [pts], isClosed=True, color=(255, 255, 255), thickness=2)

# Text
cv2.putText(canvas, "OpenCV Drawing Demo", (130, 380),
            cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2, cv2.LINE_AA)

print(f"After drawing — pixel sum: {canvas.sum():,} (no longer zero!)")
print(f"Unique colors used (sample): {np.unique(canvas.reshape(-1, 3), axis=0).shape[0]} distinct (B,G,R) tuples")

show(canvas, title="Drawing primitives on a black canvas", figsize=(10, 7))

"""---
# 6. 🔄 Image Transformations

Geometric transformations change the **spatial layout** of an image. We'll cover:

- **Resize** — change dimensions
- **Crop** — extract a sub-region (just NumPy slicing)
- **Flip** — mirror horizontally/vertically
- **Rotate** — by 90° (fast) or arbitrary angle (`getRotationMatrix2D` + `warpAffine`)
- **Translate** — shift the image
- **Affine warp** — preserves parallel lines (rotation, scale, shear, translation)
- **Perspective warp** — corrects for viewpoint distortion (4-point transform)

## 6.1 Resize

`cv2.resize(img, dsize, fx, fy, interpolation)`

| Interpolation flag | Use case |
|--------------------|----------|
| `cv2.INTER_NEAREST`  | Fastest, blocky — labels/masks |
| `cv2.INTER_LINEAR`   | Default — good for upscaling |
| `cv2.INTER_CUBIC`    | Slower but better — upscaling |
| `cv2.INTER_AREA`     | Best for **downscaling** |
"""

print(f"Original size: {img.shape[1]}x{img.shape[0]}")

# Method 1: explicit target size (width, height)
resized_small = cv2.resize(img, (200, 100), interpolation=cv2.INTER_AREA)
print(f"Forced 200x100: {resized_small.shape[1]}x{resized_small.shape[0]} "
      f"(aspect ratio NOT preserved)")

# Method 2: scale factor (fx, fy) — preserves aspect ratio if equal
resized_half = cv2.resize(img, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_AREA)
print(f"Half scale  : {resized_half.shape[1]}x{resized_half.shape[0]}")

# Method 3: keep aspect ratio when targeting a specific width
target_w = 300
ratio = target_w / img.shape[1]
target_h = int(img.shape[0] * ratio)
resized_aspect = cv2.resize(img, (target_w, target_h), interpolation=cv2.INTER_AREA)
print(f"Aspect-preserved width=300: {resized_aspect.shape[1]}x{resized_aspect.shape[0]}")

show_grid(
    [img, resized_small, resized_half, resized_aspect],
    [f"Original {img.shape[1]}x{img.shape[0]}",
     f"Forced 200x100",
     f"50% scale ({resized_half.shape[1]}x{resized_half.shape[0]})",
     f"W=300, aspect kept ({resized_aspect.shape[1]}x{resized_aspect.shape[0]})"],
    cols=2, figsize=(11, 9)
)

print(f"Original size: {img.shape[1]}x{img.shape[0]}")

# Method 1: explicit target size (width, height)
resized_small = cv2.resize(img, (200, 200), interpolation=cv2.INTER_AREA)
print(f"Forced 200x200: {resized_small.shape[1]}x{resized_small.shape[0]} "
      f"(aspect ratio NOT preserved)")

# Method 2: scale factor (fx, fy) — preserves aspect ratio if equal
resized_half = cv2.resize(img, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_AREA)
print(f"Half scale  : {resized_half.shape[1]}x{resized_half.shape[0]}")

# Method 3: keep aspect ratio when targeting a specific width
target_w = 300
ratio = target_w / img.shape[1]
target_h = int(img.shape[0] * ratio)
resized_aspect = cv2.resize(img, (target_w, target_h), interpolation=cv2.INTER_AREA)
print(f"Aspect-preserved width=300: {resized_aspect.shape[1]}x{resized_aspect.shape[0]}")

show_grid(
    [img, resized_small, resized_half, resized_aspect],
    [f"Original {img.shape[1]}x{img.shape[0]}",
     f"Forced 200x200",
     f"50% scale ({resized_half.shape[1]}x{resized_half.shape[0]})",
     f"W=300, aspect kept ({resized_aspect.shape[1]}x{resized_aspect.shape[0]})"],
    cols=2, figsize=(11, 9)
)

"""## 6.2 Crop

Cropping is just NumPy slicing: `img[y1:y2, x1:x2]`. There is no special `cv2.crop`.

"""

# Crop a 200x200 region near the face (Astronaut's face is roughly center-right)
y1, y2 = 80, 280
x1, x2 = 180, 380
cropped = img[y1:y2, x1:x2]

print(f"Cropped slice img[{y1}:{y2}, {x1}:{x2}] -> shape {cropped.shape}")
show(cropped, title=f"Cropped region ({cropped.shape[1]}x{cropped.shape[0]})", figsize=(5, 5))

"""## 6.3 Flip

`cv2.flip(img, flipCode)`:
- `flipCode = 0` → flip vertically (around x-axis)
- `flipCode > 0` → flip horizontally (around y-axis) — like a mirror
- `flipCode < 0` → flip both

"""

flip_h    = cv2.flip(img, 1)
flip_v    = cv2.flip(img, 0)
flip_both = cv2.flip(img, -1)

show_grid(
    [img, flip_h, flip_v, flip_both],
    ["Original", "Horizontal flip (1)", "Vertical flip (0)", "Both flips (-1)"],
    cols=2, figsize=(11, 9)
)

"""## 6.4 Rotation

For **90° multiples**, use `cv2.rotate` — it's fast and never crops the image.

For **arbitrary angles**, build a 2×3 rotation matrix with `cv2.getRotationMatrix2D` and apply it with `cv2.warpAffine`.

"""

# Fast 90° rotations
rot_90  = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
rot_180 = cv2.rotate(img, cv2.ROTATE_180)
rot_270 = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)

# Arbitrary angle: 45 degrees around the image center
h, w = img.shape[:2]
center = (w // 2, h // 2)
angle = 45
scale = 1.0
M = cv2.getRotationMatrix2D(center, angle, scale)

print(f"Rotation matrix (2x3) for {angle}°:")
print(M)

# warpAffine signature: warpAffine(src, M, dsize) -- dsize is (width, height)
rot_45 = cv2.warpAffine(img, M, (w, h))

show_grid(
    [img, rot_90, rot_180, rot_45],
    ["Original", "90° CW (rotate)", "180° (rotate)", "45° (warpAffine)"],
    cols=2, figsize=(11, 9)
)

"""## 6.5 Translation (shifting)

A translation matrix has the form:

```
M = [[1, 0, tx],
     [0, 1, ty]]
```

where `tx` is the horizontal shift and `ty` is the vertical shift (positive = down).

"""

tx, ty = 80, 50
M_translate = np.float32([[1, 0, tx],
                          [0, 1, ty]])
print(f"Translation matrix (shift by tx={tx}, ty={ty}):")
print(M_translate)

translated = cv2.warpAffine(img, M_translate, (w, h))
show(translated, title=f"Translated by ({tx}, {ty}) — empty area filled with black")

"""## 6.6 Affine warp (3-point mapping)

An **affine transform** maps any 3 input points to any 3 output points. It can express any combination of translation, rotation, scale, and shear, but **parallel lines stay parallel**.

"""

# Pick 3 source points and 3 destination points
src_pts = np.float32([[ 50,  50], [200,  50], [ 50, 200]])
dst_pts = np.float32([[ 10, 100], [200,  50], [100, 250]])

M_affine = cv2.getAffineTransform(src_pts, dst_pts)
print(f"Affine matrix (2x3):")
print(M_affine)

affine_warp = cv2.warpAffine(img, M_affine, (w, h))
show_grid([img, affine_warp], ["Original", "Affine warped"], cols=2, figsize=(11, 5))

"""## 6.7 Perspective warp (4-point mapping)

A **perspective transform** maps any 4 points to any 4 points. It can simulate a viewpoint change — e.g., "deskewing" a photo of a document taken at an angle.

"""

# Map 4 source points to 4 destination points
src4 = np.float32([[ 56,  65], [368,  52], [ 28, 387], [389, 390]])
dst4 = np.float32([[  0,   0], [300,   0], [  0, 300], [300, 300]])

M_persp = cv2.getPerspectiveTransform(src4, dst4)
print(f"Perspective matrix (3x3):")
print(M_persp)

# warpPerspective takes the same shape as warpAffine but uses a 3x3 matrix
persp_warp = cv2.warpPerspective(img, M_persp, (300, 300))
print(f"Output shape: {persp_warp.shape}")

show_grid([img, persp_warp], ["Original (with skew)", "Perspective corrected (300x300)"],
          cols=2, figsize=(11, 5))

"""---
# 7. ➕ Arithmetic and Bitwise Operations

We can add, subtract, blend, and combine images. Two important things:

1. `cv2.add(a, b)` performs **saturated** addition: `200 + 100 → 255` (clipped, not wrapped).
   - In contrast, NumPy's `a + b` wraps: `200 + 100 → 44` (modulo 256).
2. `cv2.addWeighted(a, α, b, β, γ)` computes `α·a + β·b + γ` — perfect for blending.

"""

x = np.uint8([200])
y = np.uint8([100])

print(f"OpenCV cv2.add(200, 100) = {cv2.add(x, y)}   (saturated at 255)")
print(f"NumPy   200 + 100         = {x + y}    (wraps around to 44)")

# Blend two images with addWeighted
img2 = cv2.imread('images/coffee.jpg', cv2.IMREAD_COLOR)
if img2 is not None:
    # Both images need the same size for blending
    img2_resized = cv2.resize(img2, (img.shape[1], img.shape[0]))
    blended = cv2.addWeighted(img, 0.6, img2_resized, 0.4, 0)
    print(f"\nBlended shape: {blended.shape}, dtype: {blended.dtype}")
    show_grid([img, img2_resized, blended],
              ["Astronaut", "Coffee (resized)", "0.6·Astronaut + 0.4·Coffee"],
              cols=3, figsize=(13, 4))
else:
    print("Skipping blend demo — second image not available.")

"""## 7.1 Bitwise operations and masking

Bitwise operations work pixel-by-pixel and are typically used with **binary masks** (0 or 255). The classic use case: **paste a coffee onto a photo without a black background**.

"""

# Build a simple star-shaped binary mask the same size as our image
mask = np.zeros(img.shape[:2], dtype=np.uint8)
cv2.circle(mask, (w // 2, h // 2), 120, 255, -1)  # white filled circle

# Bitwise AND keeps pixels where the mask is white, sets others to black
masked = cv2.bitwise_and(img, img, mask=mask)
print(f"Mask: shape={mask.shape}, dtype={mask.dtype}, unique={np.unique(mask)}")
print(f"Masked image: shape={masked.shape}, dtype={masked.dtype}")

show_grid([img, mask, masked],
          ["Original", "Circular mask", "bitwise_and(img, img, mask)"],
          cols=3, figsize=(13, 4))

"""---
# 8. 🎯 Thresholding

Thresholding turns a grayscale image into a **binary** image — every pixel becomes either 0 or 255 (or `maxval`) based on whether it's above or below a threshold value. It's the simplest way to do segmentation.

Three flavors:
1. **Simple** — one global threshold, you pick the value
2. **Otsu** — automatically picks the threshold by analyzing the histogram
3. **Adaptive** — threshold computed locally per region (great for uneven lighting)

"""

# Use the grayscale Astronaut image
print(f"Input grayscale: shape={gray.shape}, dtype={gray.dtype}, "
      f"range=[{gray.min()}, {gray.max()}]")

# Simple threshold: any pixel above 127 -> 255, else -> 0
ret_simple, th_simple = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
print(f"\nSimple threshold (127): ret={ret_simple}")

# Otsu's method: threshold value chosen automatically
ret_otsu, th_otsu = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
print(f"Otsu's threshold       : ret={ret_otsu} (chosen automatically)")

# Adaptive thresholds — threshold varies per pixel based on a local neighborhood
th_adapt_mean = cv2.adaptiveThreshold(gray, 255,
                                       cv2.ADAPTIVE_THRESH_MEAN_C,
                                       cv2.THRESH_BINARY,
                                       blockSize=11, C=2)
th_adapt_gauss = cv2.adaptiveThreshold(gray, 255,
                                        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                        cv2.THRESH_BINARY,
                                        blockSize=11, C=2)

show_grid(
    [gray, th_simple, th_otsu, th_adapt_mean, th_adapt_gauss],
    ["Grayscale",
     f"Simple T=127",
     f"Otsu T={ret_otsu:.0f}",
     "Adaptive (Mean)",
     "Adaptive (Gaussian)"],
    cols=3, figsize=(13, 8)
)

"""---
# 9. 🌫️ Smoothing (Blurring)

Smoothing reduces noise and small details. Common filters:

| Filter | When to use |
|--------|-------------|
| **Average** (`cv2.blur`) | Simple, fast — kernel is uniform |
| **Gaussian** (`cv2.GaussianBlur`) | Most common — smooth, preserves edges better than average |
| **Median** (`cv2.medianBlur`) | Best at removing **salt-and-pepper noise** — keeps edges sharp |
| **Bilateral** (`cv2.bilateralFilter`) | Edge-preserving smoothing — slow but powerful |

"""

# Add some salt-and-pepper noise so we can see the filters working
noisy = img.copy()
n = 5000
ys = np.random.randint(0, h, n)
xs = np.random.randint(0, w, n)
noisy[ys[:n//2], xs[:n//2]] = 0      # pepper
noisy[ys[n//2:], xs[n//2:]] = 255    # salt
print(f"Added {n} salt+pepper noise pixels")

# Apply the four classic filters
avg_blur  = cv2.blur(noisy, (5, 5))
gauss     = cv2.GaussianBlur(noisy, (5, 5), sigmaX=0)  # sigma=0 -> derived from kernel
median    = cv2.medianBlur(noisy, 5)
bilateral = cv2.bilateralFilter(noisy, d=9, sigmaColor=75, sigmaSpace=75)

print(f"\nAll outputs share shape {avg_blur.shape}, dtype {avg_blur.dtype}")

show_grid(
    [noisy, avg_blur, gauss, median, bilateral],
    ["Noisy", "Average blur", "Gaussian blur", "Median blur", "Bilateral"],
    cols=3, figsize=(13, 8)
)

"""---
# 10. 🔬 Morphological Operations

These operations are applied to **binary images** and use a **structuring element** (kernel) to grow or shrink shapes:

| Operation | Effect |
|-----------|--------|
| **Erosion** | Shrinks white regions — removes small specks |
| **Dilation** | Grows white regions — fills small holes |
| **Opening** | Erosion then dilation — removes noise but preserves shape size |
| **Closing** | Dilation then erosion — closes small holes |
| **Gradient** | Dilation − erosion — gives the outline of objects |

"""

# Build a synthetic binary image with a shape and some noise
binary = np.zeros((300, 300), dtype=np.uint8)
cv2.rectangle(binary, (75, 75), (225, 225), 255, -1)
cv2.circle(binary, (150, 150), 30, 0, -1)  # carve a hole inside

# Add salt noise (white specks outside) and pepper noise (black specks inside)
np.random.seed(0)
noise_pts = np.random.randint(0, 300, (200, 2))
for y, x in noise_pts[:100]:
    binary[y, x] = 255
for y, x in noise_pts[100:]:
    if binary[y, x] == 255:
        binary[y, x] = 0

# Structuring element — a 5x5 square
kernel = np.ones((5, 5), np.uint8)
print(f"Kernel shape: {kernel.shape}")
print(kernel)

erosion  = cv2.erode(binary,  kernel, iterations=1)
dilation = cv2.dilate(binary, kernel, iterations=1)
opening  = cv2.morphologyEx(binary, cv2.MORPH_OPEN,    kernel)
closing  = cv2.morphologyEx(binary, cv2.MORPH_CLOSE,   kernel)
gradient = cv2.morphologyEx(binary, cv2.MORPH_GRADIENT, kernel)

show_grid(
    [binary, erosion, dilation, opening, closing, gradient],
    ["Original (noisy)", "Erosion", "Dilation",
     "Opening (denoise)", "Closing (fill holes)", "Gradient (outline)"],
    cols=3, figsize=(13, 8)
)

"""---
# 11. ⚡ Edge Detection

Edges are places where pixel intensity changes sharply. We'll cover three classic edge detectors:

| Detector | What it does |
|----------|--------------|
| **Sobel** | Computes the gradient in x or y direction (1st derivative) |
| **Laplacian** | Combines x and y second derivatives — single output |
| **Canny** | The gold standard — multi-stage: Gaussian blur → gradients → non-max suppression → hysteresis thresholding |

"""

# Slight blur first — edge detectors are sensitive to noise
blurred = cv2.GaussianBlur(gray, (5, 5), 0)

# Sobel: ddepth=cv2.CV_64F to capture negative gradients, then convert back to uint8
sobel_x = cv2.Sobel(blurred, cv2.CV_64F, dx=1, dy=0, ksize=3)
sobel_y = cv2.Sobel(blurred, cv2.CV_64F, dx=0, dy=1, ksize=3)
sobel_x_abs = cv2.convertScaleAbs(sobel_x)
sobel_y_abs = cv2.convertScaleAbs(sobel_y)
sobel_combined = cv2.addWeighted(sobel_x_abs, 0.5, sobel_y_abs, 0.5, 0)

# Laplacian
laplacian = cv2.Laplacian(blurred, cv2.CV_64F, ksize=3)
laplacian_abs = cv2.convertScaleAbs(laplacian)

# Canny — pass two thresholds (low, high). Lower=more edges, Higher=stricter.
canny_loose  = cv2.Canny(blurred, 50, 150)
canny_strict = cv2.Canny(blurred, 100, 200)

print(f"Sobel-X dtype: {sobel_x.dtype} (CV_64F to keep sign), "
      f"range: [{sobel_x.min():.1f}, {sobel_x.max():.1f}]")
print(f"After convertScaleAbs: dtype={sobel_x_abs.dtype}, "
      f"range=[{sobel_x_abs.min()}, {sobel_x_abs.max()}]")
print(f"Canny output is binary: unique values = {np.unique(canny_loose)}")
print(f"Edge pixel count — loose Canny: {(canny_loose > 0).sum():,}, "
      f"strict Canny: {(canny_strict > 0).sum():,}")

show_grid(
    [gray, sobel_x_abs, sobel_y_abs, sobel_combined, laplacian_abs, canny_loose, canny_strict],
    ["Gray", "Sobel-X", "Sobel-Y", "Sobel combined",
     "Laplacian", "Canny (50,150)", "Canny (100,200)"],
    cols=3, figsize=(13, 11)
)

"""---
# 12. 🔵 Contours

A **contour** is a curve joining all continuous points along a boundary that share the same color/intensity. They're the foundation of shape analysis.

Workflow:
1. Convert to grayscale
2. Threshold (or run edge detection) to get a binary image
3. Call `cv2.findContours(...)`
4. Draw or analyze the contours

`findContours` returns:
- `contours`: a Python list, one element per contour, each a NumPy array of `(x, y)` points
- `hierarchy`: parent/child relationships between contours

"""

# Make a synthetic image with several distinct shapes — clearer than a photo
shapes = np.full((400, 600, 3), 255, dtype=np.uint8)  # white background
cv2.rectangle(shapes, ( 50,  50), (170, 170), (  0,   0,   0), -1)
cv2.circle(shapes,    (300, 110), 60,         (  0,   0,   0), -1)
pts_tri = np.array([[450, 50], [550, 50], [500, 170]], np.int32)
cv2.fillPoly(shapes, [pts_tri], (0, 0, 0))
cv2.rectangle(shapes, ( 50, 230), (170, 350), (  0,   0,   0), -1)
cv2.ellipse(shapes,   (350, 290), (90, 50), 0, 0, 360, (0, 0, 0), -1)

# Convert to grayscale, then threshold (invert so shapes are white = foreground)
shapes_gray = cv2.cvtColor(shapes, cv2.COLOR_BGR2GRAY)
_, shapes_bw = cv2.threshold(shapes_gray, 127, 255, cv2.THRESH_BINARY_INV)

# Find contours
# RETR_EXTERNAL = only the outermost contours
# CHAIN_APPROX_SIMPLE = compress horiz/vert/diag segments to endpoints (saves memory)
contours, hierarchy = cv2.findContours(shapes_bw, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

print(f"Number of contours found: {len(contours)}")
print(f"Hierarchy shape         : {hierarchy.shape if hierarchy is not None else None}")
print(f"\n{'#':<3} {'Points':<8} {'Area':<10} {'Perimeter':<12} {'BBox (x,y,w,h)'}")
print("-" * 60)

for i, c in enumerate(contours):
    area = cv2.contourArea(c)
    peri = cv2.arcLength(c, closed=True)
    x, y, bw_box, bh_box = cv2.boundingRect(c)
    print(f"{i:<3} {len(c):<8} {area:<10.1f} {peri:<12.1f} ({x},{y},{bw_box},{bh_box})")

# Draw all contours, plus the bounding box of each
shapes_with_contours = shapes.copy()
cv2.drawContours(shapes_with_contours, contours, -1, (0, 255, 0), 2)
for c in contours:
    x, y, bw_box, bh_box = cv2.boundingRect(c)
    cv2.rectangle(shapes_with_contours, (x, y), (x + bw_box, y + bh_box), (0, 0, 255), 2)

show_grid(
    [shapes, shapes_bw, shapes_with_contours],
    ["Synthetic shapes", "Binary (inverted)", "Contours (green) + boxes (red)"],
    cols=3, figsize=(14, 5)
)

"""---
# 13. 📊 Histograms

A histogram counts how many pixels fall into each intensity bin. They reveal the **brightness distribution** of an image — useful for diagnosing under/over-exposure, and for **histogram equalization** which boosts contrast.

"""

# Compute the grayscale histogram
hist_gray = cv2.calcHist([gray], channels=[0], mask=None,
                          histSize=[256], ranges=[0, 256])
print(f"Grayscale histogram shape: {hist_gray.shape}, dtype: {hist_gray.dtype}")
print(f"Total pixels in histogram: {int(hist_gray.sum()):,} (should equal {gray.size:,})")
print(f"Brightest bin            : {int(hist_gray.argmax())} "
      f"with {int(hist_gray.max())} pixels")

# Plot the grayscale histogram and the per-channel color histogram
fig, axes = plt.subplots(1, 2, figsize=(13, 4))

axes[0].plot(hist_gray, color='black')
axes[0].set_title("Grayscale Histogram")
axes[0].set_xlabel("Intensity")
axes[0].set_ylabel("# pixels")
axes[0].set_xlim([0, 256])

colors = ('b', 'g', 'r')
for i, col in enumerate(colors):
    h = cv2.calcHist([img], [i], None, [256], [0, 256])
    axes[1].plot(h, color=col, label=f"{col.upper()} channel")
axes[1].set_title("Color (BGR) Histograms")
axes[1].set_xlabel("Intensity")
axes[1].set_xlim([0, 256])
axes[1].legend()

plt.tight_layout()
plt.show()

"""## 13.1 Histogram equalization

If an image's histogram is concentrated in a narrow range, equalization **stretches** it across the full 0–255 range to improve contrast. CLAHE (Contrast Limited Adaptive Histogram Equalization) does this **locally** — usually better results than global equalization.

"""

# Global equalization
equ = cv2.equalizeHist(gray)

# CLAHE — local equalization with contrast limiting to avoid amplifying noise
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
clahe_img = clahe.apply(gray)

print(f"Original gray  : min={gray.min()}, max={gray.max()}, std={gray.std():.1f}")
print(f"Equalized      : min={equ.min()}, max={equ.max()}, std={equ.std():.1f}")
print(f"CLAHE          : min={clahe_img.min()}, max={clahe_img.max()}, std={clahe_img.std():.1f}")

# Side-by-side comparison
fig, axes = plt.subplots(2, 3, figsize=(13, 8))
for ax, im, title in zip(
    axes[0], [gray, equ, clahe_img],
    ["Original", "Global Equalization", "CLAHE"]
):
    ax.imshow(im, cmap='gray', vmin=0, vmax=255)
    ax.set_title(title); ax.axis('off')

for ax, im, title in zip(
    axes[1], [gray, equ, clahe_img],
    ["Original Histogram", "Equalized Histogram", "CLAHE Histogram"]
):
    h = cv2.calcHist([im], [0], None, [256], [0, 256])
    ax.plot(h, color='black')
    ax.set_xlim([0, 256])
    ax.set_title(title)

plt.tight_layout()
plt.show()

"""---
# 14. 📍 Feature Detection

A **feature** is a distinctive image location — typically a corner — that can be re-detected reliably even if the image is rotated, scaled, or slightly distorted. We'll demo:

- **Harris corners** — classic corner detector
- **Shi-Tomasi (`goodFeaturesToTrack`)** — improved Harris, returns top N corners
- **ORB** — fast, free, modern keypoint detector + descriptor (drop-in replacement for SIFT/SURF)

"""

# Harris corner detector
gray_f32 = np.float32(gray)
harris = cv2.cornerHarris(gray_f32, blockSize=2, ksize=3, k=0.04)
# Dilate to make corner markers visible
harris_dilated = cv2.dilate(harris, None)
img_harris = img.copy()
img_harris[harris_dilated > 0.01 * harris_dilated.max()] = [0, 0, 255]  # mark in red
print(f"Harris response: shape={harris.shape}, dtype={harris.dtype}, "
      f"range=[{harris.min():.4f}, {harris.max():.4f}]")
print(f"Harris corners marked: {(harris_dilated > 0.01 * harris_dilated.max()).sum():,} pixels")

# Shi-Tomasi
corners_st = cv2.goodFeaturesToTrack(gray, maxCorners=50, qualityLevel=0.01, minDistance=10)
img_st = img.copy()
print(f"\nShi-Tomasi corners: {len(corners_st)} points")
for c in corners_st:
    x, y = c.ravel().astype(int)
    cv2.circle(img_st, (x, y), 5, (0, 255, 0), 2)

# ORB
orb = cv2.ORB_create(nfeatures=200)
keypoints, descriptors = orb.detectAndCompute(gray, None)
img_orb = cv2.drawKeypoints(img, keypoints, None, color=(0, 255, 0),
                             flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
print(f"\nORB keypoints     : {len(keypoints)}")
if descriptors is not None:
    print(f"ORB descriptors    : shape={descriptors.shape}, dtype={descriptors.dtype} "
          f"({descriptors.shape[1]} bytes per descriptor)")

show_grid(
    [img_harris, img_st, img_orb],
    ["Harris corners (red)", "Shi-Tomasi top-50 (green circles)", "ORB keypoints"],
    cols=3, figsize=(14, 5)
)

"""---
# 15. 😀 Face Detection with Haar Cascades

OpenCV ships with pre-trained **Haar cascade** classifiers for faces, eyes, smiles, etc. They're not as accurate as modern deep-learning detectors, but they're **fast** and **free**, and great for learning.

The cascade XML files are bundled with OpenCV — we find their path with `cv2.data.haarcascades`.

"""

haar_path = cv2.data.haarcascades
print(f"Haar cascades directory: {haar_path}")
print("Available cascades (sample):")
for f in sorted(os.listdir(haar_path))[:8]:
    print(f"  {f}")

face_cascade = cv2.CascadeClassifier(haar_path + 'haarcascade_frontalface_default.xml')
eye_cascade  = cv2.CascadeClassifier(haar_path + 'haarcascade_eye.xml')
print(f"\nFace cascade loaded: {not face_cascade.empty()}")
print(f"Eye cascade loaded : {not eye_cascade.empty()}")

# Detect faces
faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5,
                                       minSize=(30, 30))
print(f"\nFaces detected: {len(faces)}")
for i, (x, y, fw, fh) in enumerate(faces):
    print(f"  Face {i}: x={x}, y={y}, w={fw}, h={fh}")

# Draw boxes for faces, then look for eyes inside each face
img_faces = img.copy()
for (x, y, fw, fh) in faces:
    cv2.rectangle(img_faces, (x, y), (x + fw, y + fh), (0, 255, 0), 2)
    roi_gray = gray[y:y + fh, x:x + fw]
    roi_color = img_faces[y:y + fh, x:x + fw]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    print(f"  -> Eyes in this face: {len(eyes)}")
    for (ex, ey, ew, eh) in eyes:
        cv2.rectangle(roi_color, (ex, ey), (ex + ew, ey + eh), (0, 0, 255), 2)

show(img_faces, title=f"Face detection — {len(faces)} face(s) (green) + eyes (red)")

"""---
# 16. 🎬 Video Basics

OpenCV reads video frame-by-frame with `cv2.VideoCapture`. Live webcam access (`VideoCapture(0)`) **doesn't work in Colab** — Colab runs on a remote server with no camera. But reading a video **file** works fine.

Below we build a synthetic video, then read it back and inspect the metadata.

[colab_webcam.ipynb](https://colab.research.google.com/drive/1QnC7lV7oVFk5OZCm75fqbLAfD9qBy9bw#scrollTo=L6pCmkJrUC9g)
"""

# Build a tiny synthetic video: a moving white circle on black
video_path = 'images/demo.mp4'
fps = 20
size = (320, 240)  # (width, height)

# 'mp4v' is a widely supported codec in Colab's OpenCV build
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
writer = cv2.VideoWriter(video_path, fourcc, fps, size)
print(f"VideoWriter opened: {writer.isOpened()}")

n_frames = 60
for i in range(n_frames):
    frame = np.zeros((size[1], size[0], 3), dtype=np.uint8)
    x_pos = int(20 + (size[0] - 40) * (i / (n_frames - 1)))
    cv2.circle(frame, (x_pos, size[1] // 2), 20, (0, 255, 255), -1)
    cv2.putText(frame, f"Frame {i+1}/{n_frames}", (10, 25),
                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 1)
    writer.write(frame)

writer.release()
print(f"Wrote {n_frames} frames -> {video_path} ({os.path.getsize(video_path):,} bytes)")

# Now read the video back and report its properties
cap = cv2.VideoCapture(video_path)
print(f"VideoCapture opened: {cap.isOpened()}")

n_frames_read = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
fps_read      = cap.get(cv2.CAP_PROP_FPS)
w_read        = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h_read        = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
print(f"Frame count: {n_frames_read}")
print(f"FPS        : {fps_read}")
print(f"Resolution : {w_read}x{h_read}")
print(f"Duration   : {n_frames_read / fps_read:.2f} s")

# Iterate through the frames
frame_idx = 0
sample_frames = []  # we'll keep a few to display
while True:
    ret, frame = cap.read()
    if not ret:
        break
    if frame_idx in (0, n_frames_read // 2, n_frames_read - 1):
        sample_frames.append((frame_idx, frame))
    frame_idx += 1

cap.release()
print(f"\nFinished reading. Total frames consumed: {frame_idx}")
print(f"Sampled frames at indices: {[i for i, _ in sample_frames]}")

show_grid(
    [f for _, f in sample_frames],
    [f"Frame {i}" for i, _ in sample_frames],
    cols=3, figsize=(13, 4)
)

"""---
# 🎉 Wrap Up

You've now seen the most important parts of OpenCV:

- ✅ Loading, displaying, saving, and inspecting images
- ✅ Working in different color spaces (BGR, RGB, Grayscale, HSV, Lab)
- ✅ Drawing primitives and text
- ✅ Geometric transformations (resize, crop, rotate, translate, affine, perspective)
- ✅ Arithmetic, blending, and bitwise operations with masks
- ✅ Thresholding (simple, Otsu, adaptive)
- ✅ Smoothing filters (average, Gaussian, median, bilateral)
- ✅ Morphological operations
- ✅ Edge detection (Sobel, Laplacian, Canny)
- ✅ Contours (finding, drawing, area/perimeter/bounding-box analysis)
- ✅ Histograms and equalization (incl. CLAHE)
- ✅ Feature detection (Harris, Shi-Tomasi, ORB)
- ✅ Face & eye detection with Haar cascades
- ✅ Reading and writing videos in Colab

## Where to go next

- **Object tracking** — `cv2.TrackerCSRT_create`, `cv2.TrackerKCF_create`
- **Optical flow** — `cv2.calcOpticalFlowPyrLK`, `cv2.calcOpticalFlowFarneback`
- **Image stitching / panoramas** — `cv2.Stitcher_create`
- **Deep learning** — `cv2.dnn.readNet` for running ONNX/Caffe/TF models
- **Camera calibration** — `cv2.findChessboardCorners`, `cv2.calibrateCamera`
- **Official docs** — https://docs.opencv.org/

Happy hacking! 🚀

"""