# -*- coding: utf-8 -*-
"""RC_Hw3_Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3MMxVFSkgeWcn4PEeb8MldNzlKsr_Hw

#Import Data From Drive
"""

from google.colab import drive
drive.mount('/content/drive')

import os

folder_path = "/content/drive/MyDrive/Cataract_dataset_classification"

files = os.listdir(folder_path)
print("Files in folder:")
for f in files:
    print(f)

import zipfile
import os

zip_path1 = "/content/drive/MyDrive/Cataract_dataset_classification/Cataract_dataset_classification.v1i.multiclass.zip"
extract_path1 = "/content/cataract_dataset1"


os.makedirs(extract_path1, exist_ok=True)

# Extract
with zipfile.ZipFile(zip_path1, 'r') as zip_ref:
    zip_ref.extractall(extract_path1)

print("✅ Extracted to:", extract_path1)

import os

base_path = "/content/cataract_dataset1"

for split in ["train", "valid", "test"]:
    split_path = os.path.join(base_path, split)
    print(f"\n📂 {split}:")
    if os.path.exists(split_path):
        subfolders = [f for f in os.listdir(split_path) if os.path.isdir(os.path.join(split_path, f))]
        for sub in sorted(subfolders):
            print(" -", sub)
    else:
        print("Dont find anything")

import os
import shutil

base_path = "/content/cataract_dataset1"
output_folder = "/content/collected_csv"


os.makedirs(output_folder, exist_ok=True)

splits = ["train", "valid", "test"]

for split in splits:
    split_path = os.path.join(base_path, split)

    if not os.path.exists(split_path):
        print(f"❌ Dont find:{split_path} ")
        continue


    for file in os.listdir(split_path):
        if file.endswith(".csv"):
            src = os.path.join(split_path, file)
            dst = os.path.join(output_folder, f"{split}_{file}")
            shutil.copy(src, dst)
            print(f"✔ Finding csv: {src} → {dst}")

print("\n🎉 Saving All CSVs on Folder: /content/collected_csv ")

"""#Data Distribution per Class"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


paths = {
    "Train": "/content/collected_csv/train__classes.csv",
    "Valid": "/content/collected_csv/valid__classes.csv",
    "Test": "/content/collected_csv/test__classes.csv"
}

sns.set_style("whitegrid")

for split_name, path in paths.items():


    df = pd.read_csv(path)


    label_df = df.drop(columns=["filename"])


    class_counts = label_df.sum().sort_values(ascending=False)


    plt.figure(figsize=(12, 6))
    ax = sns.barplot(
        x=class_counts.index,
        y=class_counts.values,
        palette="viridis"
    )

    plt.title(f"Class Distribution - {split_name}", fontsize=16)
    plt.xlabel("Classes", fontsize=12)
    plt.ylabel("Number of Images", fontsize=12)
    plt.xticks(rotation=45, ha="right")


    for i, value in enumerate(class_counts.values):
        ax.text(
            i,
            value + 5,
            str(int(value)),
            ha='center',
            va='bottom',
            fontsize=10,
            fontweight='bold'
        )

    plt.tight_layout()
    plt.show()

"""#Data Preprocessing"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from PIL import Image
import pandas as pd
import os


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"🎯 Using device: {device}")

class CataractDataset(Dataset):
    def __init__(self, csv_file, img_dir, transform=None):
        self.df = pd.read_csv(csv_file)
        self.img_dir = img_dir
        self.transform = transform

        self.classes = [c for c in self.df.columns if c != 'filename']

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        img_name = os.path.join(self.img_dir, self.df.iloc[idx]['filename'])
        image = Image.open(img_name).convert('RGB')


        labels = torch.tensor(self.df.iloc[idx][self.classes].values.astype(float), dtype=torch.float32)

        if self.transform:
            image = self.transform(image)

        return image, labels


transform = transforms.Compose([
    transforms.Resize((300, 300)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])



train_dataset = CataractDataset('/content/collected_csv/train__classes.csv', '/content/cataract_dataset1/train', transform=transform)
val_dataset = CataractDataset('/content/collected_csv/valid__classes.csv', '/content/cataract_dataset1/valid', transform=transform)
test_dataset = CataractDataset('/content/collected_csv/test__classes.csv', '/content/cataract_dataset1/test', transform=transform)

"""#The first Approach"""

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False, num_workers=2)

!pip install optuna

"""#Hyperparameter Optimization Using Optuna Framework"""

import optuna
import gc
def objective(trial):
    gc.collect()
    torch.cuda.empty_cache()

    lr = trial.suggest_float("lr", 1e-5, 1e-3, log=True)
    optimizer_name = trial.suggest_categorical("optimizer", ["AdamW", "SGD"])
    weight_decay = trial.suggest_float("weight_decay", 1e-6, 1e-3)


    model = models.efficientnet_b3(weights=models.EfficientNet_B3_Weights.IMAGENET1K_V1)
    num_ftrs = model.classifier[1].in_features
    model.classifier[1] = nn.Linear(num_ftrs, 12)
    model = model.to(device)


    if optimizer_name == "AdamW":
        optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
    else:
        optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9)

    criterion = nn.BCEWithLogitsLoss()


    model.train()

    for batch_idx, (data, target) in enumerate(train_loader):
        if batch_idx > 30: break
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()


    model.eval()
    val_loss = 0
    val_loader = DataLoader(val_dataset, batch_size=32)
    with torch.no_grad():
        for data, target in val_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            val_loss += criterion(output, target).item()

    return val_loss / len(val_loader)


study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=5)

print("Best hyperParametrs:", study.best_params)

best_params = study.best_params
model = models.efficientnet_b3(weights=models.EfficientNet_B3_Weights.IMAGENET1K_V1)
num_ftrs = model.classifier[1].in_features
model.classifier[1] = nn.Linear(num_ftrs, 12)
model = model.to(device)

if best_params['optimizer'] == "AdamW":
    optimizer = optim.AdamW(model.parameters(), lr=best_params['lr'], weight_decay=best_params['weight_decay'])
else:
    optimizer = optim.SGD(model.parameters(), lr=best_params['lr'], momentum=0.9)

"""#Focal Loss Class"""

import torch.nn.functional as F

class FocalLoss(nn.Module):
    def __init__(self, alpha=1, gamma=2, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):

        probs = torch.sigmoid(inputs)

        bce_loss = F.binary_cross_entropy_with_logits(inputs, targets, reduction='none')
        pt = torch.exp(-bce_loss)
        focal_loss = self.alpha * (1 - pt)**self.gamma * bce_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        else:
            return focal_loss.sum()

"""#Training model"""

drive_save_dir = "/content/drive/MyDrive/EfficientNet_Weights_RC_NOA"
os.makedirs(drive_save_dir, exist_ok=True)


save_path = os.path.join(drive_save_dir, "best_efficientnet_b3.pth")
criterion = FocalLoss(gamma=2)
best_val_loss = float('inf')


history = {
    'train_loss': [], 'val_loss': [],
    'train_acc': [], 'val_acc': []
}

epochs = 10

print("🚀 Start Training:")

for epoch in range(epochs):
    # ---Train---
    model.train()
    running_loss, train_correct = 0.0, 0

    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * inputs.size(0)


        preds = (torch.sigmoid(outputs) > 0.5).float()
        train_correct += (preds == labels).all(dim=1).sum().item()

    epoch_train_loss = running_loss / len(train_dataset)
    epoch_train_acc = train_correct / len(train_dataset)


    model.eval()
    val_running_loss, val_correct = 0.0, 0


    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)

            val_running_loss += loss.item() * inputs.size(0)
            preds = (torch.sigmoid(outputs) > 0.5).float()
            val_correct += (preds == labels).all(dim=1).sum().item()

    epoch_val_loss = val_running_loss / len(val_dataset)
    epoch_val_acc = val_correct / len(val_dataset)


    history['train_loss'].append(epoch_train_loss)
    history['val_loss'].append(epoch_val_loss)
    history['train_acc'].append(epoch_train_acc)
    history['val_acc'].append(epoch_val_acc)

    print(f"Epoch {epoch+1}/{epochs} | Train Loss: {epoch_train_loss:.4f} |Train Acc: {epoch_train_acc:.4f}|Val Loss: {epoch_val_loss:.4f} | Val Acc: {epoch_val_acc:.4f}")


    if epoch_val_loss < best_val_loss:
        best_val_loss = epoch_val_loss
        torch.save({
            'epoch': epoch + 1,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': best_val_loss,
            'history': history
        }, save_path)
        print(f"⭐ Save Best model to Google Drive! (Val Loss: {best_val_loss:.4f})")

"""#Plotting Accuracy and Loss vs. Epochs"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))


plt.subplot(1, 2, 1)
plt.plot(history['train_loss'], label='Train Loss')
plt.plot(history['val_loss'], label='Val Loss')
plt.title('Loss per Epoch')
plt.grid("True")
plt.legend()


plt.subplot(1, 2, 2)
plt.plot(history['train_acc'], label='Train Acc')
plt.plot(history['val_acc'], label='Val Acc')
plt.title('Accuracy per Epoch')
plt.legend()
plt.grid("True")
plt.show()

"""#Evaluation on test set"""

import os
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from torchvision import models
from sklearn.metrics import classification_report, precision_recall_curve, auc
from sklearn.manifold import TSNE


model = models.efficientnet_b3(weights=None)
num_ftrs = model.classifier[1].in_features
model.classifier[1] = nn.Linear(num_ftrs, 12)


save_path = "/content/drive/MyDrive/EfficientNet_Weights_RC_NOA/best_efficientnet_b3.pth"
if os.path.exists(save_path):
    checkpoint = torch.load(save_path, map_location=device)
    model.load_state_dict(checkpoint['model_state_dict'])
    print("✅ Model weights loaded successfully from Google Drive!")
else:
    print(f"❌ Error: Checkpoint not found at {save_path}")

model = model.to(device)
model.eval()


class_names = test_dataset.classes
print(f"📊 Class names detected (12 classes): {class_names}")

all_preds = []
all_labels = []
all_probs = []
all_features = []


features_flatten = None
def hook_fn(module, input, output):
    global features_flatten
    features_flatten = torch.mean(output, dim=[2, 3]).detach().cpu().numpy()

hook_handle = model.features.register_forward_hook(hook_fn)

print("🔍 Evaluating on Test Dataset (12 Classes)...")
with torch.no_grad():
    for inputs, labels in test_loader: # استفاده از test_loader بدون حذف کلاس
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)

        all_features.append(features_flatten)
        probs = torch.sigmoid(outputs)
        preds = (probs > 0.5).float()

        all_probs.append(probs.cpu().numpy())
        all_preds.append(preds.cpu().numpy())
        all_labels.append(labels.cpu().numpy())

hook_handle.remove()

all_probs = np.vstack(all_probs)
all_preds = np.vstack(all_preds)
all_labels = np.vstack(all_labels)
all_features = np.vstack(all_features)


print("\n📊 --- Classification Report (12 Classes) ---")
print(classification_report(all_labels, all_preds, target_names=class_names, zero_division=0))

print("📈 --- PR-AUC Per Class ---")
for i, name in enumerate(class_names):
    precision, recall, _ = precision_recall_curve(all_labels[:, i], all_probs[:, i])
    pr_auc = auc(recall, precision)
    print(f"Class {name} | PR-AUC: {pr_auc:.4f}")

num_classes = len(class_names)
cm_12x12 = np.zeros((num_classes, num_classes), dtype=int)
for i in range(num_classes):
    for j in range(num_classes):
        cm_12x12[i, j] = np.sum((all_labels[:, i] == 1) & (all_preds[:, j] == 1))

plt.figure(figsize=(14, 11))
sns.heatmap(cm_12x12, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title('12x12 Multi-Label Confusion Matrix', fontsize=14, pad=15)
plt.xlabel('Predicted Target', fontsize=12)
plt.ylabel('Actual Target', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import seaborn as sns
import numpy as np

print("\n🔮 Generating 100% Complete t-SNE Plot for all 12 Classes...")

plt.figure(figsize=(13, 9))


palette = sns.color_palette("tab20", n_colors=12)


color_indices = np.zeros(len(all_labels), dtype=int)
for class_idx in range(12):
    color_indices[all_labels[:, class_idx] == 1] = class_idx


scatter = plt.scatter(
    features_2d[:, 0],
    features_2d[:, 1],
    c=[palette[i] for i in color_indices],
    alpha=0.8,
    s=45,
    edgecolors='none'
)


plt.title("t-SNE Visualization of Features (All 12 Classes Included)", fontsize=14, pad=15, fontweight='bold')
plt.xlabel("t-SNE Component 1", fontsize=11)
plt.ylabel("t-SNE Component 2", fontsize=11)
plt.grid(True, linestyle='--', alpha=0.5)


legend_elements = [
    Patch(facecolor=palette[i], edgecolor='none', label=class_names[i])
    for i in range(12)
]


plt.legend(
    handles=legend_elements,
    title="Cataract Classes",
    title_fontsize='12',
    loc='upper left',
    bbox_to_anchor=(1.02, 1),
    borderaxespad=0.,
    fontsize=11,
    frameon=True,
    shadow=True
)

plt.tight_layout()
plt.show()

import cv2

class GradCAM:
    def __init__(self, model, target_layer):
        self.model = model
        self.target_layer = target_layer
        self.gradients = None
        self.activations = None

        self.target_layer.register_forward_hook(self.save_activation)
        self.target_layer.register_full_backward_hook(self.save_gradient)

    def save_activation(self, module, input, output):
        self.activations = output.detach()

    def save_gradient(self, module, grad_input, grad_output):
        self.gradients = grad_output[0].detach()

    def generate_heatmap(self, input_image, class_idx):
        self.model.zero_grad()
        output = self.model(input_image)
        target = output[0, class_idx]
        target.backward()

        weights = torch.mean(self.gradients, dim=[2, 3])[0]
        heatmap = torch.zeros(self.activations.shape[2:], dtype=torch.float32, device=input_image.device)
        for i, w in enumerate(weights):
            heatmap += w * self.activations[0, i, :, :]

        heatmap = torch.clamp(heatmap, min=0)
        heatmap /= torch.max(heatmap) if torch.max(heatmap) != 0 else 1
        return heatmap.cpu().numpy()


target_layer = model.features[-1]
cam = GradCAM(model, target_layer)


plt.figure(figsize=(18, 14))
cols = 4
rows = 3

for class_idx, class_name in enumerate(class_names):
    found_sample = False
    for inputs, labels in test_loader:
        for idx in range(inputs.size(0)):
            if labels[idx][class_idx] == 1:
                img_tensor = inputs[idx].unsqueeze(0).to(device)
                found_sample = True
                break
        if found_sample:
            break

    if not found_sample:
        print(f"⚠️ No sample found containing class: {class_name} in test set.")
        continue


    heatmap = cam.generate_heatmap(img_tensor, class_idx)


    img_show = img_tensor.squeeze(0).cpu().numpy().transpose(1, 2, 0)
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    img_show = std * img_show + mean
    img_show = np.clip(img_show, 0, 1)


    heatmap_resized = cv2.resize(heatmap, (img_show.shape[1], img_show.shape[0]))
    heatmap_colored = cv2.applyColorMap(np.uint8(255 * heatmap_resized), cv2.COLORMAP_JET)
    heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB) / 255.0
    overlapped_img = heatmap_colored * 0.4 + img_show * 0.6


    ax = plt.subplot(rows, cols, class_idx + 1)
    ax.imshow(overlapped_img)
    ax.set_title(f"Grad-CAM: {class_name}", fontsize=11)
    ax.axis('off')

plt.tight_layout()
plt.show()

"""#The Second Approach
Augmentation
"""

import os
import cv2
import albumentations as A
import pandas as pd
import numpy as np
from tqdm.auto import tqdm


augmenter = A.Compose([
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.2),
    A.Rotate(limit=30, p=0.7, border_mode=cv2.BORDER_CONSTANT),
    A.RandomBrightnessContrast(brightness_limit=0.3, contrast_limit=0.3, p=0.7),
    A.HueSaturationValue(hue_shift_limit=10, sat_shift_limit=20, val_shift_limit=10, p=0.5),
    A.Affine(scale=(0.8, 1.2), translate_percent=(0.1, 0.1), rotate=(-15, 15), p=0.5),
    A.Resize(300, 300)
], p=1.0)

def augment_and_remove_majors(input_dir, output_dir, csv_path, output_csv_path):
    if not os.path.exists(csv_path):
        print(f"❌ Error: CSV not found at {csv_path}")
        return


    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip()


    cols_to_remove = ['Cornea', 'Pupil']
    df = df.drop(columns=[col for col in cols_to_remove if col in df.columns])


    tool_classes = [c for c in df.columns if c != 'filename']


    class_counts = df[tool_classes].sum()
    target_count = int(class_counts.max())
    print(f"🎯 New Target Count per class: {target_count} (based on {class_counts.idxmax()})")

    os.makedirs(output_dir, exist_ok=True)
    final_rows = []


    print("Step 1: Copying original images with reduced labels...")
    for idx, row in tqdm(df.iterrows(), total=len(df), desc="Originals"):
        src_path = os.path.join(input_dir, row["filename"])
        if os.path.exists(src_path):
            img = cv2.imread(src_path)
            if img is not None:

                if row[tool_classes].sum() > 0:
                    cv2.imwrite(os.path.join(output_dir, row["filename"]), img)
                    final_rows.append(row.copy())


    print("Step 2: Balancing tools via augmentation...")
    current_df = pd.DataFrame(final_rows)
    current_counts = current_df[tool_classes].sum()

    for cls in tool_classes:
        needed = target_count - int(current_counts[cls])
        if needed <= 0: continue

        print(f"➕ Augmenting {cls}: Need {needed}")
        class_samples = current_df[current_df[cls] == 1]
        if len(class_samples) == 0: continue

        count_added = 0
        while count_added < needed:
            sample = class_samples.sample(n=1).iloc[0]
            src_path = os.path.join(output_dir, sample["filename"])
            image = cv2.imread(src_path)
            if image is None: continue

            augmented = augmenter(image=image)["image"]
            new_filename = f"aug_{cls.replace(' ', '_')}_{count_added}_{sample['filename']}"
            cv2.imwrite(os.path.join(output_dir, new_filename), augmented)

            new_row = sample.copy()
            new_row["filename"] = new_filename
            final_rows.append(new_row)
            count_added += 1


    df_final = pd.DataFrame(final_rows).sample(frac=1).reset_index(drop=True)
    df_final.to_csv(output_csv_path, index=False)

    print(f"\n✅ Done! Dataset is now balanced without Cornea/Pupil.")
    print(f"📊 Total images: {len(df_final)}")
    print(f"📁 Images saved to: {output_dir}")
    print(f"📄 CSV saved to: {output_csv_path}")


augment_and_remove_majors(
    input_dir="/content/cataract_dataset1/train",
    output_dir="/content/train_no_majors_augmented",
    csv_path="/content/collected_csv/train__classes.csv",
    output_csv_path="/content/train_no_majors_final.csv"
)

"""#Data Distribution per Class after Augmentation"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


paths = {"Train": "/content/train_no_majors_final.csv"}

sns.set_style("whitegrid")

for split_name, path in paths.items():


    df = pd.read_csv(path)


    label_df = df.drop(columns=["filename"])


    class_counts = label_df.sum().sort_values(ascending=False)


    plt.figure(figsize=(12, 6))
    ax = sns.barplot(
        x=class_counts.index,
        y=class_counts.values,
        palette="viridis"
    )

    plt.title(f"Class Distribution - {split_name}", fontsize=16)
    plt.xlabel("Classes", fontsize=12)
    plt.ylabel("Number of Images", fontsize=12)
    plt.xticks(rotation=45, ha="right")


    for i, value in enumerate(class_counts.values):
        ax.text(
            i,
            value + 5,
            str(int(value)),
            ha='center',
            va='bottom',
            fontsize=10,
            fontweight='bold'
        )

    plt.tight_layout()
    plt.show()

"""#Removing Cornea and Pupil from Labels"""

import os
import pandas as pd
from tqdm.auto import tqdm

def remove_majors_and_save_csv(csv_path, output_csv_path):
    if not os.path.exists(csv_path):
        print(f"❌ Error: CSV not found at {csv_path}")
        return


    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip()

    print(f"Processing {os.path.basename(csv_path)}...")
    print(f"Original shape: {df.shape}")


    cols_to_remove = ['Cornea', 'Pupil']
    df_filtered = df.drop(columns=[col for col in cols_to_remove if col in df.columns])


    tool_classes = [c for c in df_filtered.columns if c != 'filename']


    df_filtered = df_filtered[df_filtered[tool_classes].sum(axis=1) > 0]


    df_filtered = df_filtered.reset_index(drop=True)


    df_filtered.to_csv(output_csv_path, index=False)

    print(f"✅ Done! Cleaned data saved.")
    print(f"📊 New shape: {df_filtered.shape}")
    print(f"📄 CSV saved to: {output_csv_path}\n" + "-"*50)



remove_majors_and_save_csv(
    csv_path="/content/collected_csv/valid__classes.csv",
    output_csv_path="/content/val_no_majors_final.csv"
)


remove_majors_and_save_csv(
    csv_path="/content/collected_csv/test__classes.csv",
    output_csv_path="/content/test_no_majors_final.csv"
)

train_dataset1 = CataractDataset('/content/train_no_majors_final.csv', '/content/train_no_majors_augmented', transform=transform)
val_dataset1 = CataractDataset('/content/val_no_majors_final.csv', '/content/cataract_dataset1/valid', transform=transform)
test_dataset1 = CataractDataset('/content/test_no_majors_final.csv', '/content/cataract_dataset1/test', transform=transform)

train_loader1 = DataLoader(train_dataset1, batch_size=16, shuffle=True, num_workers=2)
val_loader1 = DataLoader(val_dataset1, batch_size=16, shuffle=False, num_workers=2)
test_loader1 = DataLoader(test_dataset1, batch_size=16, shuffle=False, num_workers=2)

"""#Hyperparameter Optimization Using Optuna Framework"""

import optuna
import gc
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models


num_classes = len(train_dataset1.classes)
print(f"🚀 Dynamic Number of Classes detected: {num_classes}")

def objective(trial):
    gc.collect()
    torch.cuda.empty_cache()


    lr = trial.suggest_float("lr", 1e-5, 1e-3, log=True)
    optimizer_name = trial.suggest_categorical("optimizer", ["AdamW", "SGD"])
    weight_decay = trial.suggest_float("weight_decay", 1e-6, 1e-3)


    model = models.efficientnet_b3(weights=models.EfficientNet_B3_Weights.IMAGENET1K_V1)
    num_ftrs = model.classifier[1].in_features


    model.classifier[1] = nn.Linear(num_ftrs, num_classes)
    model = model.to(device)


    if optimizer_name == "AdamW":
        optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
    else:
        optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9)

    criterion = nn.BCEWithLogitsLoss()


    model.train()
    for batch_idx, (data, target) in enumerate(train_loader1):
        if batch_idx > 30:
            break
        data, target = data.to(device), target.to(device)

        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()


    model.eval()
    val_loss = 0
    with torch.no_grad():
        for data, target in val_loader1:
            data, target = data.to(device), target.to(device)
            output = model(data)
            val_loss += criterion(output, target).item()

    return val_loss / len(val_loader1)


study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=5)

print("\n🎯 Best Hyperparameters found:", study.best_params)

"""#Focal Loss Class"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models
import torch.nn.functional as F


class FocalLoss(nn.Module):
    def __init__(self, alpha=1, gamma=2, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        probs = torch.sigmoid(inputs)
        bce_loss = F.binary_cross_entropy_with_logits(inputs, targets, reduction='none')
        pt = torch.exp(-bce_loss)
        focal_loss = self.alpha * (1 - pt)**self.gamma * bce_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        else:
            return focal_loss.sum()

"""#Training model"""

num_classes = len(train_dataset1.classes)
print(f"📊 Running training with {num_classes} classes.")


model = models.efficientnet_b3(weights=models.EfficientNet_B3_Weights.IMAGENET1K_V1)
num_ftrs = model.classifier[1].in_features


model.classifier[1] = nn.Linear(num_ftrs, num_classes)
model = model.to(device)

optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-5)


drive_save_dir = "/content/drive/MyDrive/EfficientNet_Weights_RC_A"
os.makedirs(drive_save_dir, exist_ok=True)

save_path = os.path.join(drive_save_dir, "best_efficientnet_b3.pth")
criterion = FocalLoss(gamma=2)
best_val_loss = float('inf')

history = {
    'train_loss': [], 'val_loss': [],
    'train_acc': [], 'val_acc': []
}

epochs = 10

print("🚀 Start Training:")

for epoch in range(epochs):
    # ---Train---
    model.train()
    running_loss, train_correct = 0.0, 0

    for inputs, labels in train_loader1:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)


        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * inputs.size(0)

        preds = (torch.sigmoid(outputs) > 0.5).float()
        train_correct += (preds == labels).all(dim=1).sum().item()

    epoch_train_loss = running_loss / len(train_dataset1)
    epoch_train_acc = train_correct / len(train_dataset1)

    # ---Validation---
    model.eval()
    val_running_loss, val_correct = 0.0, 0

    with torch.no_grad():
        for inputs, labels in val_loader1:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)

            val_running_loss += loss.item() * inputs.size(0)
            preds = (torch.sigmoid(outputs) > 0.5).float()
            val_correct += (preds == labels).all(dim=1).sum().item()

    epoch_val_loss = val_running_loss / len(val_dataset1)
    epoch_val_acc = val_correct / len(val_dataset1)

    history['train_loss'].append(epoch_train_loss)
    history['val_loss'].append(epoch_val_loss)
    history['train_acc'].append(epoch_train_acc)
    history['val_acc'].append(epoch_val_acc)

    print(f"Epoch {epoch+1}/{epochs} | Train Loss: {epoch_train_loss:.4f} | Train Acc: {epoch_train_acc:.4f} | Val Loss: {epoch_val_loss:.4f} | Val Acc: {epoch_val_acc:.4f}")

    if epoch_val_loss < best_val_loss:
        best_val_loss = epoch_val_loss
        torch.save({
            'epoch': epoch + 1,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': best_val_loss,
            'history': history
        }, save_path)
        print(f"⭐ Save Best model to Google Drive! (Val Loss: {best_val_loss:.4f})")

"""#Plotting Accuracy and Loss vs. Epochs"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))


plt.subplot(1, 2, 1)
plt.plot(history['train_loss'], label='Train Loss')
plt.plot(history['val_loss'], label='Val Loss')
plt.title('Loss per Epoch')
plt.grid("True")
plt.legend()


plt.subplot(1, 2, 2)
plt.plot(history['train_acc'], label='Train Acc')
plt.plot(history['val_acc'], label='Val Acc')
plt.title('Accuracy per Epoch')
plt.legend()
plt.grid("True")
plt.show()

"""#Evaluation"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, precision_recall_curve, auc, multilabel_confusion_matrix
from sklearn.manifold import TSNE


model.eval()

all_preds = []
all_labels = []
all_features = []


features_flatten = None
def hook_fn(module, input, output):
    global features_flatten

    features_flatten = torch.mean(output, dim=[2, 3]).detach().cpu().numpy()


hook_handle = model.features.register_forward_hook(hook_fn)

print("🔍 Evaluating on Test Dataset and extracting features...")
with torch.no_grad():
    for inputs, labels in test_loader1:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)


        all_features.append(features_flatten)


        probs = torch.sigmoid(outputs)
        preds = (probs > 0.5).float()

        all_preds.append(preds.cpu().numpy())
        all_labels.append(labels.cpu().numpy())


hook_handle.remove()

all_preds = np.vstack(all_preds)
all_labels = np.vstack(all_labels)
all_features = np.vstack(all_features)
class_names = train_dataset1.classes


print("\n📊 --- Classification Report (Per Class) ---")
print(classification_report(all_labels, all_preds, target_names=class_names, zero_division=0))

print("📈 --- PR-AUC Per Class ---")
for i, name in enumerate(class_names):
    precision, recall, _ = precision_recall_curve(all_labels[:, i], all_preds[:, i])
    pr_auc = auc(recall, precision)
    print(f"Class {name} | PR-AUC: {pr_auc:.4f}")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


num_classes = len(class_names)
cm_10x10 = np.zeros((num_classes, num_classes), dtype=int)


for i in range(num_classes):
    for j in range(num_classes):

        cm_10x10[i, j] = np.sum((all_labels[:, i] == 1) & (all_preds[:, j] == 1))


plt.figure(figsize=(12, 10))
sns.heatmap(cm_10x10, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)

plt.title('10x10 Multi-Label Confusion Matrix (Co-occurrence)', fontsize=14, pad=15)
plt.xlabel('Predicted Tools', fontsize=12)
plt.ylabel('Actual Tools', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

print("\n🔮 Running t-SNE (this might take a minute)...")
tsne = TSNE(n_components=2, random_state=42, perplexity=30, n_iter=1000)
features_2d = tsne.fit_transform(all_features)


dominant_labels = np.argmax(all_labels, axis=1)

plt.figure(figsize=(10, 8))
scatter = plt.scatter(features_2d[:, 0], features_2d[:, 1], c=dominant_labels, cmap='tab10', alpha=0.7)
plt.colorbar(scatter, ticks=range(10), format=plt.FuncFormatter(lambda val, loc: class_names[int(val)]))
plt.title("t-SNE Visualization of Extracted Features (Cataract Tools)")
plt.xlabel("t-SNE Component 1")
plt.ylabel("t-SNE Component 2")
plt.show()

import cv2

class GradCAM:
    def __init__(self, model, target_layer):
        self.model = model
        self.target_layer = target_layer
        self.gradients = None
        self.activations = None


        self.target_layer.register_forward_hook(self.save_activation)
        self.target_layer.register_full_backward_hook(self.save_gradient)

    def save_activation(self, module, input, output):
        self.activations = output.detach()

    def save_gradient(self, module, grad_input, grad_output):
        self.gradients = grad_output[0].detach()

    def generate_heatmap(self, input_image, class_idx):
        self.model.zero_grad()
        output = self.model(input_image)


        target = output[0, class_idx]
        target.backward()


        weights = torch.mean(self.gradients, dim=[2, 3])[0]


        heatmap = torch.zeros(self.activations.shape[2:], dtype=torch.float32, device=input_image.device)
        for i, w in enumerate(weights):
            heatmap += w * self.activations[0, i, :, :]


        heatmap = torch.clamp(heatmap, min=0)
        heatmap /= torch.max(heatmap) if torch.max(heatmap) != 0 else 1
        return heatmap.cpu().numpy()


target_layer = model.features[-1]
cam = GradCAM(model, target_layer)


plt.figure(figsize=(20, 10))
cols = 5
rows = 2

for class_idx, class_name in enumerate(class_names):

    found_sample = False
    for inputs, labels in test_loader1:
        for idx in range(inputs.size(0)):
            if labels[idx][class_idx] == 1:
                img_tensor = inputs[idx].unsqueeze(0).to(device)
                found_sample = True
                break
        if found_sample:
            break

    if not found_sample:
        print(f"⚠️ No sample found containing class: {class_name} in test set.")
        continue


    heatmap = cam.generate_heatmap(img_tensor, class_idx)


    img_show = img_tensor.squeeze(0).cpu().numpy().transpose(1, 2, 0)
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    img_show = std * img_show + mean
    img_show = np.clip(img_show, 0, 1)


    heatmap_resized = cv2.resize(heatmap, (img_show.shape[1], img_show.shape[0]))
    heatmap_colored = cv2.applyColorMap(np.uint8(255 * heatmap_resized), cv2.COLORMAP_JET)
    heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB) / 255.0


    overlapped_img = heatmap_colored * 0.4 + img_show * 0.6

   
    ax = plt.subplot(rows, cols, class_idx + 1)
    ax.imshow(overlapped_img)
    ax.set_title(f"Grad-CAM: {class_name}", fontsize=12)
    ax.axis('off')

plt.tight_layout()
plt.show()