# -*- coding: utf-8 -*-
"""OpenCV_Advanced_Tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w0acPyLFihokGN-miSOb9kD4V_u3M6XE

# 👨‍💻 About the Author

Welcome to this comprehensive tutorial! This notebook is curated and maintained by **Mohammad Javad Ahmadi**, a specialist in bridging the gap between cutting-edge AI research and production-grade software.

### **Mohammad Javad Ahmadi**
*CTO at MediversAI | Head of ARAS AI Group | Ph.D. Candidate in Electrical & Control Engineering*

With over 8 years of experience in architecting complex AI pipelines, Mohammad Javad leads technical teams in developing scalable SaaS solutions for **MedTech** and **FinTech**. His expertise includes:

*   **Advanced Computer Vision:** Real-time surgical video understanding, 3D-CNNs, and medical imaging analysis.
*   **Generative AI:** Multi-modal GenAI (LLMs/VLMs) and Autonomous Agentic Systems.
*   **Technical Leadership:** Directing R&D strategies and mentoring 60+ developers and researchers.

He has been recognized as an innovation leader by **Alberta Machine Intelligence Institute (Amii)** and has received prestigious grants for his work on AI-powered surgical assessment systems.

---
*Connect or explore more:*
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Profile-blue?style=flat&logo=linkedin)](https://www.linkedin.com/in/mjahmadi/)
[![GitHub](https://img.shields.io/badge/GitHub-Profile-black?style=flat&logo=github)](https://github.com/MJAHMADEE)
[![Google Scholar](https://img.shields.io/badge/Google%20Scholar-Publications-red?style=flat&logo=google-scholar)](https://scholar.google.com/citations?user=wTnN9IEAAAAJ&hl=en)

# 🚀 Advanced OpenCV Tutorial — Computer Vision & Robotics

This notebook is the **direct sequel** to the introductory OpenCV tutorial. It assumes you are comfortable with:

- Loading / displaying / saving images (BGR vs RGB)
- Color spaces, drawing, basic transforms
- Thresholding, smoothing, morphology, edges, contours
- Histograms, basic features (Harris/ORB), Haar cascades, video I/O

**Here we go deeper, with a focus on real Computer Vision and Robotics applications.**

## 📚 Topics Covered

| # | Topic | Key applications |
|---|-------|------------------|
| 1 | Setup & sample images (skimage, no uploads) | Reproducible environment |
| 2 | Image pyramids & multi-scale processing | Coarse-to-fine search, blending |
| 3 | Hough transforms (lines & circles) | Lane detection, coin counting |
| 4 | Watershed segmentation | Touching-object separation |
| 5 | GrabCut foreground extraction | Interactive segmentation |
| 6 | Distance transforms & skeletonization | Path planning, shape analysis |
| 7 | Template matching | Object localization, defect detection |
| 8 | SIFT, BRISK, AKAZE features | Robust matching across views |
| 9 | Feature matching, RANSAC, homography | **Image stitching, pose estimation** |
| 10 | Image stitching (panoramas) | Drone mapping, mosaicking |
| 11 | Camera calibration | Lens distortion correction (essential for robots) |
| 12 | Pose estimation (PnP) | **AR overlay, robot localization** |
| 13 | Stereo vision & depth maps | **3D reconstruction, obstacle avoidance** |
| 14 | Optical flow (sparse & dense) | Motion tracking, visual odometry |
| 15 | Background subtraction | Surveillance, moving-object detection |
| 16 | Object tracking (modern trackers) | Single & multi-object tracking |
| 17 | Fourier transform & frequency domain | Periodic noise removal |
| 18 | Inpainting & seamless cloning | Image restoration, photo editing |
| 19 | HDR imaging & tone mapping | Exposure fusion |
| 20 | Deep learning with `cv2.dnn` | Run pre-trained models without TensorFlow/PyTorch |
| 21 | Aruco/ArUco markers | **Robot fiducials, AR anchors** |
| 22 | Performance tips & profiling | Real-time pipelines |
| 23 | Useful tricks & gotchas | Practical wisdom |

> 🤖 **Robotics emphasis**: Calibration, PnP, stereo, optical flow, ArUco markers, and tracking are the *bread and butter* of any vision-based robot — perception, localization, and SLAM all depend on them.

> 💾 **No uploads required**: All sample data comes from `scikit-image` (pre-installed on Colab) or is generated programmatically.

---
# 1. 🛠️ Setup

We use the **same environment** as the intro notebook, but install one extra package: `opencv-contrib-python` (it has SIFT, ArUco, advanced trackers, etc., which the base `opencv-python` does **not** include).
"""

# Make sure we have the contrib build — it ships SIFT, ArUco, advanced trackers, etc.
!pip install -q opencv-contrib-python
!pip show opencv-contrib-python

# Commented out IPython magic to ensure Python compatibility.
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import os, sys, time, urllib.request
from skimage import data as skdata
import skimage

# %matplotlib inline
plt.rcParams['figure.figsize'] = (8, 6)
plt.rcParams['figure.dpi']    = 90

print("=" * 60)
print("ENVIRONMENT")
print("=" * 60)
print(f"Python      : {sys.version.split()[0]}")
print(f"OpenCV      : {cv2.__version__}")
print(f"NumPy       : {np.__version__}")
print(f"Matplotlib  : {matplotlib.__version__}")
print(f"scikit-image: {skimage.__version__}")
print("=" * 60)

# Sanity-check: does this OpenCV build include the modules we need?
print("\nFeature/contrib availability:")
print(f"  SIFT       : {hasattr(cv2, 'SIFT_create')}")
print(f"  AKAZE      : {hasattr(cv2, 'AKAZE_create')}")
print(f"  BRISK      : {hasattr(cv2, 'BRISK_create')}")
print(f"  ArUco      : {hasattr(cv2, 'aruco')}")
print(f"  TrackerCSRT: {hasattr(cv2, 'TrackerCSRT_create') or hasattr(cv2, 'legacy')}")
print(f"  DNN module : {hasattr(cv2, 'dnn')}")

"""## 1.1 Helper functions

We reuse the `show()` and `show_grid()` helpers from the intro notebook (verbatim) so visualizations remain consistent.

"""

def show(image, title="Image", cmap=None, figsize=(8, 6)):
    """Display an OpenCV image inline (handles BGR -> RGB)."""
    plt.figure(figsize=figsize)
    if image.ndim == 2:
        plt.imshow(image, cmap=cmap or 'gray', vmin=0, vmax=255)
    else:
        plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    plt.title(title); plt.axis('off'); plt.show()

def show_grid(images, titles, cols=2, figsize=(12, 8), cmaps=None):
    """Side-by-side display of multiple images."""
    n = len(images)
    rows = (n + cols - 1) // cols
    plt.figure(figsize=figsize)
    for i, (img, t) in enumerate(zip(images, titles)):
        plt.subplot(rows, cols, i + 1)
        cmap = (cmaps[i] if cmaps else None)
        if img.ndim == 2:
            plt.imshow(img, cmap=cmap or 'gray')
        else:
            plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        plt.title(t); plt.axis('off')
    plt.tight_layout(); plt.show()

print("Helpers ready.")

"""## 1.2 Load the sample images we'll reuse throughout

All from `skimage.data` — bundled, no network, no licensing issues.

"""

os.makedirs('images', exist_ok=True)

def to_bgr(arr):
    """Convert a skimage array (RGB or gray, uint8) to OpenCV-compatible BGR/gray uint8."""
    if arr.dtype != np.uint8:
        arr = (255 * (arr - arr.min()) / max(1e-9, arr.max() - arr.min())).astype(np.uint8)
    if arr.ndim == 3:
        return cv2.cvtColor(arr, cv2.COLOR_RGB2BGR)
    return arr

samples = {
    "astronaut.jpg" : skdata.astronaut,   # 512x512 color portrait
    "coffee.jpg"    : skdata.coffee,      # 400x600 color
    "coins.jpg"     : skdata.coins,       # 303x384 grayscale, classic segmentation
    "chelsea.jpg"   : skdata.chelsea,     # 300x451 color (cat)
    "rocket.jpg"    : skdata.rocket,      # 427x640 color (rocket launch)
    "page.jpg"      : skdata.page,        # 191x384 grayscale (text page)
    "moon.jpg"      : skdata.moon,        # 512x512 grayscale
    "camera.jpg"    : skdata.camera,      # 512x512 grayscale (man + camera)
    "brick.jpg"     : skdata.brick,       # 512x512 grayscale texture
    "checkerboard.png": skdata.checkerboard,  # 200x200 synthetic, for calibration concepts
    "horse.png"     : skdata.horse,       # 328x400 binary horse silhouette
    "text.png"      : skdata.text,        # 172x448 grayscale
}

for fname, loader in samples.items():
    arr = loader()
    if arr.dtype == bool:
        arr = (arr.astype(np.uint8) * 255)
        # invert "horse" so the horse is white-on-black (foreground convention)
        if fname == 'horse.png':
            arr = 255 - arr
    img_bgr = to_bgr(arr)
    cv2.imwrite(f'images/{fname}', img_bgr)
    print(f"✓ {fname:18s} shape={str(arr.shape):16s} dtype={arr.dtype}")

# Stereo pair (left + right images of a motorcycle, real calibrated stereo)
stereo_left, stereo_right, _ = skdata.stereo_motorcycle()
cv2.imwrite('images/stereo_left.png',  to_bgr(stereo_left))
cv2.imwrite('images/stereo_right.png', to_bgr(stereo_right))
print(f"✓ stereo_left/right.png shape={stereo_left.shape}, dtype={stereo_left.dtype}")

print("\nFiles saved:")
for f in sorted(os.listdir('images')):
    p = os.path.join('images', f)
    print(f"  {f:22s} {os.path.getsize(p):>8,} bytes")

"""---
# 2. 🏔️ Image Pyramids — Multi-Scale Processing

A **pyramid** is a stack of progressively smaller (or larger) versions of the same image. They're a foundational tool for:

- **Coarse-to-fine search**: detect at low res, refine at high res — much faster
- **Multi-scale feature detection**: SIFT internally builds a Gaussian pyramid
- **Image blending**: Laplacian pyramids let you seamlessly blend two images

OpenCV provides:
- `cv2.pyrDown(img)` — Gaussian-filter then downsample by 2 → halves both dimensions
- `cv2.pyrUp(img)` — upsample by 2 then Gaussian-filter → doubles both dimensions

> ⚠️ `pyrUp(pyrDown(img))` does **not** equal `img` — information is lost. The difference is what makes Laplacian pyramids work.

"""

img = cv2.imread('images/astronaut.jpg')
print(f"Original: {img.shape}")

# Build a 4-level Gaussian pyramid
gp = [img]
for i in range(4):
    gp.append(cv2.pyrDown(gp[-1]))
    print(f"Level {i+1}: {gp[-1].shape}  (1/{2**(i+1)} resolution)")

show_grid(gp, [f"L{i}: {im.shape[1]}x{im.shape[0]}" for i, im in enumerate(gp)],
          cols=5, figsize=(15, 3))

"""## 2.1 Laplacian pyramid

A Laplacian pyramid stores the *details lost* at each level of the Gaussian pyramid. Reconstruct by adding the details back as you upsample. Used for **seamless image blending** — paste apple half + orange half = "orapple" with no visible seam.

"""

# Laplacian level i = G_i  -  pyrUp(G_{i+1})
# We need to size-match because pyrUp doesn't always give exactly 2x.
lp = []
for i in range(len(gp) - 1):
    upsampled = cv2.pyrUp(gp[i + 1], dstsize=(gp[i].shape[1], gp[i].shape[0]))
    laplacian = cv2.subtract(gp[i], upsampled)
    lp.append(laplacian)
    print(f"Laplacian L{i}: shape={laplacian.shape}, "
          f"range=[{laplacian.min()}, {laplacian.max()}], mean={laplacian.mean():.1f}")

# Visualize — add 128 so negative differences are visible
viz = [cv2.add(l, 128) for l in lp]
show_grid(viz, [f"Laplacian L{i}" for i in range(len(lp))], cols=4, figsize=(14, 4))

# Demonstrate reconstruction (last Gaussian + Laplacians sum back to the original)
recon = gp[-1]
for i in reversed(range(len(lp))):
    recon = cv2.pyrUp(recon, dstsize=(lp[i].shape[1], lp[i].shape[0]))
    recon = cv2.add(recon, lp[i])
err = np.abs(recon.astype(int) - img.astype(int)).mean()
print(f"\nReconstruction error vs. original: {err:.3f} per-pixel "
      f"(should be near zero)")

"""---
# 3. 📐 Hough Transforms — Detecting Lines and Circles

The Hough transform finds parametric shapes (lines, circles) by **voting**: each edge pixel "votes" for every shape that could pass through it; peaks in the parameter space are the detected shapes.

**Robotics applications**: lane detection in self-driving, pipe/wire detection in industrial robotics, finding round fiducials.

## 3.1 Probabilistic Hough lines

`cv2.HoughLinesP` is the **practical** version — it returns concrete line segments `(x1, y1, x2, y2)` instead of infinite lines.
"""

# Build a scene with strong straight edges — checkerboard works perfectly
checker = cv2.imread('images/checkerboard.png', cv2.IMREAD_GRAYSCALE)

edges = cv2.Canny(checker, 50, 150)

# threshold = minimum vote count for a line to be returned
# minLineLength = shortest line we accept
# maxLineGap = max pixel gap allowed within one line
lines = cv2.HoughLinesP(edges, rho=1, theta=np.pi/180,
                        threshold=80, minLineLength=30, maxLineGap=10)

print(f"Lines detected: {0 if lines is None else len(lines)}")
print(f"Output array shape: {None if lines is None else lines.shape}  "
      f"(N lines, 1, 4 endpoints)")

vis = cv2.cvtColor(checker, cv2.COLOR_GRAY2BGR)
if lines is not None:
    for x1, y1, x2, y2 in lines.squeeze():
        cv2.line(vis, (x1, y1), (x2, y2), (0, 0, 255), 2)

show_grid([checker, edges, vis],
          ["Input", "Canny edges", f"HoughLinesP — {len(lines)} segments"],
          cols=3, figsize=(13, 4))

"""## 3.2 Hough circles

`cv2.HoughCircles` finds circles. The classic demo: counting coins.

"""

coins = cv2.imread('images/coins.jpg', cv2.IMREAD_GRAYSCALE)
coins_blur = cv2.medianBlur(coins, 5)

# Parameters that matter:
#   dp        : inverse accumulator resolution (1 = same as input)
#   minDist   : minimum distance between detected centers
#   param1    : higher Canny threshold (lower = param1/2)
#   param2    : accumulator threshold (smaller = more circles, more false positives)
#   minRadius / maxRadius : expected circle size range
circles = cv2.HoughCircles(coins_blur, cv2.HOUGH_GRADIENT, dp=1.2, minDist=30,
                            param1=80, param2=30, minRadius=15, maxRadius=40)

vis = cv2.cvtColor(coins, cv2.COLOR_GRAY2BGR)
if circles is not None:
    circles = np.round(circles[0]).astype(int)
    print(f"Circles detected: {len(circles)}")
    for i, (x, y, r) in enumerate(circles):
        cv2.circle(vis, (x, y), r, (0, 255, 0), 2)
        cv2.circle(vis, (x, y), 2, (0, 0, 255), 3)
        cv2.putText(vis, str(i + 1), (x - 10, y - r - 5),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1)

show_grid([coins, coins_blur, vis],
          ["Input", "Median-blurred", f"HoughCircles — {len(circles)} coins"],
          cols=3, figsize=(13, 4))

"""---
# 4. 💧 Watershed Segmentation — Separating Touching Objects

When objects **touch**, simple thresholding merges them into one blob. The **watershed algorithm** treats the image like a topographic surface and "floods" it from marked seed points — boundaries form where floods meet.

The trick: provide good **markers**. We use the distance transform to find object centers and morphology to find the sure-background.

"""

coins = cv2.imread('images/coins.jpg')
gray  = cv2.cvtColor(coins, cv2.COLOR_BGR2GRAY)

# Step 1: clean binary mask
_, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
thresh = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, np.ones((3, 3), np.uint8), iterations=2)

# Step 2: sure background = dilation of foreground
sure_bg = cv2.dilate(thresh, np.ones((3, 3), np.uint8), iterations=3)

# Step 3: sure foreground = peaks of the distance transform
dist = cv2.distanceTransform(thresh, cv2.DIST_L2, 5)
print(f"Distance transform: shape={dist.shape}, dtype={dist.dtype}, "
      f"range=[{dist.min():.1f}, {dist.max():.1f}]")
_, sure_fg = cv2.threshold(dist, 0.5 * dist.max(), 255, 0)
sure_fg = sure_fg.astype(np.uint8)

# Step 4: unknown = bg - fg
unknown = cv2.subtract(sure_bg, sure_fg)

# Step 5: connected-component labeling on sure_fg
n_markers, markers = cv2.connectedComponents(sure_fg)
print(f"Connected components found: {n_markers - 1} (excluding background)")

# Convention: background must be 1 (not 0), unknown must be 0
markers = markers + 1
markers[unknown == 255] = 0

# Step 6: watershed — modifies markers in place; boundaries become -1
markers = cv2.watershed(coins, markers)

# Visualize
result = coins.copy()
result[markers == -1] = [0, 0, 255]   # boundaries in red
print(f"After watershed: {markers.max()} regions, "
      f"boundary pixels: {(markers == -1).sum():,}")

# Pretty marker map (random colors per label)
rng = np.random.default_rng(42)
colors = rng.integers(50, 255, size=(markers.max() + 2, 3), dtype=np.uint8)
colors[0] = [0, 0, 0]  # boundary -1 stays "off"
marker_vis = colors[markers + 1]  # shift -1 to 0

show_grid([coins, dist / dist.max(), marker_vis, result],
          ["Original", "Distance transform", "Watershed labels", "Boundaries (red)"],
          cols=2, figsize=(11, 9))

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Helper function to display images (assuming show_grid is not defined here)
def show_grid(images, titles, cols=2, figsize=(12, 10)):
    rows = (len(images) + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=figsize)
    axes = axes.flatten()
    for i, (ax, img, title) in enumerate(zip(axes, images, titles)):
        if len(img.shape) == 2:
            ax.imshow(img, cmap='gray')
        else:
            # OpenCV uses BGR, matplotlib expects RGB
            ax.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        ax.set_title(title)
        ax.axis('off')
    for ax in axes[len(images):]:
        ax.axis('off')
    plt.tight_layout()
    plt.show()

# 1. Load the image
coins = cv2.imread('images/coins.jpg')
gray  = cv2.cvtColor(coins, cv2.COLOR_BGR2GRAY)

# ==============================================================================
# 🌟 NEW ADDITION: Apply CLAHE to equalize the uneven lighting
# This ensures that coins in the dark areas are as visible as those in the light
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
gray_clahe = clahe.apply(gray)
# ==============================================================================

# Step 1: Clean binary mask (Now applied on the CLAHE-enhanced image)
_, thresh = cv2.threshold(gray_clahe, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
thresh = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, np.ones((3, 3), np.uint8), iterations=2)

# Step 2: Sure background = dilation of foreground
sure_bg = cv2.dilate(thresh, np.ones((3, 3), np.uint8), iterations=3)

# Step 3: Sure foreground = peaks of the distance transform
dist = cv2.distanceTransform(thresh, cv2.DIST_L2, 5)
print(f"Distance transform: shape={dist.shape}, dtype={dist.dtype}, "
      f"range=[{dist.min():.1f}, {dist.max():.1f}]")
# We lower the threshold slightly from 0.5 to 0.4 to catch smaller/fainter peaks
_, sure_fg = cv2.threshold(dist, 0.4 * dist.max(), 255, 0)
sure_fg = sure_fg.astype(np.uint8)

# Step 4: Unknown = bg - fg
unknown = cv2.subtract(sure_bg, sure_fg)

# Step 5: Connected-component labeling on sure_fg
n_markers, markers = cv2.connectedComponents(sure_fg)
print(f"Connected components found: {n_markers - 1} (excluding background)")

# Convention: background must be 1 (not 0), unknown must be 0
markers = markers + 1
markers[unknown == 255] = 0

# Step 6: Watershed — modifies markers in place; boundaries become -1
markers = cv2.watershed(coins, markers)

# Visualize
result = coins.copy()
result[markers == -1] = [0, 0, 255]   # boundaries in red
print(f"After watershed: {markers.max()} regions, "
      f"boundary pixels: {(markers == -1).sum():,}")

# Pretty marker map (random colors per label)
rng = np.random.default_rng(42)
colors = rng.integers(50, 255, size=(markers.max() + 2, 3), dtype=np.uint8)
colors[0] = [0, 0, 0]  # boundary -1 stays "off"
marker_vis = colors[markers + 1]  # shift -1 to 0

show_grid([coins, gray_clahe, thresh, dist / dist.max(), marker_vis, result],
          ["Original", "CLAHE Enhanced", "Binary Mask (Cleaned)", "Distance transform", "Watershed labels", "Boundaries (red)"],
          cols=3, figsize=(15, 10))

"""---
# 5. ✂️ GrabCut — Foreground Extraction with a Bounding Box

**GrabCut** is an interactive segmentation algorithm. Given a rough bounding box around the foreground, it iteratively models foreground/background color distributions (Gaussian Mixture Models) and refines the segmentation using graph cuts.

Use cases: photo editing ("remove the background"), creating training data for ML, robot grasp targets.

"""

img = cv2.imread('images/astronaut.jpg')
mask = np.zeros(img.shape[:2], np.uint8)

# Bounding box around the astronaut (x, y, w, h) — a rough guess is fine
rect = (60, 60, 400, 450)

# These are buffers GrabCut needs internally
bgdModel = np.zeros((1, 65), np.float64)
fgdModel = np.zeros((1, 65), np.float64)

# 5 iterations of expectation-maximization
print("Running GrabCut (5 iterations)...")
t0 = time.time()
cv2.grabCut(img, mask, rect, bgdModel, fgdModel, 5, cv2.GC_INIT_WITH_RECT)
print(f"Done in {time.time() - t0:.2f} s")

# After GrabCut, mask values mean:
#   0 = sure bg, 1 = sure fg, 2 = probable bg, 3 = probable fg
print(f"Mask label distribution: {dict(zip(*np.unique(mask, return_counts=True)))}")

# Convert to a binary 0/1 mask: 0 and 2 -> bg (0); 1 and 3 -> fg (1)
mask2 = np.where((mask == 0) | (mask == 2), 0, 1).astype(np.uint8)
fg = img * mask2[:, :, None]

# Visualize the bounding box on the input
input_vis = img.copy()
cv2.rectangle(input_vis, (rect[0], rect[1]),
              (rect[0] + rect[2], rect[1] + rect[3]), (0, 255, 0), 3)

show_grid([input_vis, mask2 * 255, fg],
          ["Input + bbox", "GrabCut foreground mask", "Extracted foreground"],
          cols=3, figsize=(13, 5))

"""---
# 6. 📏 Distance Transforms & Skeletonization

A **distance transform** assigns each foreground pixel the distance to the nearest background pixel.

**Robotics applications**:
- **Path planning**: maximum-distance pixels are the "safest" routes (Voronoi-style maps)
- **Grasping**: distance transform peaks indicate object centers / wide regions
- **Skeletonization**: extract a 1-pixel-wide "centerline" — useful for character recognition, blood vessel analysis, etc.

"""

# Use the horse silhouette
horse = cv2.imread('images/horse.png', cv2.IMREAD_GRAYSCALE)
_, horse_bin = cv2.threshold(horse, 127, 255, cv2.THRESH_BINARY)
print(f"Binary horse: shape={horse_bin.shape}, fg pixels={(horse_bin > 0).sum():,}")

# Distance transforms with different metrics
# DIST_L1     - city-block (Manhattan)
# DIST_L2     - Euclidean (most common)
# DIST_C      - Chebyshev (chessboard)
dist_l2 = cv2.distanceTransform(horse_bin, cv2.DIST_L2, 5)
dist_l1 = cv2.distanceTransform(horse_bin, cv2.DIST_L1, 3)
dist_c  = cv2.distanceTransform(horse_bin, cv2.DIST_C,  3)

print(f"L2 distance transform: range=[{dist_l2.min():.1f}, {dist_l2.max():.1f}]  "
      f"(max distance from boundary inside the horse)")

# Skeletonization via iterative morphological thinning
# This is a standard trick: repeatedly erode and subtract opening
def skeletonize(img):
    skel = np.zeros(img.shape, np.uint8)
    img = img.copy()
    kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (3, 3))
    while True:
        opened = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)
        temp   = cv2.subtract(img, opened)
        eroded = cv2.erode(img, kernel)
        skel   = cv2.bitwise_or(skel, temp)
        img    = eroded.copy()
        if cv2.countNonZero(img) == 0:
            break
    return skel

skel = skeletonize(horse_bin)
print(f"Skeleton pixels: {(skel > 0).sum():,} "
      f"(originally {(horse_bin > 0).sum():,} — "
      f"{100 * (skel > 0).sum() / (horse_bin > 0).sum():.1f}% remaining)")

show_grid([horse_bin, dist_l2 / dist_l2.max(), dist_l1 / dist_l1.max(), skel],
          ["Binary input", "L2 distance", "L1 distance", "Skeleton"],
          cols=2, figsize=(11, 9))

import cv2
import numpy as np
import matplotlib.pyplot as plt

def show_grid(images, titles, cols=2, figsize=(12, 10)):
    rows = (len(images) + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=figsize)
    axes = axes.flatten()
    for i, (ax, img, title) in enumerate(zip(axes, images, titles)):
        if len(img.shape) == 2:
            ax.imshow(img, cmap='gray')
        else:
            ax.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        ax.set_title(title)
        ax.axis('off')
    for ax in axes[len(images):]:
        ax.axis('off')
    plt.tight_layout()
    plt.show()

def skeletonize(img):
    skel = np.zeros(img.shape, np.uint8)
    img = img.copy()
    kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (3, 3))
    while True:
        opened = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)
        temp   = cv2.subtract(img, opened)
        eroded = cv2.erode(img, kernel)
        skel   = cv2.bitwise_or(skel, temp)
        img    = eroded.copy()
        if cv2.countNonZero(img) == 0:
            break
    return skel

# 1. Load the image and create the initial binary mask
horse = cv2.imread('images/horse.png', cv2.IMREAD_GRAYSCALE)
_, horse_bin = cv2.threshold(horse, 127, 255, cv2.THRESH_BINARY)

# Original Skeleton (for baseline comparison)
skel_original = skeletonize(horse_bin)

# ==============================================================================
# 🌟 NEW ADDITION 1: Smoothing via Extreme Gaussian Blur + Threshold
# We apply a very large blur to melt away rough edges, then re-threshold to
# create a perfectly smooth, glass-like boundary.
blurred = cv2.GaussianBlur(horse_bin, (29, 29), 0)  # Maximum reasonable blur
_, horse_smooth_blur = cv2.threshold(blurred, 127, 255, cv2.THRESH_BINARY)

# Skeletonize the blur-smoothed image
skel_blur = skeletonize(horse_smooth_blur)
# ==============================================================================


# ==============================================================================
# 🌟 NEW ADDITION 2: Smoothing via Morphological Closing
# We use a large kernel to fill in micro-cracks and smooth out jagged edges
# without significantly altering the overall shape like extreme blurring might.
close_kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (15, 15))
horse_smooth_close = cv2.morphologyEx(horse_bin, cv2.MORPH_CLOSE, close_kernel)

# Skeletonize the morphology-smoothed image
skel_close = skeletonize(horse_smooth_close)
# ==============================================================================


# Visualize the results
show_grid([skel_original, skel_blur, skel_close],
          ["Original Skeleton (Spurs present)",
           "Skeleton after Extreme Blur",
           "Skeleton after Morph Closing"],
          cols=3, figsize=(18, 6))

"""---
# 7. 🔍 Template Matching

Slide a template image across a larger image and measure similarity at each position. Simple but effective when:

- Object orientation and scale are roughly known (no rotation/zoom invariance!)
- Lighting is consistent

**Industrial vision use case**: locating a known PCB component, finding registration marks, detecting defects against a golden template.

Six matching methods are available; `TM_CCOEFF_NORMED` is usually the most robust.

"""

img = cv2.imread('images/coins.jpg', cv2.IMREAD_GRAYSCALE)
print(f"Image shape: {img.shape}")

# Cut out one coin to use as the template
template = img[80:130, 230:280].copy()
H, W = template.shape
print(f"Template shape: {template.shape}")

# Run template matching
res = cv2.matchTemplate(img, template, cv2.TM_CCOEFF_NORMED)
print(f"Result shape: {res.shape} = (img_h - tmpl_h + 1, img_w - tmpl_w + 1)")
print(f"Score range: [{res.min():.3f}, {res.max():.3f}]")

# Find ALL matches above a threshold (multi-instance)
threshold = 0.7
locations = np.where(res >= threshold)
hits = list(zip(*locations[::-1]))  # (x, y) pairs
print(f"Matches above {threshold}: {len(hits)}")

# Non-maximum suppression: cluster hits that are very close together
def nms(points, min_dist):
    kept = []
    for p in sorted(points, key=lambda q: -res[q[1], q[0]]):  # highest score first
        if all((p[0] - q[0])**2 + (p[1] - q[1])**2 > min_dist**2 for q in kept):
            kept.append(p)
    return kept

unique = nms(hits, min_dist=20)
print(f"After NMS: {len(unique)} unique coin locations")

vis = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
for x, y in unique:
    cv2.rectangle(vis, (x, y), (x + W, y + H), (0, 255, 0), 2)

show_grid([template, res, vis],
          [f"Template ({W}x{H})", "Match scores (heatmap)", f"{len(unique)} matches found"],
          cols=3, figsize=(13, 4))

"""---
# 8. 🔑 Modern Feature Detectors — SIFT, BRISK, AKAZE

Beyond Harris/ORB (covered in the intro), OpenCV ships several robust feature detectors:

| Detector | Speed | Robustness | Notes |
|----------|-------|-----------|-------|
| **SIFT** | Slow | ⭐⭐⭐⭐⭐ | Patent expired in 2020 — now free. Gold standard. |
| **AKAZE** | Medium | ⭐⭐⭐⭐ | Free, scale & rotation invariant, binary descriptor |
| **BRISK** | Fast | ⭐⭐⭐ | Free, binary descriptor |
| **ORB** | Very fast | ⭐⭐⭐ | Free, designed as patent-free SIFT replacement |

A **descriptor** is a fixed-length vector that describes the local image patch around each keypoint. Two descriptors can be compared (Euclidean for SIFT floats; Hamming for binary descriptors like ORB/BRISK/AKAZE) to match keypoints between images.

[SURF](https://github.com/MJAHMADEE/SURF)

"""

img = cv2.imread('images/astronaut.jpg', cv2.IMREAD_GRAYSCALE)

detectors = {
    'SIFT':  cv2.SIFT_create(nfeatures=300),
    'AKAZE': cv2.AKAZE_create(),
    'BRISK': cv2.BRISK_create(),
    'ORB':   cv2.ORB_create(nfeatures=300),
}

vis = []
for name, det in detectors.items():
    t0 = time.time()
    kps, desc = det.detectAndCompute(img, None)
    dt = (time.time() - t0) * 1000
    print(f"{name:6s}: {len(kps):4d} kp,  desc shape={None if desc is None else desc.shape}, "
          f"dtype={None if desc is None else desc.dtype}, time={dt:6.1f} ms")
    drawn = cv2.drawKeypoints(cv2.cvtColor(img, cv2.COLOR_GRAY2BGR), kps, None,
                              color=(0, 255, 0),
                              flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
    vis.append(drawn)

show_grid(vis, list(detectors.keys()), cols=2, figsize=(12, 10))

"""---
# 9. 🤝 Feature Matching, RANSAC, and Homography

The full pipeline for **finding a known object in a scene** (or aligning two views):

1. Detect features in both images
2. Compute descriptors
3. Match descriptors (brute-force or FLANN)
4. Filter matches with **Lowe's ratio test**
5. Estimate a **homography** (3×3 perspective transform) using **RANSAC** to reject outliers
6. Use the homography to draw the object's outline / warp one image onto the other

**Robotics relevance**: planar pose estimation, image registration, mosaicking, loop closure in SLAM.

"""

# We'll detect a cropped region of the astronaut image inside the full image,
# after rotating + scaling the crop. This simulates "find this object in the scene".
full = cv2.imread('images/astronaut.jpg', cv2.IMREAD_GRAYSCALE)
H, W = full.shape

# Build a "query" by cropping + rotating + scaling
crop = full[60:340, 100:380].copy()
M = cv2.getRotationMatrix2D((crop.shape[1]/2, crop.shape[0]/2), angle=25, scale=0.8)
query = cv2.warpAffine(crop, M, (crop.shape[1], crop.shape[0]))

# 1. Detect SIFT in both
sift = cv2.SIFT_create()
kp1, des1 = sift.detectAndCompute(query, None)
kp2, des2 = sift.detectAndCompute(full,  None)
print(f"Query keypoints: {len(kp1)}, Scene keypoints: {len(kp2)}")

# 2. Brute-force matcher with k=2 nearest neighbors per descriptor
bf = cv2.BFMatcher(cv2.NORM_L2)
knn = bf.knnMatch(des1, des2, k=2)

# 3. Lowe's ratio test — a match is "good" if the best is much better than the 2nd best
good = [m for m, n in knn if m.distance < 0.75 * n.distance]
print(f"Raw matches: {len(knn)}, after ratio test: {len(good)}")

# 4. Need at least 4 matches for homography
MIN_MATCH_COUNT = 10
if len(good) >= MIN_MATCH_COUNT:
    src_pts = np.float32([kp1[m.queryIdx].pt for m in good]).reshape(-1, 1, 2)
    dst_pts = np.float32([kp2[m.trainIdx].pt for m in good]).reshape(-1, 1, 2)

    # RANSAC: tries random 4-point subsets; keeps the homography with the most inliers
    Hmat, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC, 5.0)
    matches_mask = mask.ravel().tolist()
    inliers = sum(matches_mask)
    print(f"RANSAC inliers: {inliers} / {len(good)} ({100*inliers/len(good):.1f}%)")
    print(f"Homography matrix:\n{Hmat}")

    # 5. Project the query's corners through the homography to find its location in the scene
    h, w = query.shape
    corners = np.float32([[0, 0], [0, h - 1], [w - 1, h - 1], [w - 1, 0]]).reshape(-1, 1, 2)
    projected = cv2.perspectiveTransform(corners, Hmat)

    scene_vis = cv2.cvtColor(full, cv2.COLOR_GRAY2BGR)
    cv2.polylines(scene_vis, [np.int32(projected)], True, (0, 255, 0), 3, cv2.LINE_AA)

    # 6. Draw the inlier matches
    draw_params = dict(matchColor=(0, 255, 0), singlePointColor=None,
                        matchesMask=matches_mask, flags=2)
    matches_vis = cv2.drawMatches(query, kp1, scene_vis, kp2, good, None, **draw_params)
    show(matches_vis, title=f"SIFT + RANSAC: {inliers} inliers, query located",
         figsize=(15, 5))
else:
    print(f"Not enough matches: {len(good)}")

"""---
# 10. 🖼️ Image Stitching (Panoramas)

The high-level `cv2.Stitcher` class wraps the entire pipeline (features → matching → homography → seam blending → tone correction) into one call. We'll create overlapping crops of one image and stitch them.

**Robotics**: drone aerial mapping, ground-station mosaicking, 360° robot perception.

"""

src = cv2.imread('images/astronaut.jpg')
print(f"Source: {src.shape}")

# Two overlapping crops (50% overlap)
left  = src[:, : src.shape[1] * 2 // 3]
right = src[:, src.shape[1] // 3 :]
print(f"Left:  {left.shape}, Right: {right.shape}")

# Build stitcher in PANORAMA mode (assumes rotation about camera center)
stitcher = cv2.Stitcher.create(cv2.Stitcher_PANORAMA)
status, pano = stitcher.stitch([left, right])

status_names = {0: 'OK', 1: 'ERR_NEED_MORE_IMGS',
                2: 'ERR_HOMOGRAPHY_EST_FAIL', 3: 'ERR_CAMERA_PARAMS_ADJUST_FAIL'}
print(f"Stitcher status: {status} ({status_names.get(status, 'UNKNOWN')})")

if status == cv2.Stitcher_OK:
    print(f"Panorama shape: {pano.shape}")
    show_grid([left, right, pano],
              ["Left input", "Right input", f"Stitched panorama {pano.shape[1]}x{pano.shape[0]}"],
              cols=1, figsize=(11, 11))
else:
    print("Stitching failed — try with images that have more overlap or texture.")

"""---
# 11. 🎯 Camera Calibration — The Foundation of Robot Vision

Every real camera has imperfections:
- The lens focal length and optical center (**intrinsics** `K`)
- Radial and tangential **distortion** (especially in wide-angle / cheap cameras)

**You cannot do metric robotics vision without calibration.** Without it, pixel-to-world mapping is meaningless.

The standard procedure: take ~15 photos of a **chessboard** from different angles, detect the corner grid, and let OpenCV solve for `K` and the distortion coefficients.

We don't have a real calibration dataset on hand, but we can demonstrate every API call and show what the inputs/outputs look like using **synthetic** chessboard views. The math is identical.

"""

# Synthesize a few "photos" of a chessboard from different angles by warping a synthetic checkerboard.
# In a real session you would replace this with cv2.imread('photo_NN.jpg') for each calibration shot.

# Build a clean chessboard pattern (7x6 inner corners means 8x7 squares)
PATTERN = (7, 6)             # inner corner count (cols, rows)
SQUARE_SIZE_PX = 50          # in pixels
W, H = (PATTERN[0] + 1) * SQUARE_SIZE_PX, (PATTERN[1] + 1) * SQUARE_SIZE_PX
board = np.zeros((H, W), np.uint8)
for r in range(PATTERN[1] + 1):
    for c in range(PATTERN[0] + 1):
        if (r + c) % 2 == 0:
            board[r*SQUARE_SIZE_PX:(r+1)*SQUARE_SIZE_PX,
                  c*SQUARE_SIZE_PX:(c+1)*SQUARE_SIZE_PX] = 255

print(f"Synthetic chessboard: {board.shape}, {PATTERN} inner corners")
show(board, title="Synthetic calibration target", figsize=(6, 5))

# Generate several warped views of it (simulating different camera poses)
def warp_view(img, angle, tx, ty, scale, out_size):
    H, W = img.shape
    src = np.float32([[0, 0], [W, 0], [0, H], [W, H]])
    M = cv2.getRotationMatrix2D((W/2, H/2), angle, scale)
    # apply rotation + translation
    M[:, 2] += [tx, ty]
    return cv2.warpAffine(img, M, out_size, borderValue=128)

views = [
    warp_view(board, angle=  0, tx=  0, ty=  0, scale=0.7, out_size=(640, 480)),
    warp_view(board, angle= 15, tx= 30, ty=-20, scale=0.6, out_size=(640, 480)),
    warp_view(board, angle=-20, tx=-30, ty= 40, scale=0.65, out_size=(640, 480)),
    warp_view(board, angle= 10, tx= 60, ty= 30, scale=0.55, out_size=(640, 480)),
    warp_view(board, angle=-10, tx=-50, ty=-30, scale=0.7, out_size=(640, 480)),
]
show_grid(views, [f"View {i+1}" for i in range(len(views))], cols=3, figsize=(14, 6))

# === Calibration pipeline ===
# 1. Define the 3D coordinates of the chessboard corners in the *board's own* frame.
#    Z = 0 because the board is flat. Units: arbitrary (use mm if you want metric output).
objp = np.zeros((PATTERN[0] * PATTERN[1], 3), np.float32)
objp[:, :2] = np.mgrid[0:PATTERN[0], 0:PATTERN[1]].T.reshape(-1, 2)
print(f"3D template points (one set per view): {objp.shape}")
print(objp[:5], "...")

# 2. For each view: detect chessboard corners in the image
obj_points, img_points = [], []
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

for i, v in enumerate(views):
    found, corners = cv2.findChessboardCorners(v, PATTERN, None)
    if found:
        # sub-pixel refinement — important for accurate calibration
        refined = cv2.cornerSubPix(v, corners, (11, 11), (-1, -1), criteria)
        obj_points.append(objp)
        img_points.append(refined)
        print(f"View {i+1}: ✓ {len(refined)} corners")
    else:
        print(f"View {i+1}: ✗ corners not found")

print(f"\nUsable views: {len(obj_points)} / {len(views)}")

# 3. Calibrate
img_size = views[0].shape[::-1]  # (width, height)
ret, K, dist, rvecs, tvecs = cv2.calibrateCamera(obj_points, img_points, img_size, None, None)

print(f"Calibration RMS reprojection error: {ret:.4f} px (lower = better; <1.0 is great)")
print(f"\nIntrinsic matrix K:\n{K}")
print(f"\nDistortion coefficients (k1, k2, p1, p2, k3): {dist.ravel()}")
print(f"\nNumber of (rvec, tvec) pose pairs estimated: {len(rvecs)}")

# Decompose K
fx, fy = K[0, 0], K[1, 1]
cx, cy = K[0, 2], K[1, 2]
print(f"\nFocal lengths   : fx={fx:.2f} px,  fy={fy:.2f} px")
print(f"Principal point : cx={cx:.2f} px,  cy={cy:.2f} px")

# 4. Use the calibration to undistort an image
# In a real wide-angle photo this dramatically straightens curved lines.
v = views[0]
undist = cv2.undistort(v, K, dist)

# Compute reprojection error on training data — sanity check
mean_err = 0
for i in range(len(obj_points)):
    proj, _ = cv2.projectPoints(obj_points[i], rvecs[i], tvecs[i], K, dist)
    err = cv2.norm(img_points[i], proj, cv2.NORM_L2) / len(proj)
    mean_err += err
print(f"Per-view mean reprojection error: {mean_err / len(obj_points):.4f} px")

show_grid([v, undist], ["Original (synthetic, low distortion)", "Undistorted"],
          cols=2, figsize=(12, 5))

"""---
# 12. 🎲 Pose Estimation (PnP) — Where Is the Camera?

**PnP (Perspective-n-Point)**: given
- a calibrated camera (`K`, `dist`)
- N known 3D points (in some world / object frame)
- their 2D projections in the image

solve for the camera's **rotation `R`** and **translation `t`** with respect to the world frame.

This is the **single most useful function in robotics vision**:
- AR overlays anchored to a marker
- Robot localization w.r.t. a known fiducial
- Object pose estimation for grasping

"""

# Suppose we have a calibrated camera (use the K/dist from the previous section)
# and we see a planar object (the chessboard) in an image. We can estimate its pose.
v = views[1]
found, corners = cv2.findChessboardCorners(v, PATTERN, None)
if found:
    corners = cv2.cornerSubPix(v, corners, (11, 11), (-1, -1), criteria)

    # solvePnP returns rotation vector (Rodrigues) and translation vector
    ok, rvec, tvec = cv2.solvePnP(objp, corners, K, dist)
    print(f"solvePnP success: {ok}")
    print(f"\nrvec (Rodrigues, radians): {rvec.ravel()}")
    print(f"tvec (translation, in board units): {tvec.ravel()}")

    # Convert rvec -> 3x3 rotation matrix
    R, _ = cv2.Rodrigues(rvec)
    print(f"\nRotation matrix R:\n{R}")
    print(f"\nDeterminant of R: {np.linalg.det(R):.6f}  (must be +1 for a valid rotation)")

    # === Draw a 3D coordinate axis on top of the board to verify pose ===
    axis_len = 3
    axis_3d = np.float32([[0,0,0], [axis_len,0,0], [0,axis_len,0], [0,0,-axis_len]])
    axis_2d, _ = cv2.projectPoints(axis_3d, rvec, tvec, K, dist)
    axis_2d = axis_2d.reshape(-1, 2).astype(int)

    pose_vis = cv2.cvtColor(v, cv2.COLOR_GRAY2BGR)
    cv2.drawChessboardCorners(pose_vis, PATTERN, corners, found)
    o, x, y, z = axis_2d
    cv2.line(pose_vis, tuple(o), tuple(x), (0, 0, 255), 4)  # X red
    cv2.line(pose_vis, tuple(o), tuple(y), (0, 255, 0), 4)  # Y green
    cv2.line(pose_vis, tuple(o), tuple(z), (255, 0, 0), 4)  # Z blue (pointing out of board)

    show(pose_vis, title="3D axis from solvePnP — X(red), Y(green), Z(blue)", figsize=(8, 6))

"""---
# 13. 👀 Stereo Vision — Computing Depth

Two cameras separated by a known **baseline** see the world from slightly different viewpoints. The horizontal pixel shift of an object between the two images is its **disparity**, which is **inversely proportional to depth**:

$$ Z = \frac{f \cdot B}{d} $$

where `f` = focal length, `B` = baseline, `d` = disparity. **More disparity → closer object.**

**Robotics applications**: passive 3D sensing for outdoor robots, obstacle detection, drone landing.

We use scikit-image's bundled, calibrated stereo motorcycle pair.

"""

left  = cv2.imread('images/stereo_left.png',  cv2.IMREAD_GRAYSCALE)
right = cv2.imread('images/stereo_right.png', cv2.IMREAD_GRAYSCALE)
print(f"Left : {left.shape}, Right: {right.shape}")
show_grid([left, right], ["Left camera", "Right camera"], cols=2, figsize=(13, 5))

# StereoBM = block matching, fast but blocky
# StereoSGBM = semi-global block matching, slower but much smoother

# numDisparities must be divisible by 16; controls max measurable depth
# blockSize is the matching window; odd, typically 5-15
sgbm = cv2.StereoSGBM_create(
    minDisparity=0,
    numDisparities=128,    # search range in pixels
    blockSize=5,
    P1=8 * 3 * 5**2,        # smoothness penalty (small disparity changes)
    P2=32 * 3 * 5**2,       # smoothness penalty (large disparity changes)
    disp12MaxDiff=1,
    uniquenessRatio=10,
    speckleWindowSize=100,
    speckleRange=32,
)

t0 = time.time()
disparity = sgbm.compute(left, right)
print(f"SGBM time: {(time.time() - t0)*1000:.1f} ms")
print(f"Disparity raw: dtype={disparity.dtype}, "
      f"range=[{disparity.min()}, {disparity.max()}]")

# SGBM returns disparity * 16 as int16; convert to true float pixel disparity
disp_float = disparity.astype(np.float32) / 16.0
print(f"Disparity (true pixels): range=[{disp_float.min():.1f}, {disp_float.max():.1f}]")

# Pretty colormap
disp_norm = cv2.normalize(disp_float, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
disp_color = cv2.applyColorMap(disp_norm, cv2.COLORMAP_JET)
# Set invalid pixels (disparity < 0) to black
disp_color[disp_float < 0] = 0

show_grid([left, disp_norm, disp_color],
          ["Left image", "Disparity (gray)", "Disparity (jet — closer = red)"],
          cols=1, figsize=(10, 11))

# Convert disparity to depth: Z = f * B / d
# Approximate values for the motorcycle dataset (real numbers would come from calibration)
focal_px = 1758.0  # focal length in pixels (approx)
baseline_m = 0.115  # baseline in meters (approx)
with np.errstate(divide='ignore'):
    depth = focal_px * baseline_m / np.where(disp_float > 0, disp_float, np.nan)
print(f"\nApprox. depth statistics (meters):")
print(f"  Min/Max depth (valid pixels): {np.nanmin(depth):.2f} m / {np.nanmax(depth):.2f} m")
print(f"  Median depth                : {np.nanmedian(depth):.2f} m")

"""---
# 14. 🌊 Optical Flow

**Optical flow** estimates how each pixel moves between consecutive video frames. Two flavors:

- **Sparse** (Lucas–Kanade) — track a chosen set of points; very fast, precise on textured points
- **Dense** (Farnebäck) — flow vector at *every* pixel; slower, useful for global motion

**Robotics applications**: visual odometry (robot self-motion), gesture recognition, video stabilization, motion-based segmentation.

"""

# Build a synthetic 2-frame "video": one frame, plus the same frame translated.
img1 = cv2.imread('images/astronaut.jpg', cv2.IMREAD_GRAYSCALE)
M = np.float32([[1, 0, 15], [0, 1, 8]])  # shift by (15, 8) pixels
img2 = cv2.warpAffine(img1, M, (img1.shape[1], img1.shape[0]))

# === Sparse: Lucas-Kanade ===
# Pick "good" corners to track in frame 1
p0 = cv2.goodFeaturesToTrack(img1, maxCorners=100, qualityLevel=0.3,
                              minDistance=7, blockSize=7)
print(f"Tracking {len(p0)} corners")

# Track them into frame 2
p1, status, err = cv2.calcOpticalFlowPyrLK(img1, img2, p0, None,
                                             winSize=(15, 15), maxLevel=2)
good_old = p0[status == 1]
good_new = p1[status == 1]
print(f"Successfully tracked: {len(good_new)} / {len(p0)} corners")

# Visualize: arrows from old -> new
flow_vis = cv2.cvtColor(img2, cv2.COLOR_GRAY2BGR)
for new, old in zip(good_new, good_old):
    a, b = new.ravel().astype(int)
    c, d = old.ravel().astype(int)
    cv2.arrowedLine(flow_vis, (c, d), (a, b), (0, 255, 0), 1, tipLength=0.4)
    cv2.circle(flow_vis, (a, b), 2, (0, 0, 255), -1)

# Average measured flow vs ground-truth (15, 8)
displacements = good_new - good_old
print(f"Mean tracked displacement: dx={displacements[:, 0].mean():.2f}, "
      f"dy={displacements[:, 1].mean():.2f}  (truth: dx=15, dy=8)")

show(flow_vis, title="Sparse optical flow (Lucas-Kanade)", figsize=(8, 8))

# === Dense: Farneback ===
flow = cv2.calcOpticalFlowFarneback(img1, img2, None,
                                     pyr_scale=0.5, levels=3, winsize=15,
                                     iterations=3, poly_n=5, poly_sigma=1.2, flags=0)
print(f"Dense flow shape: {flow.shape}  (H, W, 2 — last dim is [dx, dy])")
print(f"Mean flow vector: dx={flow[..., 0].mean():.2f}, dy={flow[..., 1].mean():.2f}")

# Visualize as HSV: hue = direction, saturation = 255, value = magnitude
mag, ang = cv2.cartToPolar(flow[..., 0], flow[..., 1])
hsv = np.zeros((*img1.shape, 3), np.uint8)
hsv[..., 0] = ang * 180 / np.pi / 2          # hue 0-179
hsv[..., 1] = 255
hsv[..., 2] = cv2.normalize(mag, None, 0, 255, cv2.NORM_MINMAX)
flow_rgb = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)

show_grid([img1, img2, flow_rgb],
          ["Frame 1", "Frame 2 (shifted)", "Dense flow (HSV: hue=dir, val=mag)"],
          cols=3, figsize=(14, 5))

"""---
# 15. 🎭 Background Subtraction

When the camera is **stationary**, you can model the static background and flag pixels that change as foreground. OpenCV ships two strong algorithms:

- **MOG2** — Mixture of Gaussians per pixel; handles gradual illumination changes
- **KNN** — K-nearest-neighbors per pixel; better when the foreground is small

**Use cases**: surveillance, traffic monitoring, motion detection on a fixed-camera robot.

We'll synthesize a "video" of a moving object on a static background.

"""

# Create 50 frames: a moving bright disk on a fixed coffee-image background
bg = cv2.imread('images/coffee.jpg')
H, W = bg.shape[:2]

frames = []
for i in range(50):
    f = bg.copy()
    cx = int(50 + (W - 100) * i / 49)
    cy = H // 2 + int(20 * np.sin(i / 5))
    cv2.circle(f, (cx, cy), 30, (255, 255, 255), -1)
    frames.append(f)

print(f"Synthesized {len(frames)} frames of {frames[0].shape}")

# === MOG2 ===
mog = cv2.createBackgroundSubtractorMOG2(history=20, varThreshold=25, detectShadows=True)
mog_masks = []
for f in frames:
    m = mog.apply(f)
    mog_masks.append(m)

print(f"MOG2 mask values: {np.unique(mog_masks[-1])}  "
      f"(0=bg, 127=shadow, 255=fg)")

# === KNN ===
knn = cv2.createBackgroundSubtractorKNN(history=20, dist2Threshold=400, detectShadows=False)
knn_masks = [knn.apply(f) for f in frames]

# Show what they detect on a late frame (after the model has converged)
idx = 40
show_grid([frames[idx], mog_masks[idx], knn_masks[idx]],
          [f"Frame {idx}", "MOG2 foreground", "KNN foreground"],
          cols=3, figsize=(14, 5))

"""---
# 16. 🎯 Object Tracking

Given a bounding box in the first frame, **track** the object through subsequent frames. Modern OpenCV trackers:

| Tracker | Strengths |
|---------|-----------|
| **CSRT** | Most accurate; handles non-rigid deformation; slower |
| **KCF** | Fast; good for rigid objects |
| **MIL** | Older, robust to partial occlusion |

> ⚠️ Different OpenCV versions expose trackers differently. In 4.5.2+, they're under `cv2.legacy.*` (the original API) and also a few at `cv2.*`. We try both.

"""

def make_tracker(name):
    """Create a tracker, handling API variations across OpenCV versions."""
    creators = []
    if name == 'CSRT':
        creators = [getattr(cv2, 'TrackerCSRT_create', None),
                     getattr(getattr(cv2, 'legacy', None), 'TrackerCSRT_create', None)]
    elif name == 'KCF':
        creators = [getattr(cv2, 'TrackerKCF_create', None),
                     getattr(getattr(cv2, 'legacy', None), 'TrackerKCF_create', None)]
    elif name == 'MIL':
        creators = [getattr(cv2, 'TrackerMIL_create', None),
                     getattr(getattr(cv2, 'legacy', None), 'TrackerMIL_create', None)]
    for c in creators:
        if c:
            return c()
    return None

# Reuse our synthesized "moving disk" video
init_bbox = (50 - 30, H // 2 - 30, 60, 60)  # (x, y, w, h) around the disk in frame 0
tracker_name = 'CSRT'
tracker = make_tracker(tracker_name)
print(f"{tracker_name} tracker created: {tracker is not None}")

if tracker is not None:
    ok = tracker.init(frames[0], init_bbox)
    print(f"Init success: {ok}, initial bbox: {init_bbox}")

    snapshots = []
    snap_indices = [0, 15, 30, 45]

    for i, f in enumerate(frames):
        ok, bbox = tracker.update(f)
        if i in snap_indices:
            vis = f.copy()
            if ok:
                x, y, w, h = [int(v) for v in bbox]
                cv2.rectangle(vis, (x, y), (x + w, y + h), (0, 255, 0), 2)
                cv2.putText(vis, f"Frame {i}", (10, 30),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
            else:
                cv2.putText(vis, "TRACKING LOST", (10, 30),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
            snapshots.append(vis)

    show_grid(snapshots, [f"Frame {i}" for i in snap_indices],
              cols=2, figsize=(12, 8))

"""---
# 17. 🌐 Fourier Transform — The Frequency Domain

Every image can be decomposed into a sum of sinusoidal patterns. The **Discrete Fourier Transform (DFT)** moves between the spatial domain (pixels) and the frequency domain (sinusoids).

**Why robotics cares**:
- Remove **periodic noise** (e.g., interference from fluorescent lights)
- Detect dominant orientations (e.g., gratings, fence patterns)
- Phase correlation for sub-pixel image registration

"""

img = cv2.imread('images/moon.jpg', cv2.IMREAD_GRAYSCALE)

# OpenCV's DFT works on float32 arrays
dft = cv2.dft(np.float32(img), flags=cv2.DFT_COMPLEX_OUTPUT)
dft_shift = np.fft.fftshift(dft)  # move zero frequency to center
print(f"DFT shape: {dft_shift.shape}  (H, W, 2 — real and imag)")

# Magnitude spectrum (log-scaled for visualization)
mag = cv2.magnitude(dft_shift[..., 0], dft_shift[..., 1])
mag_log = 20 * np.log(mag + 1)
print(f"Magnitude spectrum: range=[{mag_log.min():.1f}, {mag_log.max():.1f}]")

# === Build a low-pass filter (keep only low frequencies) ===
H, W = img.shape
crow, ccol = H // 2, W // 2

mask_lp = np.zeros((H, W, 2), np.float32)
cv2.circle(mask_lp, (ccol, crow), 30, (1, 1), -1)  # keep frequencies inside radius 30

mask_hp = np.ones((H, W, 2), np.float32)
cv2.circle(mask_hp, (ccol, crow), 30, (0, 0), -1)  # zero out low frequencies

# Apply filters and invert the DFT
def filter_and_invert(mask):
    filtered = dft_shift * mask
    f_ishift = np.fft.ifftshift(filtered)
    out = cv2.idft(f_ishift)
    out = cv2.magnitude(out[..., 0], out[..., 1])
    return cv2.normalize(out, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

low_pass  = filter_and_invert(mask_lp)
high_pass = filter_and_invert(mask_hp)

print(f"\nLow-pass result : range=[{low_pass.min()}, {low_pass.max()}] (looks blurred)")
print(f"High-pass result: range=[{high_pass.min()}, {high_pass.max()}] (looks like edges)")

show_grid([img, mag_log, low_pass, high_pass],
          ["Original", "Log-magnitude FFT", "Low-pass filtered", "High-pass filtered"],
          cols=2, figsize=(11, 9))

"""---
# 18. 🩹 Inpainting & Seamless Cloning

- **`cv2.inpaint`** fills a masked region using surrounding pixels — restore scratches, remove date stamps, erase small unwanted objects.
- **`cv2.seamlessClone`** copies a region from one image into another while matching colors and gradients at the boundary — the result has no visible seam.

These power virtually every "magic eraser" / "object remover" / "photo composite" feature you've ever used.

"""

# === Inpainting: simulate a scratch and remove it ===
img = cv2.imread('images/coffee.jpg')
damaged = img.copy()
mask = np.zeros(img.shape[:2], np.uint8)

# Draw "scratches" — both on the image and on the mask
for (p1, p2) in [((50, 50), (550, 350)), ((100, 350), (500, 50)), ((300, 30), (320, 380))]:
    cv2.line(damaged, p1, p2, (0, 0, 0), 5)
    cv2.line(mask, p1, p2, 255, 5)

print(f"Damaged image: {damaged.shape}, mask area: {(mask > 0).sum()} px")

# Two algorithms:
inpaint_telea = cv2.inpaint(damaged, mask, 3, cv2.INPAINT_TELEA)
inpaint_ns    = cv2.inpaint(damaged, mask, 3, cv2.INPAINT_NS)

show_grid([damaged, mask, inpaint_telea, inpaint_ns],
          ["Damaged input", "Mask of scratches", "TELEA algorithm", "Navier-Stokes algorithm"],
          cols=2, figsize=(12, 9))

# === Seamless cloning: paste the cat onto the rocket scene without a hard seam ===
src = cv2.imread('images/chelsea.jpg')   # cat
dst = cv2.imread('images/rocket.jpg')    # destination scene
print(f"Source (cat): {src.shape}, Dest (rocket): {dst.shape}")

# Build a mask of the cat — full image white means "use the whole src as the source patch"
src_mask = 255 * np.ones(src.shape[:2], np.uint8)
center = (dst.shape[1] // 2, dst.shape[0] // 2 + 50)

# NORMAL_CLONE blends gradients; MIXED_CLONE blends src+dst gradients (good for textured dst)
clone_normal = cv2.seamlessClone(src, dst, src_mask, center, cv2.NORMAL_CLONE)
clone_mixed  = cv2.seamlessClone(src, dst, src_mask, center, cv2.MIXED_CLONE)

# For comparison: a naive paste (just copy pixels) — you can see the seam
naive = dst.copy()
sh, sw = src.shape[:2]
y0, x0 = center[1] - sh // 2, center[0] - sw // 2
naive[y0:y0+sh, x0:x0+sw] = src

show_grid([src, dst, naive, clone_normal, clone_mixed],
          ["Source (cat)", "Destination", "Naive paste (visible seam)",
           "NORMAL_CLONE", "MIXED_CLONE"],
          cols=2, figsize=(13, 11))

"""---
# 19. 🌅 HDR Imaging — Combining Multiple Exposures

A single photo can capture only ~6 stops of dynamic range. Real scenes (sunlit clouds + shadowed interior) span 14+ stops. **HDR** captures multiple exposures and fuses them.

OpenCV provides:
- `cv2.createMergeMertens()` — *exposure fusion*, no exposure-time information needed (simplest)
- `cv2.createMergeDebevec()` — true HDR radiance map (needs exposure times)
- `cv2.createTonemapReinhard()` — compress HDR back to displayable range

We simulate three exposures by gamma-shifting one image.

"""

orig = cv2.imread('images/coffee.jpg')

# Simulate underexposed / normal / overexposed
def gamma(img, g):
    inv = 1.0 / g
    table = (np.arange(256) / 255.0) ** inv * 255.0
    return cv2.LUT(img, table.astype(np.uint8))

under  = gamma(orig, 0.4)
normal = orig
over   = gamma(orig, 2.5)
print("Mean pixel intensity per exposure:")
print(f"  under  : {under.mean():.1f}")
print(f"  normal : {normal.mean():.1f}")
print(f"  over   : {over.mean():.1f}")

# === Mertens exposure fusion (simplest, no exposure times) ===
merge_mertens = cv2.createMergeMertens()
fusion = merge_mertens.process([under, normal, over])
fusion = np.clip(fusion * 255, 0, 255).astype(np.uint8)

show_grid([under, normal, over, fusion],
          ["Underexposed", "Normal", "Overexposed", "Mertens fusion"],
          cols=2, figsize=(12, 9))

"""---
# 20. 🧠 Deep Learning with `cv2.dnn`

OpenCV's `dnn` module **runs pre-trained neural networks** without requiring TensorFlow / PyTorch / ONNXRuntime. Supported formats: ONNX, TensorFlow, Caffe, Darknet, Torch.

It is **inference-only** (no training). For robotics, this is ideal: small Docker, fast startup, OpenCL/CUDA backends for on-device acceleration.

We won't download a 100 MB model here, but we'll demonstrate the API end-to-end with a tiny synthetic network so you can see exactly how to plug in any real model.

"""

# === The standard cv2.dnn workflow ===
# 1. net = cv2.dnn.readNet(model_path, [config_path])
# 2. blob = cv2.dnn.blobFromImage(img, scalefactor, size, mean, swapRB, crop)
# 3. net.setInput(blob)
# 4. outputs = net.forward([output_layer_names])
# 5. parse outputs (model-specific)

# Inspect the parameters of blobFromImage — the most error-prone step
img = cv2.imread('images/astronaut.jpg')
blob = cv2.dnn.blobFromImage(
    img,
    scalefactor=1/255.0,    # most modern nets expect [0, 1] inputs
    size=(224, 224),         # the model's expected input resolution
    mean=(0.485, 0.456, 0.406),  # ImageNet means (per-channel) — subtracted
    swapRB=True,             # BGR -> RGB (most models trained on RGB)
    crop=False,              # if True, center-crops to size after resizing
)

print(f"Input image     : {img.shape}, dtype={img.dtype}")
print(f"Output blob     : {blob.shape}")
print(f"  Format        : NCHW = (batch=1, channels=3, height=224, width=224)")
print(f"Blob value range: [{blob.min():.3f}, {blob.max():.3f}]")
print()

# Available backends and targets
print("DNN backends and targets:")
print(f"  Default backend: {cv2.dnn.DNN_BACKEND_DEFAULT}")
print(f"  OpenCV backend : {cv2.dnn.DNN_BACKEND_OPENCV}")
print(f"  CUDA backend   : {cv2.dnn.DNN_BACKEND_CUDA}  (if compiled with CUDA)")
print(f"  CPU target     : {cv2.dnn.DNN_TARGET_CPU}")
print(f"  CUDA target    : {cv2.dnn.DNN_TARGET_CUDA}")
print()
print("To run on GPU you would call:")
print("    net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)")
print("    net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)")

"""## 20.1 Real-world usage pattern

Here is the canonical recipe for any classification model in ONNX format. Replace the model URL with your own (MobileNet, ResNet, YOLO, etc.) and adjust the post-processing.

```python
# --- TEMPLATE: classification with an ONNX model ---
# 1. Load
net = cv2.dnn.readNet('model.onnx')
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_OPENCV)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CPU)

# 2. Pre-process
blob = cv2.dnn.blobFromImage(img, 1/255.0, (224, 224), (0.485, 0.456, 0.406),
                              swapRB=True, crop=False)
net.setInput(blob)

# 3. Run
out = net.forward()          # shape (1, 1000) for ImageNet
idx = int(np.argmax(out))
print(f"Predicted class index: {idx}, score: {out[0, idx]:.3f}")
```

For object detection (YOLO/SSD) the post-processing differs (bounding boxes + NMS), but `readNet`, `blobFromImage`, and `forward` are identical.

---
# 21. 🏷️ ArUco Markers — Robot Fiducials

**ArUco markers** are square binary patterns. Each carries a unique ID; they are extremely fast to detect, robust to lighting, and standard in robotics for:

- **AR overlays** anchored to a physical marker
- **Robot pose estimation** (drop a marker on the floor → robot knows exactly where it is)
- **Hand-eye calibration**, **multi-camera registration**, **bin-picking targets**

The `cv2.aruco` API changed slightly in OpenCV 4.7. We handle both styles.
"""

# Create a printable ArUco marker
# 4x4_50 means 4x4 internal grid, 50 unique IDs in the dictionary
HAS_NEW_API = hasattr(cv2.aruco, 'getPredefinedDictionary')

if HAS_NEW_API:
    aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
    print("Using new (4.7+) aruco API")
else:
    aruco_dict = cv2.aruco.Dictionary_get(cv2.aruco.DICT_4X4_50)
    print("Using legacy aruco API")

# Generate marker images for IDs 0..3
fig, axes = plt.subplots(1, 4, figsize=(12, 3))
for ax, marker_id in zip(axes, [0, 1, 2, 3]):
    if HAS_NEW_API:
        m = cv2.aruco.generateImageMarker(aruco_dict, marker_id, 200)
    else:
        m = cv2.aruco.drawMarker(aruco_dict, marker_id, 200)
    ax.imshow(m, cmap='gray'); ax.set_title(f"ID {marker_id}"); ax.axis('off')
plt.tight_layout(); plt.show()

# === Detect markers in a synthetic scene with several markers placed in it ===
scene = np.full((600, 800, 3), 220, np.uint8)
ids_to_place = [3, 7, 17]
for i, mid in enumerate(ids_to_place):
    if HAS_NEW_API:
        m = cv2.aruco.generateImageMarker(aruco_dict, mid, 100)
    else:
        m = cv2.aruco.drawMarker(aruco_dict, mid, 100)
    m_bgr = cv2.cvtColor(m, cv2.COLOR_GRAY2BGR)
    y0 = 100 + i * 150
    x0 = 100 + i * 200
    scene[y0:y0+100, x0:x0+100] = m_bgr

# Detect
if HAS_NEW_API:
    params = cv2.aruco.DetectorParameters()
    detector = cv2.aruco.ArucoDetector(aruco_dict, params)
    corners, ids, rejected = detector.detectMarkers(scene)
else:
    params = cv2.aruco.DetectorParameters_create()
    corners, ids, rejected = cv2.aruco.detectMarkers(scene, aruco_dict, parameters=params)

print(f"\nMarkers detected: {0 if ids is None else len(ids)}")
if ids is not None:
    print(f"Detected IDs: {ids.ravel().tolist()}")
    for c, i in zip(corners, ids.ravel()):
        center = c[0].mean(axis=0)
        print(f"  ID={i}: center=({center[0]:.1f}, {center[1]:.1f})")

vis = scene.copy()
if ids is not None:
    cv2.aruco.drawDetectedMarkers(vis, corners, ids)

show(vis, title="ArUco detection — IDs printed on detected markers", figsize=(10, 7))

"""### 🤖 Pose estimation from a single ArUco marker

In a robotics deployment, once you detect a marker you call `cv2.solvePnP` (using the marker's corners as 4 known 3D points and the calibrated camera matrix) to get the marker's full 6-DOF pose relative to the camera. Combined with a known marker location in the world, this gives **the camera pose in the world** — i.e., where the robot is.

```python
# Pseudocode for an actual robot:
marker_size_m = 0.05  # 5 cm
obj_pts = np.array([[-marker_size_m/2,  marker_size_m/2, 0],
                     [ marker_size_m/2,  marker_size_m/2, 0],
                     [ marker_size_m/2, -marker_size_m/2, 0],
                     [-marker_size_m/2, -marker_size_m/2, 0]], np.float32)
ok, rvec, tvec = cv2.solvePnP(obj_pts, corners[0], K, dist)
# rvec, tvec  =  marker pose in camera frame
```

---
# 22. ⚡ Performance Tips & Profiling

For real-time robot vision (≥ 30 FPS), every millisecond counts.
"""

# === Built-in timing ===
img = cv2.imread('images/astronaut.jpg')

# cv2.getTickCount + cv2.getTickFrequency = high-resolution timer
t1 = cv2.getTickCount()
for _ in range(50):
    cv2.GaussianBlur(img, (15, 15), 0)
t2 = cv2.getTickCount()
elapsed_ms = (t2 - t1) / cv2.getTickFrequency() * 1000
print(f"50x GaussianBlur(15x15): {elapsed_ms:.1f} ms total, {elapsed_ms/50:.2f} ms each")

# === Optimization toggle ===
print(f"\ncv2.useOptimized() default: {cv2.useOptimized()}  (uses SSE/AVX/NEON SIMD if True)")

# === OpenCL ===
print(f"OpenCL available: {cv2.ocl.haveOpenCL()}")
if cv2.ocl.haveOpenCL():
    print(f"OpenCL device   : {cv2.ocl.Device.getDefault().name() if hasattr(cv2.ocl, 'Device') else 'n/a'}")

# === Threading info ===
print(f"\nThreads used by OpenCV: {cv2.getNumThreads()}")
print(f"Number of logical CPUs: {cv2.getNumberOfCPUs()}")

"""### Practical speed tips (in order of impact)

1. **Resize first.** Most vision algorithms scale super-linearly with pixel count. For 1080p input, downscaling to 720p is often "free" accuracy-wise and ~2.25× faster.
2. **Convert to grayscale early** if color isn't needed. 3× less data.
3. **Pre-allocate output buffers** when calling functions in a loop. Many functions accept a `dst=` parameter.
4. **Use `cv2.UMat`** for transparent OpenCL acceleration (`umat = cv2.UMat(img)`). Operations on `UMat` run on GPU when available.
5. **Avoid Python loops over pixels.** Use NumPy / `cv2.LUT` / vectorized ops.
6. **Set `cv2.setNumThreads(N)`** to cap threads on a small robot CPU and leave headroom for other tasks.
7. **`cv2.dnn` with CUDA backend** for neural nets — often 5–20× faster than CPU.

"""

# Demonstrate UMat / OpenCL transparently
img = cv2.imread('images/astronaut.jpg')

# CPU
t1 = cv2.getTickCount()
for _ in range(20):
    out_cpu = cv2.GaussianBlur(img, (31, 31), 0)
t_cpu = (cv2.getTickCount() - t1) / cv2.getTickFrequency()

# UMat (uses OpenCL if available, falls back to CPU otherwise)
img_umat = cv2.UMat(img)
t1 = cv2.getTickCount()
for _ in range(20):
    out_umat = cv2.GaussianBlur(img_umat, (31, 31), 0)
out_arr = out_umat.get()  # pull result back to CPU
t_umat = (cv2.getTickCount() - t1) / cv2.getTickFrequency()

print(f"CPU  20x GaussianBlur(31x31): {t_cpu*1000:.1f} ms ({t_cpu*1000/20:.2f} ms/iter)")
print(f"UMat 20x GaussianBlur(31x31): {t_umat*1000:.1f} ms ({t_umat*1000/20:.2f} ms/iter)")
print("(On Colab CPU runtime, UMat may be similar to or slower than CPU; "
      "on a real GPU it is typically much faster.)")

"""---
# 23. 🎁 Useful Tricks & Gotchas

A grab-bag of patterns that will save you time on real projects.

## 23.1 LUT — fast pixel-value remapping

A look-up table maps each input intensity (0–255) to an output intensity. Implements gamma correction, contrast curves, false-coloring, etc., **with one C call** instead of a Python loop.
"""

img = cv2.imread('images/astronaut.jpg')

# Gamma correction via LUT
def build_gamma_lut(g):
    return np.array([((i / 255) ** (1.0 / g)) * 255 for i in range(256)],
                    dtype=np.uint8)

lut_dark   = build_gamma_lut(0.5)
lut_bright = build_gamma_lut(2.0)

# cv2.LUT is much faster than NumPy fancy indexing on uint8 arrays
out_dark   = cv2.LUT(img, lut_dark)
out_bright = cv2.LUT(img, lut_bright)

# Apply a colormap (LUT-style false coloring) to a grayscale image
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
heatmap = cv2.applyColorMap(gray, cv2.COLORMAP_JET)

show_grid([img, out_dark, out_bright, heatmap],
          ["Original", "Gamma 0.5 (darker)", "Gamma 2.0 (brighter)", "JET colormap on grayscale"],
          cols=2, figsize=(11, 9))

"""## 23.2 `cv2.copyMakeBorder` — padding without arithmetic

Need a few pixels of padding for a convolution or to avoid edge effects? `copyMakeBorder` does it cleanly, with several extrapolation modes.

"""

img = cv2.imread('images/coffee.jpg')

modes = {
    'CONSTANT'   : cv2.BORDER_CONSTANT,
    'REPLICATE'  : cv2.BORDER_REPLICATE,
    'REFLECT'    : cv2.BORDER_REFLECT,
    'REFLECT_101': cv2.BORDER_REFLECT_101,
    'WRAP'       : cv2.BORDER_WRAP,
}

outs = []
for name, m in modes.items():
    padded = cv2.copyMakeBorder(img, 50, 50, 50, 50, m, value=(0, 255, 0))
    outs.append(padded)

show_grid(outs, list(modes.keys()), cols=3, figsize=(15, 8))

"""## 23.3 `connectedComponentsWithStats` — count & label blobs in one call

Stronger than `findContours` when you also want areas, bounding boxes, and centroids.

"""

coins = cv2.imread('images/coins.jpg', cv2.IMREAD_GRAYSCALE)
_, bw = cv2.threshold(coins, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
bw = cv2.morphologyEx(bw, cv2.MORPH_OPEN, np.ones((3, 3), np.uint8), iterations=2)

n_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(bw, connectivity=8)
print(f"Labels (incl. background): {n_labels}")
print(f"Stats shape: {stats.shape}  (label, [x, y, w, h, area])")
print(f"Centroids shape: {centroids.shape}")

# Print info for each non-background label
print("\nLabel | x   y    w   h   area  centroid")
print("------|----------------------------------")
for i in range(1, n_labels):
    x, y, w, h, area = stats[i]
    cx, cy = centroids[i]
    print(f"{i:5d} | {x:3d} {y:3d}  {w:3d} {h:3d}  {area:4d}  ({cx:5.1f},{cy:5.1f})")

# Pretty visualization
rng = np.random.default_rng(0)
colors = rng.integers(50, 255, size=(n_labels, 3), dtype=np.uint8)
colors[0] = 0  # background black
vis = colors[labels]
show(vis, title=f"connectedComponentsWithStats — {n_labels - 1} blobs")

"""## 23.4 Mouse / GUI replacements in Colab

`cv2.imshow`, `cv2.namedWindow`, `cv2.setMouseCallback`, and `cv2.createTrackbar` all require a desktop GUI and **don't work in Colab**.

Workarounds:
- For interactive sliders, use `ipywidgets` instead.
- For mouse coords, use Plotly or the deprecated `google.colab.output.eval_js`.
- For previewing webcam, use `IPython.display.display` with `JavaScript` snippets (search for "Colab webcam").

For a robotics project on a real machine, `cv2.imshow` etc. work fine in a normal Python session.

"""

# Example: replace cv2.createTrackbar with an ipywidgets slider
try:
    from ipywidgets import interact, IntSlider
    img = cv2.imread('images/coffee.jpg', cv2.IMREAD_GRAYSCALE)

    def show_threshold(t=127):
        _, bw = cv2.threshold(img, t, 255, cv2.THRESH_BINARY)
        plt.figure(figsize=(6, 4))
        plt.imshow(bw, cmap='gray', vmin=0, vmax=255)
        plt.title(f"Threshold = {t}"); plt.axis('off'); plt.show()

    # In the Colab UI, this creates a draggable slider for the threshold value
    interact(show_threshold, t=IntSlider(min=0, max=255, step=1, value=127))
    print("\n(If you see a slider above, drag it to change the threshold.)")
except ImportError:
    print("ipywidgets not installed — but it is on Colab by default.")

"""## 23.5 Subpixel accuracy with `cornerSubPix`

If you find a corner with `goodFeaturesToTrack` or `findChessboardCorners`, you only get **integer pixel** locations. `cornerSubPix` refines them to ~0.01 px accuracy by fitting a quadratic to the gradient. **Always use it** before calibration or pose estimation.

(Already used in Section 11.)

## 23.6 `cv2.minAreaRect`, `cv2.minEnclosingCircle`, `cv2.fitEllipse`

For a contour, get the **rotated bounding box**, **smallest enclosing circle**, or **best-fit ellipse**. Useful for:
- Object orientation (`minAreaRect` returns the rotation angle)
- Robot grasp pose (the rotated box is a planar grasp candidate)
- Shape classification (compare contour area to its enclosing-shape area)
"""

# Find the cat silhouette and characterize its shape
horse = cv2.imread('images/horse.png', cv2.IMREAD_GRAYSCALE)
_, bw = cv2.threshold(horse, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(bw, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
biggest = max(contours, key=cv2.contourArea)
print(f"Biggest contour: {len(biggest)} points, area={cv2.contourArea(biggest):.0f}")

vis = cv2.cvtColor(horse, cv2.COLOR_GRAY2BGR)

# Axis-aligned bounding rectangle
x, y, w, h = cv2.boundingRect(biggest)
cv2.rectangle(vis, (x, y), (x + w, y + h), (255, 0, 0), 2)

# Rotated min-area rectangle
rect = cv2.minAreaRect(biggest)
print(f"minAreaRect: center=({rect[0][0]:.1f},{rect[0][1]:.1f}), "
      f"size=({rect[1][0]:.1f},{rect[1][1]:.1f}), angle={rect[2]:.2f}°")
box = np.int32(cv2.boxPoints(rect))
cv2.drawContours(vis, [box], 0, (0, 255, 0), 2)

# Min enclosing circle
(cx, cy), r = cv2.minEnclosingCircle(biggest)
print(f"minEnclosingCircle: center=({cx:.1f},{cy:.1f}), r={r:.1f}")
cv2.circle(vis, (int(cx), int(cy)), int(r), (0, 255, 255), 2)

# Best-fit ellipse
if len(biggest) >= 5:
    ellipse = cv2.fitEllipse(biggest)
    cv2.ellipse(vis, ellipse, (255, 0, 255), 2)
    print(f"fitEllipse: center=({ellipse[0][0]:.1f},{ellipse[0][1]:.1f}), "
          f"axes=({ellipse[1][0]:.1f},{ellipse[1][1]:.1f}), angle={ellipse[2]:.2f}°")

show(vis, title="Bounding shapes — bbox(blue), rotRect(green), circle(yellow), ellipse(magenta)",
     figsize=(7, 7))

"""## 23.7 `cv2.matchShapes` — Hu moments for shape matching

Compare two contours by their seven **Hu moment invariants** — invariant to translation, rotation, and scale. Tiny return value = very similar shapes.

"""

# Compare the cat silhouette to a rotated/scaled version of itself, vs a different shape
horse  = cv2.imread('images/horse.png', cv2.IMREAD_GRAYSCALE)
_, bw1 = cv2.threshold(horse, 127, 255, cv2.THRESH_BINARY)
c1, _  = cv2.findContours(bw1, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
c1     = max(c1, key=cv2.contourArea)

# Rotate + scale the binary image to make a "different" view of the same horse
M = cv2.getRotationMatrix2D((horse.shape[1]/2, horse.shape[0]/2), 30, 1.3)
bw2 = cv2.warpAffine(bw1, M, (horse.shape[1], horse.shape[0]))
c2, _  = cv2.findContours(bw2, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
c2     = max(c2, key=cv2.contourArea)

# A genuinely different shape: a square
sq = np.zeros((300, 300), np.uint8)
cv2.rectangle(sq, (50, 50), (250, 250), 255, -1)
c3, _ = cv2.findContours(sq, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
c3 = c3[0]

print("matchShapes (lower = more similar, 0 = identical):")
print(f"  horse vs. rotated horse: {cv2.matchShapes(c1, c2, cv2.CONTOURS_MATCH_I1, 0.0):.5f}")
print(f"  horse vs. square       : {cv2.matchShapes(c1, c3, cv2.CONTOURS_MATCH_I1, 0.0):.5f}")

"""## 23.8 Color quantization with `cv2.kmeans`

Reduce an image to N dominant colors. Useful for: artistic stylization, palette extraction, segmenting by color region for robotic sorting.

"""

img = cv2.imread('images/coffee.jpg')
Z = img.reshape(-1, 3).astype(np.float32)

# K-means: cluster pixels by color
K = 6
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 20, 1.0)
compactness, labels, centers = cv2.kmeans(Z, K, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)
print(f"K-means: K={K}, compactness={compactness:.0f}")
print(f"Cluster centers (BGR):\n{centers.astype(int)}")

# Re-paint the image using only the cluster center colors
quantized = centers[labels.flatten()].reshape(img.shape).astype(np.uint8)

show_grid([img, quantized], ["Original", f"Quantized to {K} colors"],
          cols=2, figsize=(13, 5))

# Show the palette
palette = np.zeros((50, 50 * K, 3), np.uint8)
for i, c in enumerate(centers.astype(np.uint8)):
    palette[:, i*50:(i+1)*50] = c
show(palette, title="Dominant color palette", figsize=(8, 1.5))

"""---
# 🏁 Wrap Up

You now have hands-on familiarity with the **production-grade** parts of OpenCV used in real computer vision and robotics systems:

**Geometry & calibration**: pyramids, calibration, undistortion, homographies, PnP, stereo
**Detection & tracking**: SIFT/AKAZE/BRISK features, RANSAC matching, ArUco markers, modern trackers, optical flow
**Image processing**: watershed, GrabCut, distance transforms, Hough, template matching, Fourier
**Photo techniques**: stitching, inpainting, seamless cloning, HDR
**ML integration**: `cv2.dnn` for ONNX/TF/Caffe inference
**Engineering**: performance tools, LUTs, ipywidgets sliders, kmeans, shape matching

## 🛣️ Suggested next steps

| If you want to build... | Look into... |
|-------------------------|--------------|
| A vision-guided robot arm | hand–eye calibration, ArUco for end-effector tracking |
| A SLAM system | `cv2.calcOpticalFlowPyrLK`, ORB features, [ORB-SLAM3](https://github.com/UZ-SLAMLab/ORB_SLAM3), feature-based bundle adjustment |
| Drone aerial mapping | image stitching pipeline + GPS/IMU fusion |
| Industrial defect detection | template matching + DNN classifier + good lighting (the most underrated factor!) |
| AR app | ArUco / Aruco-marker pose + OpenGL / Three.js overlay |
| Autonomous driving prototype | Hough lines + dense optical flow + DNN object detector |

## 📚 Authoritative resources

- **OpenCV docs**: https://docs.opencv.org/
- **OpenCV tutorials**: https://docs.opencv.org/4.x/d9/df8/tutorial_root.html
- **Multiple View Geometry** (Hartley & Zisserman) — the bible for the math behind stereo / homographies / calibration
- **Probabilistic Robotics** (Thrun, Burgard, Fox) — the bridge from perception to robot decision-making

Happy building! 🚀

"""